### ISSUE TITLE
inflections component: add current word form

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#100]
add the current word form (including stem and suffix) to the vue component based inflection table display

e.g. 

![screenshot from 2018-05-30 14-15-18](https://user-images.githubusercontent.com/644870/40739375-fc4bffec-6413-11e8-8638-f403128fe0dd.png)

**Comment by irina060981** [comment]
https://github.com/alpheios-project/components/pull/108

1) Created the component - wordForms - it generates the following form "targetWord" (forms) for the inflections component

2) Forms are created in the component based on the language model direction

3) Added unit tests for the wordForms component
