### ISSUE TITLE
incorrect showing inflection's table on the panel

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/components#102]
Description:

1) For some words Inflections tab on the panel is available and it shows a blank page (if clicks them first) - for example "bene"
![image](https://user-images.githubusercontent.com/12377640/40871639-9698b5de-6682-11e8-9845-843b55127698.png)

2) If you clicked on the otner word first (for example "cepit"), it will show inflections tab with correct data
![image](https://user-images.githubusercontent.com/12377640/40871640-aca8a2e4-6682-11e8-87e4-8d24dbdb2141.png)

3) And then you again click on the "bene" word, it will show inflection data (wideTable) for the previous word ("cepit").
![image](https://user-images.githubusercontent.com/12377640/40871642-ba072adc-6682-11e8-893a-ebbcc55a854b.png)

4) And if you click on the Full table button, it prints error to console.
![image](https://user-images.githubusercontent.com/12377640/40871647-c60a1862-6682-11e8-8810-9ed4a918bf6d.png)

Investigation results:

1) Inflection table shows from this.selectedView (inflection component).
   This.selectedView is made from ViewSet based on the lemma.
   And for the "bene" it returns ViewSet  without partsOfSpeech (for cepit it returns with partsOfSpeech)

  That is why for bene - the.selectedView is ''
2) The table is printed using renderInflections. It executes only if selectedView is not empty
   
  So for bene renderInflections doesn't execute, and for cepit - executes.
3) The table is printed to this tag
   
    <div v-show="!selectedView.hasComponentData" class="variant2">
           <div :id="elementIDs.wideView" class=""></div>
          .......
     </div>

And this condition !selectedView.hasComponentData is true for both variants

**Comment by balmas** [comment]
@kirlat I wonder if this bug is what caused the inflection tables not to appear in the pwa.

**Comment by balmas** [comment]
This appears to have solved the problem for the PWA. Leaving open to port those changes to the UIController in components for the Beta release. Will also enter an issue for the webextension.

**Comment by kirlat** [comment]
This should be fixed with cf250a133e59057ccbc2bb77e1177d7ea08e1d19. A webextension `comp-i102` branch code can be used for testing.

**Comment by kirlat** [comment]
An webextension download link is https://github.com/alpheios-project/webextension/archive/comp-i102.zip

**Comment by monzug** [comment]
also subii has been fixed. Thanks
