### ISSUE TITLE
move grammar not found notice back to top of the panel

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#11]
moved from https://github.com/alpheios-project/webextension/issues/82
when we moved the provider for the grammar to the bottom of the panel, that caused the not found message also to display there because we overloaded the provider to display that. Use a real notification message instead and have it display at the top of the panel

**Comment by irina060981** [comment]
I have fixed issue - 
https://github.com/alpheios-project/components/pull/118
simply hide iframe in grammar component if url is not defined

Other changes - I have corrected tests (the same as for #115)

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
I got this message
"the requested grammar resource is not currently available" at the bottom of the panel. not sure if this is part of the scope of this fix, @balmas ?

**Comment by balmas** [comment]
hmm. yes I think changes made for the PWA to wrap the iframe in a parent frame to enable scrolling broke this. Sending back to @irina060981.

**Comment by irina060981** [comment]
@monzug and @balmas,  I have fixed it here - 
https://github.com/alpheios-project/components/pull/161

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
I get correctly the message at the top of the page: The requested grammar resource is not currently available.
would it be possible to change the font of the message to be consistent with the other message that are generated in option panel such as Inflection table are not available etc? Thanks

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
Reading for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-5
