### ISSUE TITLE
styles for reskin-font-color component need to be bound to element

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#121]
If you use the webextension on page which has styles defined on an `li` element, it causes the reskin-font-color component to be displayed incorrectly. See attached from use on http://www.thelatinlibrary.com/apuleius/apuleius4.shtml which has the following styles defined on the `li` element:
```
list-style-type: none; 
font-size: 13pt; 
font-family: "book antiqua","times new roman",times; 
text-align: justify; 
text-indent: 0em; 
padding-left: 2em; 
padding-right: 2em; 
```
We need to explicitly define the styles for this component on an li element so that it takes precedence over the page styles.

**Comment by irina060981** [comment]
I have added fixes for reskin panel styles.
![image](https://user-images.githubusercontent.com/12377640/41636677-3cef1aae-7493-11e8-9095-c7e3de3167d9.png)

**Comment by irina060981** [comment]
Merged and closed
