### ISSUE TITLE
Develop a universal link format to navigate between components

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/components#125]
For navigation we probably need to establish some more or less universal link format. I think of something that would be able to identify a component (panel/popup), then one or more sub-components (a panel within a panel) and then some other elements (a specific table within a panel). We could have an arbitrary number of nested components of different types.

A link format extendable so it'll be able to cover elements we do not have now but will have in the future. If there are some standards or best practices here, it would be better to follow them too.

Would need that for inflection tables navigation and probably for other purposes too.

Maybe instead of `openTab()`, or `panel.open()` we could have some universal method like `navigate(reflink)` that will open a popup or a panel, switch to a corresponding tab, and scroll to a proper element. That would allow to unify our navigation.

Each component could implement its own version of `navigate()` that will know how to handle component's specifics.

**Comment by balmas** [comment]
Maybe we could use the schema.org BreadcrumbList  schema?

https://schema.org/BreadcrumbList
https://developers.google.com/search/docs/data-types/breadcrumb

**Comment by balmas** [comment]
likely to be covered with use of Vuex?

**Comment by kirlat** [comment]
Yes, I think so. Using common Vuex store would make this way much simpler.

**Comment by balmas** [comment]
obsolete with use of Vuex.
