### ISSUE TITLE
add data-alpheios-ignore="all" to the panel and popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#129]
with #17 we can now disable alpheios word lookup events for selected portions of a page. We should add this attribute to the main panel and popup elements. (Eventually we may want to selectively enable parts of the panel and popup contents, but for now we can just disable it entirely)

**Comment by kirlat** [comment]
Should be in master now.

**Comment by balmas** [comment]
@monzug to verify this you should see that double-clicking on words in any of the Alpheios panels or popups does not activate the lookup behavior.

**Comment by monzug** [comment]
verified. chrome and firefox
