### ISSUE TITLE
experiment with different treatments for separating different words and senses in the popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#14]
moved from https://github.com/alpheios-project/webextension/issues/60

Mark suggested using an approach which numbers each distinct entry. We need to explore few different treatments with different possible scenarios including:

1. when a word produces multiple lemmas
2. when a lemma has multiple definitions

**Comment by balmas** [comment]
@irina060981 I would like to discuss this issue with you before you start working on it, so let me know when you are ready to get started on it.

**Comment by balmas** [comment]
![image](https://user-images.githubusercontent.com/644870/39483749-64e73f38-4d41-11e8-9c9e-7c1b6bca1c5f.png)
![dv-cepit-common variant](https://user-images.githubusercontent.com/644870/39483750-64f5f870-4d41-11e8-858a-0e8574b704ca.PNG)
![dv-placito-many lemmas-2](https://user-images.githubusercontent.com/644870/39483751-650723c0-4d41-11e8-8ec2-4ebd270377f1.PNG)
![dv-mala-several definitions-2](https://user-images.githubusercontent.com/644870/39483752-6517769e-4d41-11e8-8f0d-608498a6ace0.PNG)
![dv-mare-several inflections-2](https://user-images.githubusercontent.com/644870/39483753-652bd058-4d41-11e8-8c21-67a016cc69eb.PNG)
![dv-bene-no inflections-2](https://user-images.githubusercontent.com/644870/39483754-653c395c-4d41-11e8-83f4-f5cb6079dc79.PNG)

Images from first proposal by @irina060981

**Comment by balmas** [comment]
Here's an alternative suggested by @abrasax 

[popup-format.pdf](https://github.com/alpheios-project/components/files/1964586/popup-format.pdf)

@irina060981 could you try applying this approach so that we could present both for comparison? I think that it's worth trying to implement this with the code to see what questions come up in implementation. Thank you!

**Comment by irina060981** [comment]
Here it is in other arranging order - first inflections (experiments with different situations)

![3-caeli-new-layout](https://user-images.githubusercontent.com/12377640/39524523-966ee1f2-4e5c-11e8-884b-c260debb6d7e.PNG)

**Comment by balmas** [comment]
@irina060981 can we see a version of each design without the lines separating each section?

**Comment by irina060981** [comment]
Ready - I've prepared with several words

**caeli**
![_caeli-new-layout-v1](https://user-images.githubusercontent.com/12377640/39579365-f5bf137a-4f29-11e8-91ab-2451044208c5.PNG)
![_caeli-new-layout-v2](https://user-images.githubusercontent.com/12377640/39579368-f5f18896-4f29-11e8-9227-0b195dfbd842.PNG)

**mare**
![_mare-new-layout-v1](https://user-images.githubusercontent.com/12377640/39579381-fe7f6c26-4f29-11e8-927d-3ee82d4ed2eb.PNG)
![_mare-new-layout-v2](https://user-images.githubusercontent.com/12377640/39579382-feaed556-4f29-11e8-9f23-de0997cb48c4.PNG)

**cupidinibus**
![_cupidinibus-new-layout-v1](https://user-images.githubusercontent.com/12377640/39579405-0d0e4cee-4f2a-11e8-9272-47c164e09513.PNG)
![_cupidinibus-new-layout-v2](https://user-images.githubusercontent.com/12377640/39579407-0d4014f4-4f2a-11e8-9675-571c1186ad67.PNG)

**Comment by irina060981** [comment]
I have updated this branch with new structure for options, with new build process and with lookup-component.
The design of this reskin is based on simple changing child-componets in morph.vue

morph-inner.vue - current production layout
morph-inner-v1.vue - my design with numbers  (first principal parts)
morph-inner-v2.vue - my design with numbers  (first inflections)

**Comment by balmas** [comment]
discussed with @abrasax today. we would like to go ahead with the first design proposal (first principal parts). A few additional changes to be made:

- [ ] move frequency to the same line as the lemma and principal parts (removing the colon after the lemma/principal parts and putting a little space in between that and the frequency
- [ ] order by frequency (I think this was in the mockups but the implementation doesn't have it yet - need to be sure to not fail if no frequency is present in the lemma features as this isn't always there)
- [ ] remove the colon in the inflection groups

**Comment by irina060981** [comment]
1) Added changes to lookup component - adding highlight color and place lookup block to the panel

**Comment by irina060981** [comment]
3. Removed colon from inflrctions group

**Comment by irina060981** [comment]
About order by frequency:
After fetching lexemes there is a sort homonym.lexemes.sort(Lexeme.getSortByTwoLemmaFeatures(Feature.types.frequency, Feature.types.part))
I didn't change it - so it should sort by frequency feature.

I have examined several words and the function in Lexemes and it really sorts by the field sort order of the frequency feature.
But If have a look at different words and its lemmas - we could see that all variants of features have the same sortOrder value = 1.
That is why We couldn't see the sorting.

Should I change it here in the function (create a local array with other sort order)?
Or should I search for the source with this data?

**Comment by balmas** [comment]
ah, the frequency not being obeyed is a bug :-) Tracked it down to this: https://github.com/alpheios-project/data-models/issues/23 So fixing the sorting doesn't need to be addressed here but instead will be fixed with that issue. Thanks!!

**Comment by irina060981** [comment]
Thank you, Bridget, for the explanation. Should I get it for investigation or should I stop to woek on this issue?

**Comment by balmas** [comment]
I think you can just finish this issue without worrying about the ordering by frequency piece.  That will be addressed by fixing the other bug (which I will probably do since I'm halfway there). Thank you!

**Comment by irina060981** [comment]
Ok, should I merge it with some branch?

**Comment by balmas** [comment]
Is it correct that the the various designs are already in the reskin-font-color branch in the morph-inner components?

**Comment by balmas** [comment]
See also my comment at https://github.com/alpheios-project/components/pull/42#discussion_r188296303

**Comment by irina060981** [comment]
Yes - these different variants are placed in reskin-color-font branch.
I have integrated it there for being compatible with style changing effects.

**Comment by balmas** [comment]
Ok, so please proceed with finishing the changes for this item in that branch then. Thank you!

**Comment by irina060981** [comment]
ok!

**Comment by irina060981** [comment]
Move all changes to a new branch, that collects all my issues together:
lookup-reskin
https://github.com/alpheios-project/components/pull/68
