### ISSUE TITLE
web page in which the extension has a different look

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#149]
tested in Chrome extension. go to page https://mymemory.translated.net/
open any inflected table, the title has a blue background.

**Comment by irina060981** [comment]
From #checkins 
we could review styles to check
1) that we normalize panel and popup styles (without any applying skins, fonts or color styles)
2) that we have all styles for our classes for fonts, color - in Monica's case there should rewrite such situations (edited)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
@monzug you should be able to test this in the issues-inflection-tables-59 build

**Comment by monzug** [comment]
yes! works as expected. Verified
