### ISSUE TITLE
Full table/Collapse button missing in some tables

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#150]
the full table/collapse button is missing in the inflected table for the possum verb. to repro, enter possum in the lookup, then click on Inflect. button is missing. However the button is present in the irregular table where there is a match.

**Comment by kirlat** [comment]
This might be an expected behavior. "Collapse/Full table" button show or hides columns that have no suffix matches. However, some words, such as "possum", can have no suffix matches at all. In such cases the full table will always be shown, and it makes no reason to show "Collapse/Full table" as full table would be the only table state.

Please let me know if that makes sense or if there are other cases where it does not behave properly.

**Comment by monzug** [comment]
it does make sense now that I know the logic. it's confusing as you can see the button in very small tables (e.g. irregular verbs) and do not see the button in very large table with active and passive voice. let's think about this. Bridget?

**Comment by kirlat** [comment]
Maybe we should add an indicator that will display a current table format (full/compact) with a control to change it? So for tables that have only one format (full) there will be no change control, but there still be an indicator showing a current table format. Would that be less confusing? @balmas, @monzug, what do you think?

**Comment by balmas** [comment]
I think that's a reasonable suggestion. The only other idea I have off the top of my head is to add some explanatory text, e.g. something like "This table has been collapsed to show only columns with matching endings. Click 'Expand' to see the full table."

**Comment by kirlat** [comment]
Right now we have a single "Full/Compact" button at the top of the view. However, now we can have several tables below each other in each view. I think it is confusing as it is now as it is not clear to what table is this button related. Also, some tables in a view can be collapsed and some not and that adds confusion too.

I think it would make sense to have a button per table in our current configuration. Then we should remove a button from where it is currently and put it above each table in a view, so it will be clear that each table does have its own set of controls. The text explaining a table state can be put next to the button above the table too.

@balmas, @monzug, what do you think?

**Comment by balmas** [comment]
this sounds reasonable.

**Comment by kirlat** [comment]
Here is an updated that adds explanatory messages for each table state: https://github.com/alpheios-project/components/archive/comp-i150-i151.zip Please let me know what the exact wording of each message should be and what other corrections are required. Thanks!

**Comment by balmas** [comment]
Hmm. I think the wording is okay.  Could we just move it to the tooltip for the expand/collapse button rather than in the page? I think that might be sufficient. 

I also don't think we need to show anything when there is no button.

What do you think @monzug ?

**Comment by monzug** [comment]
I have a problem installing the build. I get the message that manifest file is missing and looking at dist folder, I do not see it there.

**Comment by balmas** [comment]
wrong link! Here's the correct one: https://github.com/alpheios-project/webextension/tree/comp-i150-i151

**Comment by kirlat** [comment]
Thanks, Bridget! The correct direct link for downloading is https://github.com/alpheios-project/webextension/archive/comp-i150-i151.zip.

**Comment by monzug** [comment]
I like it. Actually, I do not mind the message when there is no button.
Visually I do not like the one size table.  some tables (e.g. the supine will be interesting) are so streched that you get 'lost' in the table.

![strechingtable](https://user-images.githubusercontent.com/41396793/45683539-fee41a00-bb11-11e8-9502-8d41ed55568b.JPG)

**Comment by monzug** [comment]
Bridget, I am ok with the current status. the look of the table is very personal so passing to you

**Comment by balmas** [comment]
yikes I'm stressed to be the one imposing a ui design decision :-)  
I think I'll stick with my request though. I'd like the text to be moved to the tooltip of the button and not shown when there is no button.

**Comment by kirlat** [comment]
Updated. Removed messages shown above table, message text is shown in tooltip only

**Comment by balmas** [comment]
this is in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-8

**Comment by monzug** [comment]
Message is in tooltip now 2.0.3-8, tested in Firefox

**Comment by monzug** [comment]
@kirlat, question on the expand/collapse button.
it's missing from some verb views.
e.g.  iremus has expand button in voice-conj-mood  but there is no button in the conj-voice-mood and in mood-voice-conj.
in case of dicere , no tables have the button except for the infinitive. Is there a reason for this?

**Comment by kirlat** [comment]
If table is collapsed, the top-level column groups (columns that are grouped by a feature value at the very top of the table header) are hidden. We do that if those columns has no suffix or full matches.

However, if all top-level column groups has some suffix matches inside of one of their columns, we can hide none of these groups, and thus table cannot be collapsed. In such cases we do not show "Collapse/Expand" button for a table.

**Comment by monzug** [comment]
it does work as @kirlat explanation, except that there might be some stickiness due to previous view. this is issue  inflection-tables/issues/173
