### ISSUE TITLE
full table/collapse button not working properly

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#151]
enter dicere in the lookup, then click on Inflect. select the imperative table from verb drop-down. click on Full table, the full table is displayed. Now select imperative from drop-down. click on Collapse, the button become Full table, click a second time, the Full table is displayed. not sure if there should be a default mode when switching table.

**Comment by kirlat** [comment]
Please check https://github.com/alpheios-project/components/archive/comp-i150-i151.zip that should have this issues fixed.

**Comment by monzug** [comment]
This issue is fixed.
two minor things here:
1) I think Bridget requested to move the tooltip out of the table
2) for consistency, the tooltip should be "Show Full Table" and "Show Collapsed Table" or "Show full table" and "Show collapsed table" . Right, now we have "Show full Table".

**Comment by kirlat** [comment]
Switched all related message to sentence case to be consistent with other message texts throughout the webextension.

**Comment by balmas** [comment]
https://github.com/alpheios-project/webextension/tree/qa-2.0.3-8

**Comment by monzug** [comment]
Message has been reworked now see issue #150
