### ISSUE TITLE
port alignment prototype to components

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#152]
In https://github.com/alpheios-project/embed-lib/commit/64b6abfccbf15a726936fa1fd91c54ce23750bc1 I added some code to the alpheios embedded library to enable mouseover highlighting of embedded translation alignments. Some of it was lost with https://github.com/alpheios-project/embed-lib/commit/e43961f49a9a76152c138ddf82dd5ae589bf0bf4 but I'd like to port it to components anyway.

**Comment by irina060981** [comment]
Merged to components and closed
