### ISSUE TITLE
Page not found for verb participle (Greek)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#155]
When I click on the verb participle from the morphology page, I get page not found. however, it does work for other part of speech.
Not Found
The requested URL /smyth/xhtml/index.htm was not found on this server.
Bridget said that it could be a bug in the grammar index or in the way we pass the term to it from component.

**Comment by balmas** [comment]
this was a mismatch between the data - we were looking for 'verb participle' in the index entry for the grammars but they had it as 'verb_participle' (carry-over from V1). I have updated the Bennett and Smyth grammar indexes and these links should work now. (You may need to clear your browser cache to get the updated index file to be retrieved).  @monzug can you please verify that it's working? Thanks!

**Comment by monzug** [comment]
also conjunction  (e.g.  ἐπεὶ ) does not work

**Comment by balmas** [comment]
I just realized that there were two problems here - when a term isn't found in our index of the grammar, it should bring you to the index or table of contents of the grammar. The page we were trying to load for Smyth in that case was incorrectly specified. So, linking on conjunction in Greek now brings you to the Smyth table of contents.  

I'm not sure if there is a better place to link for conjunction in this grammar, what do you think @monzug ? there are sections for specific words used as conjunctions but the general concept of conjunction doesn't seem to be there.

**Comment by monzug** [comment]
apparently conjunction is only mention once in Chapter 2. table of contents is the best solution.
