### ISSUE TITLE
Suffix match is not highlighted in light color schema

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/components#157]
It seems that in a light color schema a suffix that is a partial match (a span with `infl-suff` and `infl-suff--suffix-match`) has the same text color as the rest of the suffixes (`rgb(51, 51, 51)`). Because of this, partial suffix matches are not highlighted. Probably we need to add a background color to it.

**Comment by balmas** [comment]
@irina060981 can you investigate? maybe this was introduced in the style normalization changes?

**Comment by balmas** [comment]
@irina060981 Kirill has a temporary fix for this in b24412c5e1656bcae69436d4a0a62e8170076437 but maybe it needs further work?

**Comment by irina060981** [comment]
I have fixed it here:
https://github.com/alpheios-project/components/pull/158

**Comment by irina060981** [comment]
Merged and closed
