### ISSUE TITLE
we currently write lots of information to the browser console. We should probably restrict this verbose mode.

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#16]
we currently write lots of information to the browser console. We should probably restrict this to verbose mode.

**Comment by irina060981** [comment]
Created branch in lexicons - https://github.com/alpheios-project/lexicon-client/tree/comp-%2316
Created branch in inflection-tables - https://github.com/alpheios-project/inflection-tables/tree/comp-%2316
Created branch in components - https://github.com/alpheios-project/components/tree/issue%2316

**Comment by balmas** [comment]
per discussion in today's check-in call, I would like @kirlat to review and suggest a design for the logging which also takes into account the work he did for the HTMLConsole log for the PWA. This is lower priority than work on inflection tables, however.

**Comment by irina060981** [comment]
@balmas and @kirlat, may be it is better to reassign this issue from me to @kirlat, if Kirill will work on refactoring and it seems to me that it is a part of refactoring task?
(the same as for https://github.com/alpheios-project/webextension/issues/86)

**Comment by kirlat** [comment]
We were developing a logger class a while ago. Can we (and would we) use it to control the amount of messages printed (i.e. print whatever we need with **debug** option on and limit output to things that are really important with **debug** off)? It might also be beneficial to set this debug option as a URL parameter, so we would be able to change it "on the fly".

**Comment by balmas** [comment]
I think we starting putting some things in place to support this.  We should revisit this for the MVP release.

**Comment by balmas** [comment]
qa-3.0.0.56/components 1.2.25

@monzug when testing this, what you should see now is very few, if any, messages in the developer's console when the UI Option Log Level is set to normal. If you set it to verbose, you should see several messages, and all of them preceded by "Alpheios <loglevel>:"

**Comment by monzug** [comment]
yes, I can definitely see the difference between normal and verbose log! tested in chrome and FF
