### ISSUE TITLE
two minor issues on Panel

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#162]
1) the wheel on Panel is Options according to tooltip, however we call it Settings from info: Click the Settings wheel to change the default language....
2) the Close Panel is barely visible on this site www.poesialatina.it/_ns/Greek/testi/Homerus/Odyssea01.htm

**Comment by irina060981** [comment]
Corrected message.json - changed Settings to Options

Corrected class names in the panel component - to avoid rewrite styles

https://github.com/alpheios-project/components/pull/165

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
Thanks. looks good.
