### ISSUE TITLE
load grammar upon grammer pane activation

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#163]
for the PWA we made a change to only load the grammar into the panel upon lookup of a word (i.e. rather than loading the current language's grammar upon load of the script). This causes the panel to be empty if it's accessed before lookup, which is confusing for the user. We should load it upon access of the grammar panel if it hasn't been loaded already by then.

(Reported by @monzug as activate Alpheios, look up a Latin word, reload page, click on grammar you will get the message at bottom of page saying the requested resource is not found)

A second issue that could be considered here would be to track panel contents in state as well as panel activated status.  That will be postponed for the refactoring of state handling.

**Comment by irina060981** [comment]
merged

**Comment by monzug** [comment]
Now I get the default language's Grammar open after reloading a page
