### ISSUE TITLE
add ability to include alternate Lemmas in morph display

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#166]
Per https://github.com/alpheios-project/data-models/issues/42 and https://github.com/alpheios-project/morph-client/issues/17 we sometimes have lexemes which have lemmas with alternate spellings. We need to show these under a single lexeme entry in the morph display, similar to the way we did in V1:

![44033906-c7be422a-9ed9-11e8-8da5-92cdee83cdf7](https://user-images.githubusercontent.com/644870/44223670-40ba2300-a156-11e8-98c2-cedbf504d18c.png)

**Comment by balmas** [comment]
Starting work on this .. still remaining to be done:
- [ ] sort lemmas on a lexeme by frequency
- [ ] display source (if there is one) with each lemma

**Comment by balmas** [comment]
@monzug You can test this with the build in https://github.com/alpheios-project/webextension/tree/issues-whitakers-engine

**Comment by monzug** [comment]
can we update the link for irregular verb to go to a different section of the grammar? right now, it takes to the declination. it should go to irregular verbs section 124

**Comment by monzug** [comment]
in Firefox, when clicking on the verb conjugation link, the correct section of the grammar is displayed.
also in Firefox, the verb irregular for absum is not available in the dropdown.

**Comment by balmas** [comment]
re 1: can you try clearing your browser cache in Chrome? I think likely the incorrect index file is cached, which is why you go to the wrong grammar entry there, and don't in Firefox

re 2: yes we don't have irregular tables for adsum yet -- we have an issue for that https://github.com/alpheios-project/inflection-tables/issues/70 . I'm still trying to decide if I want to add the conjugations for all the compounds of sum or to just show the base sum table.  I started adding the, but decided to check with you again about that first :-) see my comment in that item.

**Comment by monzug** [comment]
you were right. I forgot to clear cache in Chrome. close this one.
