### ISSUE TITLE
add support for alpheios-ignore data attribute

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#17]
Moved from https://github.com/alpheios-project/webextension/issues/15

We need to be able to identify areas of a page on which the alpheios tools should always be deactivated. In v1 of the tools we used an alpheios-ignore class for this. Should reimplement, probably via a data attribute.

3rd party site publishers can use this to control how Alpheios interacts with their site, and we can use it in our own components (e.g. the inflection tables and should be deactivated)

**Comment by balmas** [comment]
I think we really need this for the pwa prototype release @kirlat . Could you add something to the htmlselector class for this?

**Comment by kirlat** [comment]
Should be solved with 2ce213ce45a5fcdf568e7090c1d5ea5b40266fda. The format is: `data-alpheios-ignore="value"`. Currently, the only supported value is "all". It will ignore all pointer events that will initiate lexical query for the element that has its attribute and for all its children.

More values can be added later, as needed.

A filter is added to custom pointer events library. Right now it works in PWA only, as it is the first user of custom pointer events. It can be added to webextension too by switching it to use custom pointer events. Should be relatively easy to do.

**Comment by balmas** [comment]
Will close when 2ce213c is merged to master.  Entered https://github.com/alpheios-project/webextension/issues/99 to switch the Webextension to using the custom pointer events library.

**Comment by kirlat** [comment]
It is in master now. Added test to verify that it is working in alpheios-project/webextension@f10f7dad818a57730fae9f3082a53aa19ab99fb4.
