### ISSUE TITLE
add option to enable/disable use of lookupLanguage setting for Lookup component

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#170]
Per @monzug and discussion in #33 the way we deal with language for the lookup component can be confusing to the end user.

We would like to try adding a new boolean option (represented as a checkbox) on the lookup component which allows the user to specify whether they want to use the default language or a different language, and then only if that is checked do we show them the language settings select box and use the value from the lookupLanguage setting for the lookup. If it not checked, then we use the preferredLanguage setting.

@monzug I have a question for you about this though: we currently don't keep track of the last language used for the page separately from the last language used in the lookup box.  I think we might need to in order to implement this correctly. Take the following scenario:

1) User's preferredLanguage is Latin
2) User is on a page which has at least one other language(s) correctly identified with html markup (e.g. it may contain a mixture of Greek and Latin, or just Greek)
3) User clicks on a Greek word and gets the popup with Greek morphology definition, etc.
4) User enters a word in the Lookup box

What language should be used in this scenario? Latin or Greek?

**Comment by monzug** [comment]
I would say Latin as it's the Page language in Option. if they want to use the lookup with one of the supported language they should select it from drop-down, that will be available by checking Using language, so it's clear that that will be the language used.
right now, it works like this: page language is Latin, double-click and lookup work for Latin. if I double-click a Greek word, it returns the greek morphology for the word, and also lookup a greek word works fine because the Using language is Greek at this point. but if I lookup a latin word, it would not work and I would get the message: Language: Unknown. change to "Latin" shown in the drop-down. To lookup a latin word, I have to double-click a latin word again so both page languages are sync.
maybe this is limiting the ability of the user to switch from one language to the other in lookup, but I think it could prevent some confusion.

**Comment by balmas** [comment]
Ok, thanks. So then the description of what we need to do stands as follows:

We would like to try adding a new boolean option overrideLanguage (represented as a checkbox) on the lookup component which allows the user to specify whether they want to use the default language or a different language. Then only if the overrideLanguage option is checked do we show them the language settings select box and use the value from the lookupLanguage setting for the lookup. If it not checked, then we use the preferredLanguage setting.

@irina060981 Can you work on this? Let me know if it isn't clear what is needed. Thanks!

**Comment by irina060981** [comment]
I have made - 
https://github.com/alpheios-project/components/pull/179

Waiting for your feedback.

**Comment by irina060981** [comment]
merged - waiting verification

**Comment by monzug** [comment]
tested in Firefox.
- Now we have two settings to enable/disable a language: Using language
and the checkbox with Override language (some resizing needed here as the word language is slightly truncated on the bottom)
One of the two is redundant, unless I am missing some functionality here. Please advise.

- There is a minor issue with the checkbox not been checked in the other panels after the checkbox has been checked in lookup. I think this should be consistent among Info panel, Lookup, double-click and Definitions panel.
e.g.
checkbox is checked  in Info panel and select a language from drop-down different than the default language. Go to Definitions panel, the checkbox there is not checked, so it is not in lookup and in double-click.

- Related to above issue, if I remove or add a short lexicon, the selection should be sticky among all panels.
e.g. override language with greek and remove all lexicon from Info panel and enter  ἔννεπε, then from lookup click on using language, the drop-down is populated with the default short greek lexicon, enetr  ἔννεπε again and the definition is there.

**Comment by balmas** [comment]
Re point 1:  yes, we should remove the "Using Language" link. It is redundant.

Re point 2: agree that Override Language checkbox state should be the same in all places it appears

Re point 3: I'm not sure about this. I believe the way it behaves is by design - we wanted to keep the short definition lexicon selection state separate for lookups and the double-click behavior. E.g. one usage scenario we envisioned for this is that for languages with multiple lexicons, the user might want to use one lexicon for the default and then have the ability to override that to lookup in another lexicon for specific words if they needed further clarification on the definition. I think this might be a more frequent use case than changing languages actually. 

Re the 4th point: what I'm seeing is that the selection lasts until you change it, whether or not the popup is closed. This makes sense to me, but are you requesting a different behavior?

**Comment by monzug** [comment]
absolutely no request from my side. I am ok with all your answers. 
Irina, could you pls fix the resizing problem and then point 1 and point 2, pls? Thanks

**Comment by irina060981** [comment]
Hello, Monica :)
I have fixed -  https://github.com/alpheios-project/components/pull/193

You could test it from this branch - https://github.com/alpheios-project/webextension/tree/qa-lookup-issue%23170

**Comment by monzug** [comment]
tested on Chrome. all looks good, including resizing. Thanks.
one minor thing. Check the checkbox to use Greek, reload the page or deactivate/activate extension, the override language checkbox is checked but language goes to latin which is the default. if we want to go to default state, it would be enough to unchecked the checkbox. if we want to retain the override language we should have greek selected and not latin.

**Comment by irina060981** [comment]
Oh, great! I haven't noticed it :)
Fixed in the same PR.
I will merged as it is really very minor bug.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-5

**Comment by monzug** [comment]
Uhm, not quite right. we have two cases:
1) override language set to Greek (default language is Latin). reload page. override language is unchecked
2) override language set to Greek (default language is Latin), have the Greek grammar open. deactivate/activate webextension. the greek grammar is reopen. double-click any word, the pop-up has override language checked with Latin as selected language.
so, there is a minor conflict here between Greek grammar being reload and override language set to Latin. if we open the Greek grammar after deactivate/activate webextension, override language  should be Greek

**Comment by balmas** [comment]
@monzug can this wait until after the release? As noted in the comments in #109, managing the current language state across multiple languages and features needs some underlying refactoring to the code.  I'm worried about fiddling too more with it right now.
