### ISSUE TITLE
Hide "Collapse/Full table" button if table cannot be expanded or collapsed

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/components#178]
"Collapse/Full table" button is displayed even if an inflection table cannot change its width (i.e. has no column groups with no suffix matches). I think the button should be hidden in this case.

**Comment by kirlat** [comment]
This should be fixed with cf250a133e59057ccbc2bb77e1177d7ea08e1d19. A webextension `comp-i102` branch code can be used for testing.

**Comment by kirlat** [comment]
An webextension download link is https://github.com/alpheios-project/webextension/archive/comp-i102.zip

**Comment by monzug** [comment]
tested in chrome. works as per description. Thanks
e.g. possum, exis do not have the full/collapse button in inflection table

**Comment by balmas** [comment]
@kirlat I think you can merge this branch now?

**Comment by kirlat** [comment]
The problem that this fix is grouped with #109, which needs some changes. Will finish that one ASAP and merge
