### ISSUE TITLE
would like small/medium/large font/icon options

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#18]
moved from https://github.com/alpheios-project/webextension/issues/57

Mark says he would prefer a smaller font/icon sizes be the default. This is likely to be a user preference thing. Maybe we could offer the user 2 or 3 options (small/medium/large)? This applies to both the base text font size (e.g. in the popup and panel) and the icon size.

@kirlat commented:
This can be a little tricky as we need to carefully base all font and probably some other element's sizes like spacing and buttons on a base font size (use of "rem" as a base unit might help). And yet we have to avoid any interference with a font sizing set by a host page.

But I think it would be a nice feature to have, and I think this can be done.

I was also thinking if we can add support for basic skins. Not to change the shape of elements themselves, but allow to switch between different pre-set color combinations (dark/light, etc.). With SCSS variables this should be even easier to do than font options, yet it could probably be an important value for users.

**Comment by irina060981** [comment]
Started to work on it in branch 
https://github.com/alpheios-project/components/tree/reskin-color-font

I am creating a pull request right now as Bridget adviced to start with pull request to making easy to follow changes -
https://github.com/alpheios-project/components/pull/42

But there is no need - to merge it now.

**Comment by irina060981** [comment]
I have added color schemas - dark/light via scss files - _colorschema_dark.scss, _colorschema_light.scss
They use colors from _alpheios.scss
Aplied with the same way as font sizes classes.
The issue is done for now - waiting for your feedback.

**Comment by irina060981** [comment]
I have checked difference betwee files for merging and didn't find critical conflicts.

**Comment by irina060981** [comment]
Added lookup changes (lookup highlight color and place lookup component to the panel)

**Comment by irina060981** [comment]
Moved all changes to a new branch, that collected all my issues together:
lookup-reskin
#68
Stoped working on #42

**Comment by irina060981** [comment]
merged yo master (lookup-reskin)
