### ISSUE TITLE
Panel on activate: question

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#183]
After deactivating/activating the extension, both in Chrome and Firefox, the Info panel does not turn on. The Panel is generated only after the installation of any new build. I do remember in previous builds that the info panel was generated on activation unless unchecked the option. Is this an expecting behavior or side effect of recent changes?

**Comment by balmas** [comment]
not expected behavior.  Assigning to @irina060981 to investigate.

**Comment by irina060981** [comment]
Could you give me a link to the build - you are getting this behaviour? As while I was testing reactivating issue - panel was opened every time without bugs (if option is checked of course)

**Comment by monzug** [comment]
https://github.com/alpheios-project/webextension/tree/qa-2.0.3-3

**Comment by monzug** [comment]
on firefox, I used this site for testing: https://www.skuola.net/grammatica-latina/frasi-ablativo-assoluto.html
only after reloading the page the panel pops up.

**Comment by monzug** [comment]
on Chrome, I also used this site for testing: https://www.lexilogos.com/english/greek_ancient_dictionary.htm

**Comment by irina060981** [comment]
Thank you, Monica, I have checked more attentively your workflow and you are right.
In the scenarion - activate (panel status is loaded from options) / deactivate / reactivate (here the check panel status from options was missed) - panel wasn't open properly.
I have fixed it.

https://github.com/alpheios-project/webextension/pull/109

**Comment by irina060981** [comment]
merged and waiting for Monica's check

**Comment by monzug** [comment]
great. is there a build that I can test?

**Comment by balmas** [comment]
I will make you one soon...

**Comment by monzug** [comment]
Merci'

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-4

**Comment by monzug** [comment]
tested on Firefox only.
let's clarify few things here in terms of reloading vs enable/disable extension:
1) after deactivation/activation of extension, the Definition panel pops-up with lookup populated by the last word searched in lookup. should the search field be blank after reactivation or is it ok to retain this information? Note that after reloading, Definition panel pops up with search field empty.
same with inflection data: on reloading I get Inflection data not available, on activation of extension, it pops up the last viewed Inflection table.
2) should the info panel pop up after disable/enable extension or is it ok that we show the last viewed panel?
3) should default settings be reintroduced after reloading but not after disable/enabling of extension?

**Comment by balmas** [comment]
1. I think this is okay. We are retaining state in between activation/reactivation. But once the page is reloaded, the javascript is reinitialized and we lose that state. We can make refinements to this after the release, when we will do a refactoring of all state handling

2. I think it's okay that we show the last viewed panel upon reactivation.

3. I think the answer to this is the same as point 1
