### ISSUE TITLE
Auto adjustment of inlection panel width is broken

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/components#184]
A width of an inflection panel should be adjusted automatically to fit an inflection table fully. However, this seems to be broken now in Chrome, at least. It seems that an adjustment is made, but the panel is still a little bit narrower than it should be to display inflection table without scrolling. Please see an image below.

![image](https://user-images.githubusercontent.com/18631055/44903429-95949680-ad1d-11e8-8edd-e9fcb2c5bf33.png)

That used to be working, but some of the changes (not sure how recent those changes were) caused a regression.

This calculation is made in the `mounted()` callback of a panel component (`panel.vue`). This is where it probably needs to be fixed. It seems that calculation takes paddings/margin out of the equation when determining a final panel width.

**Comment by irina060981** [comment]
Fixed
https://github.com/alpheios-project/components/pull/186

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-4

**Comment by monzug** [comment]
tested in build 2.0.3.4 both in firefox and chrome. finally we have back this functionality.
