### ISSUE TITLE
add option to enable translations

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#194]
we would like to be able to enable beta testing of the translations feature via the lemma-client without turning this on for all users by default.

**Comment by monzug** [comment]
beatum doesn't have translation, beatus does (in all languages). In general it looks like the inflected words don't have the translation. Beside some funky translation in Italian (the excessive use of the article), I would say that it's a go. it's a great feature and I like it.
Please add  a space between multiple translation.

**Comment by balmas** [comment]
it should always use the lemma when looking up a translation. beatum as a lemma doesn't have a translation, but the lexical entries which identify beatus do, they just weren't showing up because of a bug in the deployment. 

Multiple translations are separated now, on different lines. Display probably still needs some refinement here.
