### ISSUE TITLE
better error messages needed when looking up a word in the wrong language

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#195]
Right now the error messages we produce when the user looks up a word in the wrong language are very confusing.

We say "Lexical data couldn't be populated for unknown reason" and the language selection notification says "Language: unknown"

For the former we should just say something like "Lexical query did not produce results." and I think the language selection notification should show the language we tried, not "unknown". 

Assigning this to myself to investigate solutions.

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-6

**Comment by monzug** [comment]
If I enter garbage text or not existing words, I get: Lexical query produced no results
"Morphological data not found. Definitions queries pending" and then it shows the language selection notification with the latest language used and the same language in drop-down.
