### ISSUE TITLE
add nicely styled tooltips

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#2]
on all icons and buttons

**Comment by balmas** [comment]
closing this now. We may want to refine the styles further at some point but if so we can open that as a separate issue.

**Comment by balmas** [comment]
@monzug can you verify and provide your opinion on whether there are tooltips everywhere we need them as well if they are now too numerous?

**Comment by monzug** [comment]
on Firefox & Chrome, when panel is on the left, the close panel tooltip is truncated, only anel is visible.

**Comment by balmas** [comment]
@irina060981 can you take a look at this when you get a second?

**Comment by irina060981** [comment]
Hello, Bridget (@balmas )!
I have corrected styles - https://github.com/alpheios-project/components/pull/160

**Comment by monzug** [comment]
yes, panel on the right and tooltip truncated on the left.
one more thing, the tooltip for Lookup is only activate when the pop-up has the lookup button under the enter text area. both crome and firefox
![screenshot_2018-08-15 translate ad lucem invia in tagalog with examples](https://user-images.githubusercontent.com/41396793/44148290-b9ead61c-a065-11e8-9663-b40207cb9c06.png)

**Comment by irina060981** [comment]
Merged and closed
