### ISSUE TITLE
lexical query never finalized if no definition requests

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#208]
reported by @monzug with symptom that language notification message never appears after a Ge'ez lookup fails. This is because the lexical query is never finalized if we didn't have full or short definition requests.

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-6

**Comment by balmas** [comment]
Hmm. I think something went wrong with that build. Can you get the latest copy of it from https://github.com/alpheios-project/webextension/tree/qa-2.0.3-6 and try again?

**Comment by monzug** [comment]
yes, this works fine now.
