### ISSUE TITLE
Greek Pronoun table and drop-down navigation

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#213]
From #40  (although really this belongs in the inflection-tables repository)

> from lookup enter αὐτόν and click to Inflect. The pronoun inflection table is generated but I was expecting the Intensive pronoun table.
> 
>     1. why did I get the Pronoun table and not the Intensive table?
> 
>     2. why the Pronoun table is not listed in the browsing section of the pronoun?
> 
>     3. there is not exact match here, why? also for "ὅστις " , I do not have an exact match.
> 
> 
> More about the drop-down on the right side of the Pronoun table. It has 4 type of pronoun, while the browsing pronoun table have 9 different tables.
> 4) what's the drop down for?
> 5) why is it populated by only 4 pronoun tables: pronoun declension, reflexive pronoun declension, personal pronoun declension, demonstrative pronoun declension?

There are two independent components here: 
- an inflection view at the top of the panel that shows tables for the result of a current lexical query.
- an inflection browser at the bottom that shows a list of "standard forms" of inflection tables.
Those two components are not interacting with each other currently and should be considered separately. This issue is related to the inflection browser. If there is a problem with incorrect inflection tables shown for a lexical query, then this should probably be a separate issue. @balmas, what do you think?

Drop down on the right side of the pronoun table shows four tables that the library thinks are relevant to the current lexical query. The drop down is used to switch between those four tables within a "current lexical query results" component. 

In inflection browser is a separate component. It shows nine tables because those are all pronoun tables it knows about. It has nothing to do with results of the lexical query. I was taking a list of tables from V1, except those that are not implemented currently.

I'll check this lexical query and figure out why does it show exactly those four tables and why it does not have proper matches sometimes.

_Originally posted by @kirlat in https://github.com/alpheios-project/components/issues/40#issuecomment-421973832_

**Comment by balmas** [comment]
Found a solution to the first part of this -- the version of the form we were using to match into the pronoun inflection table data had the separator in it still (e.g. we were looking for αὐτ -ον rather than αὐτον). Working on a fix to that .

**Comment by balmas** [comment]
NB this fix requires the changes for #40 as well.

**Comment by balmas** [comment]
Fix is in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-7

**Comment by monzug** [comment]
tested in Chrome, build 2.0.3-9
lookup for αὐτόν  shows only the Intensive pronoun table with exact match
lookup for ὅστις has exact match in the General relative pronoun declension
