### ISSUE TITLE
abbreviation for plural

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#234]
@abrasax suggests we use "pl." instead of "p." for plural. @monzug is this consistent with Allen and Greenough?

**Comment by monzug** [comment]
Mostly PLURAL, sometimes PLUR. will look in the online grammar

**Comment by monzug** [comment]
Confirmed: Allen & Greenough's grammar uses sing. and plur.

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/memleaks2/dist
