### ISSUE TITLE
On Chrome on the Mac the close panel/popup X is barely visible

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#240]
Reported by @abrasax

**Comment by balmas** [comment]
@kirlat would you be able to take a quick look at this to see if you can make it a little more prominent?

**Comment by balmas** [comment]
Note that we updated the width of the move to right/left arrows too to match

please test in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-18/dist

**Comment by monzug** [comment]
tested on Mac, build QA-18 - looks good
see screenshot
![screen shot 2018-10-03 at 17 02 39](https://user-images.githubusercontent.com/41396793/46419635-4b2b7e80-c6fc-11e8-9158-52814361f670.png)
