### ISSUE TITLE
Script message generated in Firefox

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#245]
lookup for 'credere' with French translation enable.  lookup takes longer than usual. few times I got the script message. Lookup for credere with translation disabled, I did not get the script message

**Comment by irina060981** [comment]
I was not able to reproduce any script messages with enebled translations for French language (I tried new 20-30 clicks).
So I couldn't read the script message.
And I could only suppose - may be there were some temporary problems with alpheios translation service.

**Comment by monzug** [comment]
not reproducible

**Comment by monzug** [comment]
could not repro in Alpheios Reading Tools 3.0.0.62
Alpheios Components 1.2.35
