### ISSUE TITLE
Inflections button and Diagram button are not reloaded for the next target word

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/components#248]
Buttons Inflections and Diagram - are not hidden for the word if the current word doesn't have inflections and treebank, but one of the previous had.
And if you click inflections - the previous tables will be shown, if clicks diagram - the blank tab will be shown.

For example, 
![image](https://user-images.githubusercontent.com/12377640/46947436-24872380-d0be-11e8-89db-356108e3a0b5.png)

**Comment by irina060981** [comment]
@balmas, I have assigned it to you only because you have recieved an alert about it.
I could solve it later, when I will finish with games notices and those issues that I have taken before.

**Comment by balmas** [comment]
thanks @irina060981 . Not sure of the priority of this just yet but we should fix it at some point.

**Comment by balmas** [comment]
@monzug whenever you have time can you check to see if this is still occurring? Thanks!

**Comment by monzug** [comment]
Could not reproduce in the online example text with diagrams
