### ISSUE TITLE
Colour issues on buttons on Loeb site

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#250]
We do have a color issue with all buttons on the Loeb Classics site, http://www.loebclassics.com
see screenshot
![loebb-classics](https://user-images.githubusercontent.com/41396793/47015748-cc7f0a00-d11b-11e8-8f97-7b3a655069bc.JPG)

**Comment by monzug** [comment]
@balmas   shall we add this change for next release?

**Comment by balmas** [comment]
yes, we should do this along with the other style fixes @irina060981 is making for Safari.

**Comment by irina060981** [comment]
Solved upon https://github.com/alpheios-project/webextension/issues/135
Fixed styles
**Firefox**
![image](https://user-images.githubusercontent.com/12377640/48661232-891d1000-eaba-11e8-8b3a-9f3e3a67e807.png)

**Comment by irina060981** [comment]
Merged and Closed

**Comment by balmas** [comment]
ready for testing in build 2.1.0.9

**Comment by monzug** [comment]
tested in build 2.1.0.10, Safari only
