### ISSUE TITLE
Respect state of panel when browsing

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#254]
Quoting Bridget  'it should respect the state of the panel when browsing. I.e. if 
the panel is closed when you advance to a new page in the browser, it 
should stay closed.  If it's not then maybe we broke it at some point.'

This came up when I requested a way to disable the panel when browsing a text (e.g. loeb-classics):
closed pop-up and advance to next page, panel is generated again.  
in poesialatina web site, the url changes when browsing through the pages, so it does reload the page again. On reload, we show the panel. is this the bug? Bridget said yes.

This is my fault as I thought we wanted the panel on reload.

**Comment by monzug** [comment]
I thin this issue: Panel on activate: question #183  is related

**Comment by balmas** [comment]
Ah this isn't as broken as I thought. I think it always worked this way on reload, although I guess it probably shouldn't.

If you navigate to a new page in your browser, the panel status is respected. It's the page reload which is losing state.  This should be addressed with refactoring.

**Comment by balmas** [comment]
I believe we are actually addressing this with the Safari release. To assign for verification with the next build.

**Comment by balmas** [comment]
I believe this may be working correctly in FF and Chrome in 2.1.0.x build 14 (available from https://github.com/alpheios-project/webextension/tree/issue-176/dist) and is still not correct in the same build in Safari. Passing to @monzug to confirm in FF/Chrome.

**Comment by monzug** [comment]
Chrome and FF, build 2.1.0.14  vs  build 2.0.2.20
1) go Loebclassics and activate tools. the info panel is generated.
2) go to the author page. info panel is generated.
3) select any author, e.g. ACHILLES TATIUS, Leucippe and Clitophon
4) in latest build, no panel is generated when browsing through pages - in 2.0.2.20 the info panel is generated and keeps popping up when browsing through pages
4) open the inflection table (or the grammar panel) and go to next page, no panel is generated. in 2.0.2.20 the inflection panel (or grammar panel) is open.
5) in Safari the info panel is generated when browsing through pages, no matter which panel was previously open in the page (inflection panel or definition panel or grammar panel).

**Comment by balmas** [comment]
this should be fixed in build 2.1.0.16

**Comment by monzug** [comment]
this is fixed accordingly to comment on issue #174

**Comment by monzug** [comment]
tested in Chrome, FF and Safari, build 2.1.0.17 in http://www.thelatinlibrary.com/lucan/lucan1.shtml
open the grammar panel and then navigate to page http://www.thelatinlibrary.com/lucan/lucan2.shtml by changing the URL. the info panel is also generated in the new page. go back with back browser to the previous page and the info panel is generated again. if the define panel is open, thedefine panel pops up in new page and going back to previous page with back button.
