### ISSUE TITLE
update lexicon class names

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#255]
in https://github.com/alpheios-project/lexsvc/pull/4 we have added an alpheios namespace to the classes defined in the html of the lexicon service output. We need to update the styles here in order to deploy that.

**Comment by irina060981** [comment]
I have updated a couple of additional css classes in lexsvc (I have missed it) - https://github.com/alpheios-project/lexsvc/pull/5
And updated class name in styles - https://github.com/alpheios-project/components/pull/259

**Comment by irina060981** [comment]
Additional PRs are merged for components and lexsvc.
