### ISSUE TITLE
include dialect in morph output

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#262]
at some point we seem to have lost the dialect from the morph output. this can be useful to differentiate inflections.

E.g. see ἐλῴη

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist

**Comment by monzug** [comment]
dialect are in

![dialect-yes](https://user-images.githubusercontent.com/41396793/47513535-719c8f80-d84c-11e8-80e3-31f5faa07616.JPG)

old build
![no dialect](https://user-images.githubusercontent.com/41396793/47513559-795c3400-d84c-11e8-8430-5d9562cfdd61.JPG)
