### ISSUE TITLE
Lookup component does not always display a lookup word

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/components#267]
It seems that in some situations when a lookup is started via a lookup component, a lookup word is not displayed in a component after the query is completed.

One way to reproduce this is:
1. Activate an extensions for the first time.
2. A panel will appear if panel-on-open option is on in settings.
3. Type a word in an incorrect language in a lookup component within a panel and start the search.
4. A popup will open with the message saying that the word is not found. A search word will not be displayed in the popup’s lookup component.
5. Open a panel (Right click, then in a menu select **Alpheios Reading Tools** -> **Open Panel**). A panel with an info tab will open and a lookup component will appear. The search word will not be shown in a lookup component too.

I think it will be beneficial to have this word be displayed so that user can search again by just changing language settings.

**Comment by balmas** [comment]
I think this is obsolete now. @monzug can you verify?

**Comment by monzug** [comment]
the steps to repro are slightly different but Kirlat's suggestion is still valid.

**Comment by balmas** [comment]
ok, thanks.

**Comment by irina060981** [comment]
I have a question here - because UI is slighty changed after @kirlat described the issue.

Now we have 2 lookup components - in toolbar and in panel.
So we should realize the following workflow:

if a user try to lookup via any lookup panel (toolbar or panel) and the morph adapter didn't return a result, we should save it to memory (I think to Vuex) and publish to both lookups ?

**Comment by balmas** [comment]
hmm. yes, I think so.  @kirlat do you agree?

**Comment by kirlat** [comment]
> if a user try to lookup via any lookup panel (toolbar or panel) and the morph adapter didn't return a result, we should save it to memory (I think to Vuex) and publish to both lookups ?

I am for syncing the data between the two lookups. But I'm afraid this can be more complicated than just syncing the word now. The problem is that if we start keeping them in sync, we have to sync language options (i.e. the language selected) too. But by requirements language options work differently for the two lookups: the one in a panel has controls to allow select language and lexicons, or use the one from the options page (with a Default setting). The one in the toolbar, however, uses settings from the options page only. It has no language selection controls. So I'm not really sure what we can do about language synchronization. @balmas, @irina060981, what do you think?

**Comment by balmas** [comment]
need to think about this a little bit.

**Comment by monzug** [comment]
how about if lookup is initiated in panel, we'll offer the word in panel. if lookup is initiated in toolbar, we'll offer the word in toolbar

**Comment by balmas** [comment]
Yes I think that is simplest for now. Let's not try to sync them.

**Comment by irina060981** [comment]
@balmas and @kirlat ,
For now the message `Lexical query produced no result` disappears very quickly
![image](https://user-images.githubusercontent.com/12377640/60000101-dd1e5180-96a6-11e9-8e39-f143cc3c26ff.png)

may be we should save it in the popup/panel?

**Comment by irina060981** [comment]
Merged and closed

**Comment by kirlat** [comment]
> For now the message `Lexical query produced no result` disappears very quickly, may be we should save it in the popup/panel?

I agree with you. I was thinking about it myself. Right now we show a word with no data about it whatsoever. I think it would be beneficial to explain why there is no data there.

**Comment by balmas** [comment]
we have a couple of issues for that #501 #502 that I pushed out of the release. If we have time we can address them.

**Comment by balmas** [comment]
webextension qa-3.0.0.45/Safari3.0.0.45)/embed-lib 1.0.0.27

**Comment by monzug** [comment]
I can see the word in the lookup in toolbar when I enter the word from there. same in Help panel.
However I can't see the word in  lookup from Definition panel, even if I entered the word in there. I think we are missing to update the lookup from Definition Panel.

**Comment by balmas** [comment]
> I can see the word in the lookup in toolbar when I enter the word from there. same in Help panel.
> However I can't see the word in lookup from Definition panel, even if I entered the word in there. I think we are missing to update the lookup from Definition Panel.

Ok, so we need a new issue for this?
