### ISSUE TITLE
vue-multiselect 2.1.3 causes a crash on Firefox

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#272]
Still haven't quite isolated the reason for this, but the automatic update of the vue-multiselect dependency from v2.1.0 to v2.1.3 causes the webextension to crash when loading options in Firefox.   I'm going to fix the dependency at 2.1.0 for the beta patch release but we should investigate the cause of this.

**Comment by balmas** [comment]
I believe this is fixed now in https://github.com/alpheios-project/webextension/tree/v2.0.3.5/dist

**Comment by monzug** [comment]
tested in firefox and  both the double-clicking and verb browser issues are gone.
