### ISSUE TITLE
separate inflection browser from lookup-activated inflection tables

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#275]
Feedback from Mark and @abrasax : we should keep the Inflection Table browser always distinct from the tables produced by the lookup results. Their feeling was that it is not intuitive to have them both in the same view. They would like the Inflection Table tab on the panel to always bring up the browser and only the browser, and for the tables that are produced by the lookup to appear in a separate panel. I am not sure what icon we would want to use for the lookup-specific panel. This needs some experimenting.

**Comment by balmas** [comment]
@monzug I have made this change, and you can test it first in the Safari build 2.1.0.10 (I will give you a new build of the webextension for Chrome and FF soon). The inflection tables now appear in their own tab separate from the inflection browser.

**Comment by monzug** [comment]
I really like (also the icon). there is one thing about the look of fonts in different sites. I did update issue webextension/issues/140
also, in the verb browser, the inflection table stays open even after lookup for a different word. e.g. open inflection table for dicere then go to verb browser and open any table, let's say the adj table. then close panel, lookup for a different word, go to inflection table then verb browser, the previous table is still open.

**Comment by balmas** [comment]
ok, state of the browser tables is fixed in Safari build 2.1.0.11. There is a parallel build for chrome and firefox available for testing at https://github.com/alpheios-project/webextension/tree/qa-2.1.0.11/dist

**Comment by monzug** [comment]
one question on this: should the verb browser show only latin and greek inflection browser titles? right now, when I click on the browser icon after searching any latin word, the latin browser is expanded to show all the list.

**Comment by balmas** [comment]
I know, I was a little sloppy about the status of the browsers themselves. I think too after you do a query right now, the browser that was last opened remained open. I will clean this up a little bit further.

**Comment by monzug** [comment]
tested in chrome and firefox build 2.1.0.11

**Comment by monzug** [comment]
tested in Safari, FF and Chrome in 2.1.0.13. works as described above.

e.g.  language in options is set to Greek, related verb browser opens with Greek verbs expanded. change language to Latin in Look-up, verb browser opens with Latin verbs expanded.

Question: if I close the expanded latin verb browser, any subsequent view of the verb browser will have the latin list not expanded. Is this ok?

**Comment by balmas** [comment]
yes I think that is fine.  Can we mark this verified?

**Comment by monzug** [comment]
YES!
