### ISSUE TITLE
state problems with dropped connections?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#280]
@abrasax was noticing some odd behavior when testing the tools in a place where the online connection was spotty. For example, selection of indiga at http://www.thelatinlibrary.com/lucretius/lucretius1.shtml bringing up Aenedum instead of indiga. He posits that maybe this was caused by the connection dropping and I think it's conceivable, if Aenedum was looked up prior to the connection dropping. I'm not sure exactly what we want to do about this, but @monzug could you do a little bit of testing at some point to see if you can reproduce? (e.g. do some lookups, then go offline and see what happens) Thanks!

**Comment by monzug** [comment]
I will. I have worked with bad connection few times when travelling but I
didn't experience anything unusual

**Comment by monzug** [comment]
could not replicate this one. double click on Aeneadum produces no results, indigo is an adj of 1st decl. offline, both words produce a failed lookup. I'll keep it assigned tp myself to see if I can reproduce it with a bad connection

**Comment by monzug** [comment]
Just installed new build and noticed the following:
double click on any latin word and open the related inflection table. deactivate the tools and activate again, the previous inflection table pops up. double click on any other latin word rathar than the previously selected one, the morphology pops up with the previous word, and soon after it will be replaced by the new one. this might be what Harry has experienced, with slow connection it might have been obvious. I was able to repro this only once just after the installation.

**Comment by monzug** [comment]
see issue /alpheios-project/webextension/issues/164

**Comment by monzug** [comment]
not reproducible in Alpheios Reading Tools 3.0.0.62
Alpheios Components 1.2.35
