### ISSUE TITLE
user word-in-context lists

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#304]
Background perspective on this feature, with additional currently out of scope user stories, is available at:

https://github.com/alpheios-project/documentation/blob/master/design/vocabulary.md
https://github.com/alpheios-project/documentation/blob/master/design/vocab_management.md

N.B. **The user word-in-context lists and the usage examples features both  _extend_  a common core word-in-context use case**
![sowkiimgastduubi22rebl88pozaqvncqtnepoj9hizhlb2fqtllq40nvj9mjipbpyjcjinh22rej4zlsar8p2t8ismfwsixdiy5p140](https://user-images.githubusercontent.com/644870/49876840-305b4180-fdf2-11e8-942b-5eb4e890faaf.png)

A first stab at scoping *this* enhancement:

As a user I want to store all of the words I look up to my word-in-context list.
As a user I want to be able to flag as important a specific instance of an item on my word-in-context list.
As a user I want to be able to flag as important all instances of specific word form on my word-in-context list
As a user I want to be able to flag as important all instances of all forms of a specific lemma on my word-in-context list.
As a user I want to be able to flag as important all instances of a specific form and lemma combination on my word-in-context list.
As a user I want to be able to remove an important flag from a specific instance of any item on my word-in-context list.
As a user I want to be able to remove important flags from all instances of specific word form on my word-in-context list.
As a user I want to be able to remove important flags from all instances of all forms of a specific lemma on my word-in-context list.
As a user I want to be able to remove an important flag from all instances of a specific form and lemma combination on my word-in-context list.
As a user I want to be able to remove all important flags from all items on my word-in-context list.
As a user I want to be able to remove all items from my word-in-context list.
As a user I want to be able to view a subset of my word-in-context list that contains just the words I have looked up during the current application session.
As a user I want to be able to view a subset of my word-in-context list that contains just the instances of a specific word form.
As a user I want to be able to view a subset of my word-in-context list that contains just the instances of a specific lemma.
As a user I want to be able to view a subset of my word-in-context list that contains just the instances of a specific form+lemma combination.
As a user I want to be able to view a subset of my word-in-context list that contains just the instances of a specific form in which another form appears before that word in the context.
As a user I want to be able to view a subset of my word-in-context list that contains just the instances of a specific form in which another form appears after that word in the context.
As a user I want to be able to filter any view of my word-in-context list to the items I have flagged as important.
As a user I want to be able to download the data from any view I can produce of my word-in-context list.
As a user I want to be able to configure the number of words of surrounding context that get saved with an item to my word-in-context list.
As a user I want to be able to edit the words saved as the surrounding context for an item on my word-in-context list.
As an application I want to be able to limit the surrounding context saved with an item to a word-in-context list to the full sentence in which the word appears.
As an application I want to be able to respect user preferences for the number of words of surrounding context saved with an item to a word-in-context list.
As an application I want to be able to apply reasonable defaults to the of words of surrounding context stored with an item on word-in-context list if the sentence cannot be determined or exceeds a maximum length.

**Comment by irina060981** [comment]
Repo is created - https://github.com/alpheios-project/wordlist

**Comment by irina060981** [comment]
I have made refactoring for IndexedDB methods:

1) made them promise-based

2) created a separate file for storing indexedDB structure - `indexed-db-structure`

3) changed the TextQuoteSelectore Table structure (and upgraded the database version for that - it will add additional index, I suggest you to clear database - you don't need to delete it)

![image](https://user-images.githubusercontent.com/12377640/51115879-2b583a80-1855-11e9-83c0-73071e5d3b52.png)

4) added to embed-lib special demo page to test  - embed-lib#feat-304-word-list
http://localhost:8888/demo/caesar-gall1

**Comment by irina060981** [comment]
Fixes - add remoteAdapter to workflow:

https://github.com/alpheios-project/components/pull/349
https://github.com/alpheios-project/data-models/pull/74
https://github.com/alpheios-project/wordlist/pull/9

**Comment by balmas** [comment]
@monzug the basics of the wordlist feature  can now be tested in the webextension and in the texts-test environment.   It doesn't include all of the user stories listed above (at least download and user configuration options are missing) but it would be good to start testing it sooner rather than later.

The webextension build to use for testing is in https://github.com/alpheios-project/webextension/tree/qa-3.0.0.23/dist

Alpheios Reader test environment at http://texts-test.alpheios.net/ as usual

The wordlists work with or without login. Without login, the wordlist data gets erased when you close your browser session. With login, it works as described at #317 

Focus on testing in Chrome for now.

**Comment by monzug** [comment]
tested in Chrome in http://texts-test.alpheios.net/ 
1) tested without login and noticed that the wordlist data gets erased by clicking in the text link in Show context or by going to the next page within same text.  
as noted, it should erase data after closing the browser session. what do you intend by browser session? 
2) the words in wordlist look like active links but if you click on them, nothing happens. are they supposed to be active link?

**Comment by balmas** [comment]
>tested without login and noticed that the wordlist data gets erased by clicking in the text link in Show context or by going to the next page within same text.
as noted, it should erase data after closing the browser session. what do you intend by browser session?

ah, you're right ,if a new page is loaded, or the same page reloaded, the wordlist will get cleared. We could consider adding this to the extension state so that it is retained. We really want them to login though so I am not sure it makes sense to optimize the unlogged-in experience.

**Comment by balmas** [comment]
>the words in wordlist look like active links but if you click on them, nothing happens. are they supposed to be active link?
Ah, they ARE active links, but if you are testing without login, then yes it looks like nothing happens because it just reloads the page you are on.  I think we should have a different styling if the context is the same as the page we are on and indicate that it is the current page (and not make it linked). Do you agree @monzug ? If so then I will turn this into a new issue.

**Comment by monzug** [comment]
yes, agree. I am still testing without logging in

**Comment by monzug** [comment]
Not sure if there is anything that can be done about this:  when I scroll the text and click on any word, the words are saved in the User word list but the link in Show Context takes you to the beginning of the section
e.g. urn:cts:latinLit:phi0893.phi003.perseus-lat2/passage/5.31-5.60    and not to    section 11.1-11.28 where the word belongs. Note that the url does not change when scrolling so it's always http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0893.phi003.perseus-lat2/passage/5.31-5.60.

**Comment by balmas** [comment]
good catch. this is something I need to fix in the scroll handler for the texts application. Have entered it as an issue there.

**Comment by irina060981** [comment]
Current priorities from the SLack discussion with Bridget:
>balmas [22:21]
I think the features for the wordlist
I think in this order of priority:
sorting/filtering
download data

**Comment by balmas** [comment]
I have moved a number of the user stories to their own issues. This item now covers just the following scope.

As a user I want to store all of the words I look up to my word-in-context list.
As a user I want to be able to flag as important a specific instance of an item on my word-in-context list.
As a user I want to be able to flag as important all instances of specific word form on my word-in-context list
As a user I want to be able to flag as important all instances of all forms of a specific lemma on my word-in-context list.
As a user I want to be able to flag as important all instances of a specific form and lemma combination on my word-in-context list.
As a user I want to be able to remove an important flag from a specific instance of any item on my word-in-context list.
As a user I want to be able to remove important flags from all instances of specific word form on my word-in-context list.
As a user I want to be able to remove important flags from all instances of all forms of a specific lemma on my word-in-context list.
As a user I want to be able to remove an important flag from all instances of a specific form and lemma combination on my word-in-context list.
As a user I want to be able to remove all important flags from all items on my word-in-context list.
As a user I want to be able to remove all items from my word-in-context list.

**Comment by balmas** [comment]
these are all implemented so moving this to closed and waiting_verification.

**Comment by monzug** [comment]
The following has not been implemented:
As a user I want to be able to remove an important flag from all instances of a specific form and lemma combination on my word-in-context list.
Not sure if we will implement in future releases. @balmas?

**Comment by monzug** [comment]
Irina, this is an excerpt from #419:

"As a user I want to be able to view a subset of my word-in-context list that contains just the instances of a specific form+lemma combination.
I am not sure this one actually makes sense because we group forms by lemma. So let's drop this one."

as we dropped the lemma+form combination, we did also not implement these requirements:
As a user I want to be able to flag as important all instances of a specific form and lemma combination on my word-in-context list.
As a user I want to be able to remove an important flag from all instances of a specific form and lemma combination on my word-in-context list.
Does it  make sense? I really hope it does. Otherwise I have to revisit this issue.

**Comment by irina060981** [comment]
@monzug , I remembered. 
as we have drop the implementation of the filtering by exact form + lemma, I have excluded setting/removing  important flag from such combinations.
So I think you described right.

And I believe that I shouldn't do anything else here.
Am I right?

**Comment by monzug** [comment]
I believe so. not sure if there is a plan to add the lemma+form combination
in the future. if not, this is all done.@balmas?

**Comment by balmas** [comment]
I don't think there is a plan for that right now. We will wait for user feedback on this before doing more on that point. Thanks both.
