### ISSUE TITLE
usage examples feature

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#307]
Add a component which allows the user to query for usage examples for the selected word. 

This could be added to a new Usage Examples tab in the panel. 

A button in the popup should open the Usage Examples tab and initiate the search, making a request to the concordance service adapter (see alpheios-project/client-adapters#4). (The service request could instead be initiated by the lexical query but I would prefer to start with on-demand request)

The interface should present the user with the following options

* filter by author
* filter by author and work
* sort by author
* sort by work
* sort by prefix (preceding word)
* sort by suffix (following word)
* specify a maximum number of results to return

The following is an example of how the results get displayed on the PHI site. We could use this as a model to start

![phi latin texts concordance](https://user-images.githubusercontent.com/644870/50361997-c8b09f00-0533-11e9-8143-690cc4b7e676.png)

We may link the source citations to the the text on the PHI page as they are done here although we may choose not to.

An important requirement is that Alpheios lookup functionality MUST be active on the display of usage examples. I.e.,users should be able to select the words in the examples and initiate lookups on them.  This requires fixing #144.

**Comment by balmas** [comment]
The options for filtering should be acquired by calling the Concordance adapter API.  A typeahead library should be used to allow the user to enter the first few letters of each filter field value and present suggestions to the user. Only known values will be allowed.

**Comment by balmas** [comment]
The interface should also include credits for the usage example data, retrieved from the ResourceProvider in the adapter response.

**Comment by balmas** [comment]
We might want to have lookups from selections of usage examples words appear in a separate popup.  See #21

**Comment by irina060981** [comment]
The first version is here:
https://github.com/alpheios-project/data-models/pull/68
https://github.com/alpheios-project/client-adapters/pull/8
https://github.com/alpheios-project/components/pull/320
https://github.com/alpheios-project/embed-lib/pull/32

**Comment by irina060981** [comment]
The first prototype is realized the way described here: https://github.com/alpheios-project/client-adapters/issues/4

Filtering, Sorting and setting max property on panel/popup is postponed to Kirill's finish and merge comp-vue-refactoring branch.

**Comment by balmas** [comment]
We'd like to refine the requirement for user-configuration of max number of results returned to add another level, max number of results per author. The PHI folks have accommodated this request by adding a new authmax parameter,  The way the service currently works, the max parameter applies to all results, and then the authmax parameter applies within that. And if no max parameter is supplied, it limits all results to 50, and only the authmax would then apply within that, so if the first 16 or so authors each had 3 hits, we would not get any results from the others.  While we can ask for changes in behavior on the server, since it's not our service I don't want to request too much before we really know what we need here.   So I'd like to experiment with options on the client side a bit first. 

We would like to start by returning 3 results *per author*.  The PHI corpus has a total of 362 authors, so that would mean the default would return, at most, 1086 hits.  

But in order to get that 1086 results,  we need to set the actual max much higher, because any one author might themselves have 1086 results for a given word. So to ensure that we get the 3 hits per author, we have to set the overall max very high for now.

It is possible that we will want to allow the user to specify a specific list of authors to limit the initial results to, or to change the number of results per author, but I think we need to get further along with the feature and get some beta user feedback before implement these refinements. 

So to start, let's experiment with the following:

- Default for every query: return max 3 results *per author*.  
- from within the usage examples tab:
- allow the user to filter and sort the initial query results on author and work
- offer an option to retrieve more results for a specific author or author/work combination

and then we can pause and evaluate this functionality before expanding it.

**Comment by irina060981** [comment]
> An important requirement is that Alpheios lookup functionality MUST be active on the display of usage examples. I.e.,users should be able to select the words in the examples and initiate lookups on them. 

I suggest this solution
https://github.com/alpheios-project/components/pull/354

**Comment by balmas** [comment]
@monzug although there is also still more work to do on the usage examples, I would like to get your feedback on what has been implemented so far.   

The webextension build to use for testing is in https://github.com/alpheios-project/webextension/tree/qa-3.0.0.23/dist

Alpheios Reader test environment at http://texts-test.alpheios.net/ as usual

While this feature should work in both Firefox and Chrome (I still need to get a Safari build of the webextension together) I recommend limiting testing for now to Chrome until we figure out the performance problem on Firefox. 

You should probably review the conversation at https://github.com/alpheios-project/components/pull/356 which has more information on what has been implemented and why.

**Comment by monzug** [comment]
1) I haven't fully tested this feature yet but I noticed that if I go to world usage examples and then I do enter a word in lookup, there is an extra button on the pop-up with examples. if I click on it, I get the previous word usage examples. Note that I do not usually get the button using lookup., except after a world usage examples. May be we should disabled it for lookup?
![dicere-examples](https://user-images.githubusercontent.com/41396793/55330251-8fef6280-545e-11e9-954f-230991335c78.JPG)

2) the Examples button is also added to the morphological panel after I get results for that specific word.
Isn't it redundant?

3) how do I clear the world usage examples? right now, it's only by clicking on World usage examples on a new word. is this ok?

tested in Chrome in http://texts-test.alpheios.net

**Comment by balmas** [comment]
We are currently experimenting with 2 different settings for this:
1) OnDemand -- where the examples are only retrieved when the user explicitly asks for them on the Usage Examples Tab
2) OnLexicalQuery - where the examples are retrieved with every (Latin) query.

This is currently controlled by a setting in the Options tab. 

In either case, the user has the ability to sort and refine further.

I think the default setting is OnDemand, and it sounds like you have identified a couple of problems with that implementation.  

I think the Examples button should always appear on the popup when usage examples are enabled, but maybe in the case of OnDemand it should clear the tab of the prior results?   

Or maybe we don't want to offer these two variations and only ever do the request upon demand? Or the opposite? Part of the reason for waffling here is that we don't really know yet what sort of load the service can handle, and querying on every single lookup might be problematic if/when we have a lot of users.

(@irina060981  - I did notice that in the latest build, we now NEVER get the usage examples icon on the navbar or panel...)

**Comment by monzug** [comment]
yes, I noticed the two options, the default is On demand. Lexical query is
misspelled in the build I tested: it's LexiqalQuery

**Comment by balmas** [comment]
So, @monzug do you agree with my suggestion for the OnDemand option? I.e. to always show the Examples button in the popup, but make sure the prior search is cleared?

**Comment by monzug** [comment]
let me spend some time testing the feature. will get back to you tomorrow.

**Comment by monzug** [comment]
prior search has to be cleared, when I do a lookup and click on examples as right now it shows the previous search.  I think that having only on demand option would be better (simpler design and possible less load). if we agree on this, we should remove the Get word usage examples: in Options. Also, the examples button should always be present when world usage example is enable. is this ok?

**Comment by monzug** [comment]
why do we allow 0 in these Options:
Word Usage Examples - max results per author   and     Word Usage Examples - max results for single author request? if I do apply them I get no results so not sure why we set this limit to 0.

**Comment by balmas** [comment]
> prior search has to be cleared, when I do a lookup and click on examples as right now it shows the previous search. I think that having only on demand option would be better (simpler design and possible less load). if we agree on this, we should remove the Get word usage examples: in Options. Also, the examples button should always be present when world usage example is enable. is this ok?

I think simplification might be a good idea. @irina060981 we could perhaps leave both options in place in the code but just not offer the user the option to change this right now. This would allow us to revert to the  automatic lookups if user feedback indicates a need for it. What do you think?

**Comment by irina060981** [comment]
I have fixed that previous results for wordUsageExamples were not cleared.
Now it is always cleared.

>Also, the examples button should always be present when world usage example is enable.
Examples buttons inside panel and toolbar are always visible when examples feature is enabled
Examples button inside popup  is visible only when wordUsageExamples are retrieved.

Should I synchronise it?

Now both variants - onDemand and onLexicalQuery are working properly, should i hide the type from the options now?

**Comment by balmas** [comment]
@irina060981 yes, please hide the type from options. Not sure I understand the question about syncrhonizing.

**Comment by irina060981** [comment]
I meant the following:

Examples buttons inside **panel and toolbar** are always visible when examples feature is **enabled**.
Examples button inside **popup** is visible only when wordUsageExamples are **retrieved**.

So we have different conditions for panel and popup.

Monica asks,
>Also, the examples button should always be present when world usage example is enable. is this ok?

So should I made conditions the same?

**Comment by balmas** [comment]
> I meant the following:
> 
> Examples buttons inside **panel and toolbar** are always visible when examples feature is **enabled**.
> Examples button inside **popup** is visible only when wordUsageExamples are **retrieved**.
> 
> So we have different conditions for panel and popup.
> 
> Monica asks,
> 
> > Also, the examples button should always be present when world usage example is enable. is this ok?
> 
> So should I made conditions the same?

Yes, We always want to show the Examples button in the popup now if the feature is enabled.  I entered this as #467

**Comment by balmas** [comment]
closing this item. Bugs and enhancements will be reported separately.

**Comment by monzug** [comment]
1) How do I activate the filter "Filter these results by Author and/or Work"? both in mobile and desktop
2) on desktop, lookup works in the examples as per requirement. However when double click on a word, the lookup is generated on the word from the text behind the World usage examples panel.
could not activate this functionality on mobile

**Comment by monzug** [comment]
can't test on iPhone 6s as the options view is all screwed up 
see screenshot
![IMG_0476](https://user-images.githubusercontent.com/41396793/57465867-7c010280-724d-11e9-92eb-d50ace21024c.PNG)

**Comment by balmas** [comment]
> on desktop, lookup works in the examples as per requirement. However when double click on a word, the lookup is generated on the word from the text behind the World usage examples panel.
> could not activate this functionality on mobile (samsung 5s)

I have made issue #526 for this bug

**Comment by balmas** [comment]
@monzug can we close this one now?

**Comment by monzug** [comment]
will open separate issues if needed. verified.
