### ISSUE TITLE
Tracking in event based architecture

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/components#308]
My previous collegue that has a huge experience in js development pointed me such a great disadvantage of using event-based architecture:

It is really dificult to find all publishers and subscribes of all events.
He had got such a project from previous developer and needed to refactor it, and he spent a great amount of time to find all publishers and subscribes.
He didn't find any automation way to collect it - and the only way was to use full-text search.

In our case we have event publisheres and subscribes spread among repos. (I am using the same approach in user word-in-context lists) And it is more difficult to track all of them.

I really like event-based  approach and may be we should use some rulles to our code, comments in documents, some events map in documentation to track all of it while we are a the start of this way?

@balmas and @kirlat , what do you think?

**Comment by balmas** [comment]
I think that is a good idea. Perhaps we should require that any interface which publishes or subscribes to an event document in an specific way, and then have a custom linter function which verifies that the documentation is there and perhaps even extracts a map?

**Comment by kirlat** [comment]
I think we could do at least two things here:
1. We're already using JSDoc syntax, but never generated any documentation with it yet. So we could probably try to describe publisher to subscriber relationships with whatever tools JSDoc provides us. Then we could add a command to `package.json` to generate such docs automatically.
2. Subscriptions are made dynamically, but at each moment of the program execution each publisher knows all its subscribers. So we could add functions that will lay down all the publishers and their subscribers during program executions, per request (maybe we could even run it from a browser console if needed). In addition to that, we could add recording of any subscriber execution by the publisher in real time. That will give us a clear dynamic picture what calls what and when. 

We already started to work on a logger. We could probably expand it by adding a domain parameter, that will allow to enable logging selectively, for certain functionality only. For example, if we set domain to be `Event Controller`, we could enable tracking of these controller events only, while keeping everything else off.

**Comment by balmas** [comment]
I think is a great idea. @kirlat what do you think?

**Comment by kirlat** [comment]
I think it is a great idea! I can update the `PsEvent` class to include this, if nobody objects 🙂

**Comment by irina060981** [comment]
@balmas and @kirlat , great!
Then we could update components repo and wordlist repo (they both use event-based model).
It has not such much usage for now :)

**Comment by irina060981** [comment]
The ability to track is added.
