### ISSUE TITLE
authentication: require consent to terms

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#314]
We need to follow the GDPR rules and track consent to terms and service. instructions for Auth0 are here

https://auth0.com/docs/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-lock

This will need to be changed in the lock config for the embedded library and the hosted login page on the AuthO service. 

We need to make sure we can easily require a re-signing of consent when the terms change.

**Comment by balmas** [comment]
I'm going to split this into two issues: this one is for requiring consent to terms upon signup.  In the future we should track consent but it may not be required for minimal GDPR compliance.

**Comment by balmas** [comment]
I have changed the hosted login form to require consent upon signup. This can be tested now in the webextension and the next build of the embedded library.

**Comment by balmas** [comment]
embed-lib 1.0.0.24 webextension 3.0.0.41

**Comment by monzug** [comment]
tested in Chrome and Firefox build 3.0.0.41 and text env in mobile too.
Now it's required to check the consent check box when signing up with google or just signing up.
