### ISSUE TITLE
add settings (options) groupings

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#323]
We need to have a more organized way of presenting the user-configurable settings to the user.  The options in the settings panel are too many to scroll through and not organized in a coherent manner.

It would be nice to be able to use a tabbed display to keep like or most frequently used settings together. Not sure the best way to do this - if it's in the current panel, or if we create a separate ui component that just deals with settings.  The webextension architecture offers a mechanism for this (see alpheios-project/webextension#78 ) but I think we need to implement our own that isn't dependent on the delivery application because it needs to be available in the embedded library etc. to.

**Comment by balmas** [comment]
@irina060981 can you take a stab at this to see if you can improve the way the options panel looks? We do now have 3 separate components, one for each type of setting (resource-settings, feature-settings, ui-settings) + the font size (which should be included with ui).

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
qa-3.0.0.50/components 1.2.15

**Comment by monzug** [comment]
uhm, I am not so crazy about those letters 1) usually User interface  is UI not just U, right? maybe 1,2,3 I don't know

anyhow, it looks like I am not able to remove or add any grammars in Resource options

**Comment by irina060981** [comment]
> anyhow, it looks like I am not able to remove or add any grammars in Resource options both in chrome and FF

I didn't touch this - but I will check

**Comment by balmas** [comment]
> > anyhow, it looks like I am not able to remove or add any grammars in Resource options both in chrome and FF
> 
> I didn't touch this - but I will check
> 
> It doesn't work for me even in Chrome

possibly I broke it with the regrouping, although I thought I had tested it.

**Comment by balmas** [comment]
@irina060981 if you don't mind, I will give this back to you

**Comment by balmas** [comment]
as for the letters -- what if we just use links instead of tabs?

[user interface settings](#)
[feature settings](#)
[resource settings](#)

and clicking on the link shows the corresponding options

it's a little less visually appealing maybe, but clearer

**Comment by irina060981** [comment]
> as for the letters -- what if we just use links instead of tabs?
> 
> [user interface settings](#)
> [feature settings](#)
> [resource settings](#)
> 
> and clicking on the link shows the corresponding options
> 
> it's a little less visually appealing maybe, but clearer

It would be placed as 3 rows on the tab?

**Comment by balmas** [comment]
yes. do you think it's an awful idea?

**Comment by irina060981** [comment]
Advantages 
     - it would be more clearer
Disadvantages 
     - on mobile it will use all visible place on the tab 
     - it would be a new way to navigate

So I don't think that it is really awfull, but it makes sense only for new users
For users that were applied settings once it would be redundantly (from my point of view of course :))

I think we should choose according to our future users :)

**Comment by balmas** [comment]
hmm. all good points. What about using UI, Feature, Resource, where the 'eature' and 'esource' are in a smaller font?

**Comment by balmas** [comment]
(I know, I should not be allowed to make UI decisions...)

**Comment by irina060981** [comment]
It would be this way

![image](https://user-images.githubusercontent.com/12377640/62292680-46656180-b4aa-11e9-87d8-0131726b5921.png)

I don't think that it is bad - is it more understandable?

**Comment by irina060981** [comment]
> @irina060981 if you don't mind, I will give this back to you

I think the problem is here for multiple values

```
resourceSettingChange (name, value) {
    this.api.settings.getResourceOptions().items[name].filter((f) => f.name === name).forEach((f) => { f.setTextValue(value) })
```

It could be correct only for the single value, not for array

**Comment by balmas** [comment]
> It would be this way
> 
> ![image](https://user-images.githubusercontent.com/12377640/62292680-46656180-b4aa-11e9-87d8-0131726b5921.png)
> 
> I don't think that it is bad - is it more understandable?

Yes I Iike that!

**Comment by balmas** [comment]
> > @irina060981 if you don't mind, I will give this back to you
> 
> I think the problem is here for multiple values
> 
> ```
> resourceSettingChange (name, value) {
>     this.api.settings.getResourceOptions().items[name].filter((f) => f.name === name).forEach((f) => { f.setTextValue(value) })
> ```
> 
> It could be correct only for the single value, not for array

hmm. that code hasn't changed, I don't think.

**Comment by irina060981** [comment]
also this doesn't work

```
let keyinfo = Options.parseKey(name)
```

returns `lexicons` instead of `alpheios-resource-options__2__lexicons__grc`
so - it couldn't be updated

**Comment by irina060981** [comment]
> hmm. that code hasn't changed, I don't think.

I didn't test it for a long time :)

And I think we don't have unit tests for these aspects

**Comment by balmas** [comment]
@irina060981 I'll take a look at that. The use of parseKey here is necessary because of the way we reference the settings in the options object but it could be that I am misunderstanding something.

**Comment by irina060981** [comment]
ok - then I will stop to work on it for now - waiting for the results of your investigation :)

**Comment by balmas** [comment]
wish me luck :-) But please go ahead and do a PR for the change to the tabs. Thanks!

**Comment by balmas** [comment]
I have broken the problem with the resource settings off into #719 because it's not caused by the UI changes. Keeping this item open for responding to the changes to the tabs

**Comment by balmas** [comment]
qa-3.0.0.51/components 1.2.17

**Comment by monzug** [comment]
there is a misspelled word in the Resource button. it says Reasource
also I believe that it should be Apply rather than Applies. @balmas, what do you think?

**Comment by balmas** [comment]
Yes, saw the misspelling, that's #726 and will be fixed in the next build.

Re 'Apply' vs 'Applies' --- We could go either way here. I think with 'Apply' it would imply that it could affect the action -- i.e. the user should have a choice to apply to only some  settings.  Whereas what I meant with using "Applies" was to explain what would happen.  But if you think it's confusing that way, I will switch back to Apply

**Comment by monzug** [comment]
I am so use to see apply in the UI rather than the 3rd person. I am not
100% sure about it as this is not the option but the help, that's why I
double check with you. your call

**Comment by balmas** [comment]
I will change it to 'Apply'.

**Comment by balmas** [comment]
qa-3.0.0.52/components 1.2.18

**Comment by monzug** [comment]
cool
