### ISSUE TITLE
ensure utf-8 encoding for words entered in lookup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#328]
@monzug found an interesting bug on Safari. For some pages (e.g. https://thelatinlibrary.com/lucan/lucan2.shtml and https://thelatinlibrary.com/lucretius/lucretius3.shtml) the browser is encoding Greek works entered as lookups as HTML entities rather than UTF-8, so the lookup request to the morphology service fails (lexicon lookup still succeeds though).   If you change the encoding of the page to UTF-8 via the Safari view menu, the lookup text is properly interpreted as UTF-8.   Needs more investigation to understand exactly the conditions under which this occurs, but we should ensure lookup text is always interpreted as utf-8.

**Comment by monzug** [comment]
apparently issue is reproducible also in main page of latin library: https://www.thelatinlibrary.com
tested in Safari App Extension 3.0.1.83

**Comment by monzug** [comment]
Thanks!!!

**Comment by balmas** [comment]
qa3.0.3.87/components 1.4.5

**Comment by monzug** [comment]
Greek lookup works beautifully in latin library. Thanks
