### ISSUE TITLE
styles/design for Auth0 Login page

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#329]
Need to review and update design for Auth0 Login page

**Comment by balmas** [comment]
ok, made an attempt to apply our current style guide as much as Auth0 allows (and a bit more than that with some digging)


![Screenshot from 2019-04-23 15-33-59](https://user-images.githubusercontent.com/644870/56610471-75cc1e80-65dd-11e9-8c5e-6c0406b98418.png)
![Screenshot from 2019-04-23 15-33-53](https://user-images.githubusercontent.com/644870/56610475-79f83c00-65dd-11e9-9458-6108d803bf09.png)

**Comment by monzug** [comment]
test the login and resent psw. looks good.  I can see the Alpheios logo now!!!!!
do we have a standard for  messages? right now they appear on top of the page as follow
1) 
![email to reset psw](https://user-images.githubusercontent.com/41396793/56749446-c06da800-674f-11e9-9636-16820fbefd05.JPG)
2) 
![wrong-email](https://user-images.githubusercontent.com/41396793/56749474-ca8fa680-674f-11e9-9616-4859db2e906e.JPG)

**Comment by balmas** [comment]
we don't have much control over how and where the messages display without implementing our own login page. I managed to apply at least the same colors we use for our notifications by digging into their css code. I am hesitant to try to hack their html further though. There is a new version of the UI in beta and when that is more ready we might switch to it.

**Comment by monzug** [comment]
uhm, I still see the same messages as above in screenshots. pls confirm this is ok by changing status to verified. Thanks

**Comment by balmas** [comment]
done!
