### ISSUE TITLE
option to remember last location of the popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#335]
Requested by Josh Sosin:

When I select a word and the pop-up appears, I would love to (a) move the pop-up to where I’d like it (which I can do now) and (b) have it persist there as I click on other words on the page (which I cannot).

**Comment by kirlat** [comment]
I think this should not be particularly hard. Every time a popup/toolbar is moved (probably a couple of seconds after its coordinates has stopped to change) we can store its updated coordinates somewhere into configuration.

Also, do we need to keep coordinates between page reloads? If so, then we can duplicate them in the local storage.

Do we want a popup/toolbar to always be restored in the last remembered position or do we want to make it configurable via options?

**Comment by balmas** [comment]
I think yes, we need to keep coordinates between page reloads and yes, whether to do this should be configurable.

**Comment by kirlat** [comment]
We do have two position settings of the popup: fixed and flexible. With it set to fixed a popup will always appear at the set point of the screen, with flexible the popup should put itself around the word being shown (but I'm not sure if the last mode is working properly). So if we want to remember a popup position, it would make sense to do so only for the fixed position, maybe. Or do we, if `remember position` option is set, to apply it for both fixed and flexible positions?

**Comment by kirlat** [comment]
Also, if we decide to store position for the `fixed` mode only then do we ever need an option to enable or disable it? In the fixed mode, when popup will always appear at the same position over and over agian, the simplest way to restore a status quo is to drag a popup to the top left corner, where it will appear by default. That will be much simpler than going into options, finding the `remember position` options, and change its value. What do you think?

**Comment by balmas** [comment]
we never really got the flexible position working too well. I wish we could just drop it entirely, but am afraid the minute we do I'll be asked to put it back again :-) 

I agree we should remember the position only when we are using the fixed position setting.'

Let's try as you suggest without adding a "remember position" setting.  If we need to add that later based upon user request we can.

**Comment by balmas** [comment]
I think this can be tested in 3.0.0.31/1.0.0.7 and later.

**Comment by monzug** [comment]
tested in Chrome in text environment 1.0.0.7
I do also agree to keep the new coordinates of overlay and pop-up between page reloads and I verified that it works. Question: how do we go back to default position?

**Comment by balmas** [comment]
>Question: how do we go back to default position?
that will be provided with #488

**Comment by monzug** [comment]
good thinking! Thanks Bridget.

as per Firefox (3.0.0.31), unfortunately after the first move of the fixed pop-up (and overlay), I am not able to move it around again. I need to reload the page. note that the text environment works just fine also in firefox.

**Comment by balmas** [comment]
ok, giving back to Kirill to look at issue in Firefox.

**Comment by balmas** [comment]
> good thinking! Thanks Bridget.
> 
> as per Firefox (3.0.0.31), unfortunately after the first move of the fixed pop-up (and overlay), I am not able to move it around again. I need to reload the page. note that the text environment works just fine also in firefox.

I have actually entered a new bug for this, because I am seeing it on Chrome too.
