### ISSUE TITLE
make initial placement location of overlay nav a UIController constructor option

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#341]
initial placement of the overlay nav should be a UIController constructor option

**Comment by kirlat** [comment]
To control positioning, I've added the `initialPos` object to the toolbar module config parameter. This object should specify any combination of positioning parameters (top, right, bottom, left) in two different dimensions (X and Y). Pixel units should NOT be added to the values.

Example:
```
  initialPos: {
    top: 10,
    right: 15
  }
```
This corresponds to the current default position of a toolbar.

Here is how we can use it in, for example, an embedded library:
```
this.ui.registerModule(ToolbarModule, {
    mountPoint: '#alpheios-toolbar-embedded',
    initialPos: {
      left: 50,
      bottom: 200
    }
})
```

Would it provide what we need?

**Comment by kirlat** [comment]
I think our ultimate goal when adapting components to the AlpheiosReader is to keep as much common code between AlpheiosReader, embedded library, and webextension as possible.

To achieve this, we should make components configurable, especially if this configurability would benefit several target apps. This will allow to avoid creating separate versions of components for separate target apps. This scenario is highly undesirable as it will complicate code significantly. Separate component versions should be used as the last resort only.

We have several ways to achieve desired flexibility:
1. Through the use of configuration parameters of UI and data modules;
2. Through the use of different layout templates for modules. We're doing this internally for both panel and toolbar. It will be not hard to have it as a config parameter too. We're even able to change the layout dynamically, on components that are already initialized and active.
3. Through the methods of a UI controller that allow to configure and operate UI components, such as `switchTab()`, `openPanel()`, etc.

I think the combination of the above should be enough to handle probably any configuration reasonable imaginable 🙂 . What do you think? Are there any specific scenarios that might require something more than that?

**Comment by balmas** [comment]
yes that seems sensible.  So with your commit fif4206 will the following code already work?

```
this.ui.registerModule(ToolbarModule, {
    mountPoint: '#alpheios-toolbar-embedded',
    initialPos: {
      left: 50,
      bottom: 200
    }
})
```
I think we might need more than just initialPosition of left/bottom here in order to implement the design at https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Reader/Default.png . There we need a new component layout too and maybe additional positioning parameters?

**Comment by kirlat** [comment]
Yes, the code above should work with f1f4206b0d9d39eeae17341602482fa50cb2eb64.

Agree that for the new Reader design we need more than just positioning parameters, but I think we can do all this within our current architecture.

**Comment by kirlat** [comment]
Since we've not defined the exact changes in the architecture needed to support AlpheiosReader yet and it might take few iterations maybe it will make sense to merge f1f4206b0d9d39eeae17341602482fa50cb2eb64 now so that we'll have this feature in master and then continue doing other changes to support Alpheios Reader in succeeding commits? I just don't want to keep a branch parallel to master for too long, it may be a pain to merge. It's probably better to implement feature by feature and merge to master after each separate feature is complete. What do you think?

**Comment by balmas** [comment]
yes I agree.

**Comment by balmas** [comment]
@abrasax would really like us to anchor the tools icon in the headers on the alpheios texts display. So we need to reopen this, because I think we are back to needing a way for a user of the embedded library to be able to specify an element which activates this functionality.  Assigning to myself to provide a clear example...

**Comment by balmas** [comment]
Per discussion in Slack:

 the most general way to do it, that others could reuse, would be for the embedding page to be able to specify an element to which the ui controller attaches events.  

Currently this just applies to the the tools icon itself, i.e. the one that opens the action panel, but in the future we might want to have individual tools enabled this way. 

We might also want the ability to differentiate between behavior on desktop and mobile (e.g. on desktop it opens the full panel and on mobile the action panel) but for the beta let's assume it will open the action panel in a consistent experience on desktop and mobile.

@kirlat suggest we need to be able to:

1. Specify to which element it to be mounted
2. Disable it from being moved (if it is in a draggable variant)
3. separate component behavior from style

**Comment by kirlat** [comment]
Added a reading tools button to the mobile version of the Reader. When clicked, it opens an action panel:
![image](https://user-images.githubusercontent.com/18631055/57698564-f2936b00-7666-11e9-939a-dde9a5695c82.png)
Whenever the button is clicked on the action panel or the lookup is started, a "main" panel is opened. When the "main" panel is closed, an action panels becomes visible again. The action panel has to be closed manually.

On the desktop version of a platform in opens a desktop version of a toolbar, as previously.

@balmas, can you please confirm that the behavior described above is correct? If so, I will submit a PR with the changes.

**Comment by balmas** [comment]
yes that is correct (at least for now).

**Comment by kirlat** [comment]
These changes has been merged to master and are ready to be tested in the next build.

**Comment by balmas** [comment]
ready for testing in 1.0.0.13

**Comment by monzug** [comment]
verified.
