### ISSUE TITLE
tooltips for Alpheios toolbar don't display

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#342]
if the Alpheios toolbar is expanded and placed on the left side of the screen, when you mouse over Help or Definitions or Options, the related tooltip is not displayed

**Comment by monzug** [comment]
the toolbar can also be dropped outside the screen, not sure if this is intentional

**Comment by kirlat** [comment]
Submitted a build that should fix that

**Comment by balmas** [comment]
This is in 3.0.0.29

**Comment by monzug** [comment]
tested in Chrome and Firefox in build 3.0.029
the tooltips are displayed correctly. however I am still able to move the overlay outside the visible screen both in Chrome and Firefox.

**Comment by balmas** [comment]
> tested in Chrome and Firefox in build 3.0.029
> the tooltips are displayed correctly. however I am still able to move the overlay outside the visible screen both in Chrome and Firefox.

I think that got missed. Entered it as a new issue #472

**Comment by kirlat** [comment]
@balmas, since the issue with toolbar not restricted by the viewport is now a separate one and the tooltips are fixed, can we close this now?

**Comment by balmas** [comment]
yes I think so.

**Comment by monzug** [comment]
Is this broken again or it's my environment? tested in build 3.0.0.31 in both Chrome and Firefox and text environment. the tooltips for the overlay placed on the left of screen are not visible

**Comment by balmas** [comment]
fixed in build 3.0.0.33 (webext)/1.0.0.11 (embedlib)

**Comment by monzug** [comment]
if overlay is on the left of screen, so tooltips are. it's there a way to open them on the right when overlay is on the left? not a big deal as I can move the overlay around to display them, just checking.
![tooltip-left](https://user-images.githubusercontent.com/41396793/57570234-dc1eb280-73cd-11e9-9edb-ec78bcb43a8e.png)

**Comment by kirlat** [comment]
I've submitted a PR that should fix this: #533
