### ISSUE TITLE
apply new styleguide

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#346]
apply new styleguide colors, sizes, etc. to the core components.

The style guide is at https://github.com/alpheios-project/design-guidelines/blob/master/v3/Alpheios-Style-Guide.pdf

It's a combination of styles for website and application, the colors, sizes, fonts etc. apply to both. Application-specific guidelines are at the end of the guide.

Mockups of the styleguide rules applied to the alpheios core components are in there as well:

https://github.com/alpheios-project/design-guidelines/blob/master/v3/Mobile
https://github.com/alpheios-project/design-guidelines/blob/master/v3/Panel
https://github.com/alpheios-project/design-guidelines/blob/master/v3/Popup

**Comment by balmas** [comment]
When implementing this, I'd like us to refactor and clean up a few things with regard to the core components styles.  

Basic Configuration Requirements for Styling:

(1) End user should be able to configure the base font size for the Alpheios components (small, medium or large)

(2) The embedded library should be able to configure a branding skin for the Alpheios components via its constructor arguments.

We should remove the existing options for skin and colors from the UI. 

The default Alpheios skin should define variables for all of the details that are in the style guide. I.e. logo, colors, typography, link styling, button and icon colors and sizes.

Any css that is in the components themselves should always use skin variables for all these same properties (i.e. colors, typography, link styling, buttons, icon colors and sizes. 

For this release, I would like to keep the capabilities for skinning simple -- i'm fine with an all-or-none approach -- i.e. requiring any 3rd party using the embedded library who wants to brand the interface to completely override all variables defined in the default alpheios skin.

**Comment by balmas** [comment]
It might be helpful to start with the bootstrap overrides file that I have been using for the Alpheios Reader interface. https://github.com/alpheios-project/alpheios_nemo_ui/blob/v2.0-tei-test/alpheios_nemo_ui/data/assets/scss/bootstrap_overrides.css

**Comment by balmas** [comment]
Note also that I have now added a demo file to the embedded library which is based upon the wip version of the Alpheios Reader application (which will use the embedded library). It's the embed-lib/demo/AlpheiosReader.html file. Although this is still in flux and needs further design input, going forward we need to start testing all Alpheios components UI changes in that context as well as the webextension.

**Comment by kirlat** [comment]
This is probably a work in progress for some time ahead, but I'm wondering if it would make sense to close this issue and track whatever will arise in issues of their own.

**Comment by balmas** [comment]
yes I agree.
