### ISSUE TITLE
need better immediate visual indication when word selection worked on mobile

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#348]
right now the long tap can be a little tricky and doesn't always work. since it can take a second or two for the results to display in the panel, we need an immediate visual indication as soon as the word selection is captured.

**Comment by balmas** [comment]
I think this is generally working better now. closing for now. we can reopen based upon feedback as needed.

**Comment by balmas** [comment]
ok, feedback from @abrasax and Mark is that they are still finding this tricky.  Wondering  if we can fine tune the long tap behavior so that it works better

**Comment by kirlat** [comment]
In my tests I found it very beneficial for perceived responsiveness to disable user selection with `user-select: none`. When touch is intercepted by the text selection of the browser it causes a noticeable delay. It also may prevent `getSelectedText()` of the Alpheios from being fired. So I'm thinking probably we can add an option to a UI controller that, when enabled, will inject `user-select: none !important` to the body of mobile pages. We can also probably have a UI option to enable or disable that. This is our intrusion to host pages, but it can probably justified as it serves good purpose. I also think not so many users will use text selection on pages with Alpheios enabled. But if they do, us making it configurable will allow them to keep this functionality.

I will also check if there are any other delays we can eliminate to make the process more responsive.

**Comment by kirlat** [comment]
I've made code changes to open the UI sooner after selection in complete. It helped to reduce response time by around 50ms on mobile devices I've tested it with. 

I've also added an option to turn off a browser-based text selection on host pages. A browser-based text selection can prevent getSelectedText() from running. This option is configurable via a UI controller's constructor parameter.

**Comment by kirlat** [comment]
The changes has been merged to master. Disabling of browser-based text selection is controlled by the `disableTextSelection` parameter of a UI controller's constructor (must be turned on in webextensions if we decide to disable it on all mobile pages where webextension is running) and the same parameter of the constructor of the embedded lib (it will allow the page owner to decide whether to disable it on that particular page or not).

If we find it useful, we can also add a UI options to the options panel that will allow to turn it on and off on the case by case basis.

**Comment by balmas** [comment]
@kirlat, is there any way to get the selected word highlighted on the page when disableTextSelection is on? While it seems a little more responsive to me (at least when used in Alpheios nemo ui, I couldn't get selections to work nearly at all on the embed lib demo page) it feels like operating blind not to see the word highlighted.

**Comment by balmas** [comment]
adding notes from Slack discussion on this:

kirlat 
> I think we're getting a Selection object from the browser here, so we probably can highlight it
I just see a UX experience with it
It will get highlighted when selection is complete. So this is also the moment we'll open the panel
So the user will see the word selected and then it will start the query right after that.

balmas 
> hmm. so maybe we should not implement this.

kirlat 
>Not sure if it will be helpful or not because the user cannot change anything once selection is done
But I also was missing this highlighting feedback
Just not sure how it should be made UI-wise
Maybe user puts finger on the word, the word gets highlighted after some time, and if user keeps the finger for some more time the query starts. If the user lifts the finger, the query is cancelled
To me, probably something like that would be the best
But it's much more complex than what we have implemented now and will require change to the pointer events library

balmas 
> yes, I think maybe we could consider that after the beta if user feedback warrants it
i.e. if lots of people are having trouble with the selection as it is currently (using the default browser behavior)

kirlat
> Yes, a agree. I think it probably be a mistake to do something truly complex now if user feedback do not suggest it. Because we can spend a lot of time chasing something of little importance. What do you think?

balmas 
> yes, agree completely

**Comment by balmas** [comment]
moving further work on this out of the beta.

**Comment by balmas** [comment]
closing this pending further user feedback. It seems to be working pretty well right now.
