### ISSUE TITLE
bug in setting popup dimensions when visibility is updated

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#358]
I think the following bit of code, which updates the popup dimensions when its visibility state changes might be incorrect. I think the order of parameters for the watch function are reversed - according to the vue documentation the order of arguments for the callback are newValue followed by oldValue

```
  this.$options.visibleUnwatch = this.$store.watch((state) => state.popup.visible, (oldValue, newValue) => {
      if (newValue) {
        // A popup became visible
        this.updatePopupDimensions()
      } else {
        // A popup became invisible
        this.resetPopupDimensions()
      }
    })
```

**Comment by kirlat** [comment]
That's a very good catch! The arguments are really reversed, and it means that popup dimensions are updated when popup is closed which does not appear to be useful at all.

That made me question whether we ever need this watch function. I commented it out and things continued to work fine in my tests even without it. I remember I've added it during refactoring to emulate a watcher we had there before. But the question is: do we really need it? We have an `updated()` callback that updates popup dimensions. It should catch all content changes: https://vuejs.org/v2/api/#updated. I tracked it with the log statement and it's called several times during the regular popup workflow (i.e. double clicking on the word). @balmas, @irina060981, do you remember any reason why we have this specific visibility watcher there? Maybe we can just remove it and live without it?

**Comment by balmas** [comment]
I'd suggest to remove it for now if you cannot see any reason for it.

**Comment by kirlat** [comment]
Submitted a PR that removes this code. It works well without it in my tests.

**Comment by balmas** [comment]
This is in 3.0.0.29 but might be difficult to test. Probably better to wait for #332

**Comment by monzug** [comment]
will wait to test with #332

**Comment by monzug** [comment]
Not sure how to test this. @balmas?

**Comment by balmas** [comment]
I think if resizing works, then this can be verified, but I believe resizing was broken due to other changes, and the fix is waiting for me to give you a new build.

**Comment by monzug** [comment]
uhm, I just verified the resizing one for desktop but not for mobile

**Comment by kirlat** [comment]
> uhm, I just verified the resizing one for desktop but not for mobile

We do not show the popup on mobile so I think this should be tested for desktop only

**Comment by monzug** [comment]
I verified issue #332  for desktop only. it's about panel resizing in general.

**Comment by monzug** [comment]
I don't see any issue with pop-up resizing here.
