### ISSUE TITLE
Wordlist vs word list in tooltip

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#359]
reported by @monzug 
Minor issue: we have 'User word list' tooltip and also 'Back to WordList' tooltip. for consistency, they should be the same.also, we have Remove worditem and Remove all word items

**Comment by irina060981** [comment]
Fixed, merged and closed

**Comment by balmas** [comment]
in 3.0.0.25

**Comment by monzug** [comment]
tested in firefox 3.0.0.25 - fixed. Thanks
