### ISSUE TITLE
on Firefox, popup doesn't redraw until full definition queries are finished

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#362]
This seems to be more of a problem on Firefox than Chrome, haven't tested on Safari yet. The lexical query loading message displays until all of the lexical query requests complete, including the full definitions. It should start updating as soon as we have any data from the morphology lookup.

**Comment by balmas** [comment]
Additional information from Slack discussion with @irina060981 

There are differences in how the different languages are shown:

>when you try geez - it draw popup at the same time and show correct progress
when you try persian - it shows first error - no data
annd in some time it uploads data
when you try arabic - it renders later than for other languages

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
would like to verify that this is working now

**Comment by monzug** [comment]
firefox 3.0.0.25, looks fine to me - need more testing

**Comment by monzug** [comment]
tested again on the test.html file in firefox build 3.0.0.36 - works fine
could not test in safari build 3.0.0.33 as the overlay did not appear in the tab with the test.html file. Note that the overlay is normally generated on activation of alpheios in the latin library site. I'll create a safari issue
