### ISSUE TITLE
confirmation before delete all on wordlist

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#363]
we should probably ask the user to confirm that they really want to delete all their words before proceeding to delete all following a click on the wordlist delete icon

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
I think this can be tested in 3.0.0.25

**Comment by monzug** [comment]
yes, we get the message now.

**Comment by monzug** [comment]
forgot to ask, can we display the message in same style as login messages? if this is out of scope, pls disregard.
