### ISSUE TITLE
review Vuex mutations for performance issues

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#364]
This issue is to request a review of all Vuex module mutations to identify potential performance issues, as seen in #360 

From @kirlat in Slack:

>As a general rule, we should never put anything that runs for long into the mutations, because mutations are synchronous. I think we should probably put no calculations into mutations at all (except the simplest ones, but that might be arguable; for more complex things actions are a better choice). Probably a mutation should be a "technical" function that just assigns values to store objects, when those values are already calculated.

>So if we have something that might take long (a network request, or a calculation that will takes long), we better not to put it to the mutation, but rather create a method, do a network request (in a "true" async way, not with `await`) or a calculation there, and then call a mutation to just assign the values.

**Comment by balmas** [comment]
@irina060981 to check for this in wordlist and usage examples components and modules
@kirlat to check for this in the other components and modules

**Comment by irina060981** [comment]
I have checked wordUsage components.
I have only the following mutations:
   `setWordUsageExampleEnabled`
   `setWordUsageExamplesReady`
   `setWordUsageAuthorsReady`

All of them are really simple boolean values.
So for this part I couldn't make any optimisation.

**Comment by irina060981** [comment]
I have checked wordList components and made all optimizations when was integrating components from wordlist repo.

As for Vues mutations - We are using only 
`app/setWordLists` that sets Boolean property - `hasWordListsData` and Date property `wordListUpdateTime` for tracking updates inside components

And that's all
So we don't need optimisations from this point of view

**Comment by irina060981** [comment]
@balmas and @kirlat , do you see here some more changes with wordUsageExamples and wordList from me? If not, could I unassign this issue from myself?

**Comment by balmas** [comment]
ok @irina060981 removing you from this issue. Thank you!

**Comment by kirlat** [comment]
I've checked our code in its current state, after all recent optimizations, and I do not see any issues with the way we're using Vuex. There is no large objects stored in there, and there is no blocking transactions calls from mutation. We probably can close this now.

**Comment by balmas** [comment]
ok. closed.
