### ISSUE TITLE
Review reactive objects in Vuex stores for performance issues

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#365]
This issue is to request a review of all reactive objects in the Vuex stores to identify potential performance issues, as seen in #360

From a Slack conversation with @kirlat 

>... as objects in Vuex store are reactive, we should not try to put complex objects (such as inflection tables) there as it may result in performance degradation. If we need to track a state of such object reactivealy, we can:
>1. Store a complex object within a UI controller or some other object.
>2. Make this object accessible to UI components by exposing it to the public API.
>3. Make a reactive prop in the Vuex store to track object updates (`updated`).
>4. Include this Vuex reactive prop into a computed prop of a UI component that returns an object the the UI component. This way every time a Vuex prop is changed, a visual representation of this object in the UI component will be refreshed.
>5. Every time we update an object, update the Vuex reactive prop (i.e. `updated`) as well.

**Comment by balmas** [comment]
@irina060981 to check for this in wordlist and usage examples objects
@kirlat to check for this in the other components

**Comment by irina060981** [comment]
For wordUsageExamples

I have only one complex object `wordUsageExamples` and I am tracking it using simple Vuex property `setWordUsageExamplesReady`

So there is no need in optimisation here.

**Comment by irina060981** [comment]
For wordList

We don't have any complex objects inside VuexStore.
Current wordLists are saved inside wordListController and controlled inside it with the help of IndexedDB and RemoteSource.

I don't think that it is a good solution to save it accordinly to the Vuex store, because it will increase dependencies between UIController and WordlistController.
For now we have all actions from wordlist published to app store module:
```
     getWordList: this.wordlistC.getWordList.bind(this.wordlistC),
      selectWordItem: this.wordlistC.selectWordItem.bind(this.wordlistC),
      updateAllImportant: this.wordlistC.updateAllImportant.bind(this.wordlistC),
      updateWordItemImportant: this.wordlistC.updateWordItemImportant.bind(this.wordlistC),
      removeWordListItem: this.wordlistC.removeWordListItem.bind(this.wordlistC),
      removeWordList: this.wordlistC.removeWordList.bind(this.wordlistC),
      getAllWordLists: () => this.wordlistC ? this.wordlistC.wordLists : [],
```
So I don't see what other optimisations could be done here.

**Comment by irina060981** [comment]
@balmas and @kirlat , should I do something else here with wordUsageExamples and wordlIst?
Or could I unassign it?

**Comment by balmas** [comment]
ok, thanks @irina060981 removing you from this item.

**Comment by kirlat** [comment]
I checked the code at its current state, and I think we're fine for now. Let's try to keep it that way in the future!

**Comment by balmas** [comment]
ok.
