### ISSUE TITLE
wordlist - restyle context links if same as current page

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#374]
>the words in wordlist look like active links but if you click on them, nothing happens. are they supposed to be active link?

They ARE active links, but if you are testing without login, then yes it looks like nothing happens because it just reloads the page you are on.  I think we should have a different styling if the context is the same as the page we are on and indicate that it is the current page (and not make it linked). Do you agree @monzug ? If so then I will turn this into a new issue.

_Originally posted by @balmas in https://github.com/alpheios-project/components/issues/304#issuecomment-478623770_

**Comment by balmas** [comment]
When displaying the wordlist, we should check to see if the url referenced in the context (excluding any location hash) is the same as the current url, and if so, style these differently to indicate that it's the current page and not make them active links.

**Comment by irina060981** [comment]
@balmas , It seems to me that it is about the same
https://github.com/alpheios-project/components/issues/409

**Comment by monzug** [comment]
looks the same to me.

**Comment by balmas** [comment]
Oh, I misunderstood. I thought this was about the context links. Yes, then this is probably the same as #409. Will close as dupe.

**Comment by monzug** [comment]
I will assign to myself to retest when #409 is fixed, so I can verify that everything works ok

**Comment by irina060981** [comment]
Great! I think it will be very useful to understand if it is quite right now :)

**Comment by monzug** [comment]
the show contexts does open a new link even if the word is from current passage. I don't think we need to have a different style if the context is the same as suggested above.
