### ISSUE TITLE
minimum 1 for usage examples max results per author

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#376]
why do we allow 0 in these Options:
Word Usage Examples - max results per author   and     Word Usage Examples - max results for single author request? if I do apply them I get no results so not sure why we set this limit to 0.

_Originally posted by @monzug in https://github.com/alpheios-project/components/issues/307#issuecomment-479011418_

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
I think this can be tested in 3.0.0.25

**Comment by monzug** [comment]
Range is 1 to 1e+21 (100000000000000000000) - do we need to set a max too?
in issue #307 @balmas suggested: 
But in order to get that 1086 results, we need to set the actual max much higher, because any one author might themselves have 1086 results for a given word. So to ensure that we get the 3 hits per author, we have to set the overall max very high for now.

**Comment by balmas** [comment]
Hmm. we probably should enforce a max here. There are two settings, one for max all results, and one for max per author. They don't apply together. When max per author is chosen, we override the max for all to make sure we get enough, But for both user-facing settings we should probably enforce a reasonable maximum.  Maybe 1000?

**Comment by balmas** [comment]
Hmm. we probably should enforce a max here. There are two settings, one for max all results, and one for max per author. They don't apply together. When max per author is chosen, we override the max for all to make sure we get enough, But for both user-facing settings we should probably enforce a reasonable maximum.  Maybe 1000?

**Comment by balmas** [comment]
Hmm. we probably should enforce a max here. There are two settings, one for max all results, and one for max per author. They don't apply together. When max per author is chosen, we override the max for all to make sure we get enough, But for both user-facing settings we should probably enforce a reasonable maximum.  Maybe 1000?

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
can be tested in 3.0.0.26 (https://github.com/alpheios-project/webextension/tree/qa-3.0.0.26/dist and Dropbox)

**Comment by monzug** [comment]
range is now 1 to 1000. tested in chrome 3.0.0.26
