### ISSUE TITLE
Wordlist: test case in which same word from two different books/authors

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#377]
tested in Chrome on text environment with login.
When I double click the same word (e.g. Caesar) from different section within the same book, the new sentence just gets added in Show context (note that there is only one link to text). However, when I have the same word but from different book, Alpheios does not handle in the same way. Arma is the first word in Virgilius --  http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0690.phi003.perseus-lat2/passage/1.1-1.30
and also there is arma in Horace 9.1-9.30 -- http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0893.phi003.perseus-lat2/passage/1.1-1.30
I have Arma from Virgilius saved in my word list., then I do double click on arma from Horace. if I look at word list,  and follow the link in Show context for Arma, and back to wordlist,, there is only one word there and the Show context is empty. the situation got back normal when I go to main page - word list is back populated but no trace of arma in wordlist.
let me know if it's too confusing and I will add step by step scenario (if alpheios will cooperate...).
I don't know if it's the upper case A (Arma vs arma) or the two different books, but there is something wrong here

1) my wordlist
![mywordlist1](https://user-images.githubusercontent.com/41396793/55417449-b7b5f780-553e-11e9-804a-819071aae1ab.JPG)
2) wordlist after double-clicking on arma
![where is my wordlist](https://user-images.githubusercontent.com/41396793/55417484-cb615e00-553e-11e9-8762-c61d5a3d474c.JPG)

**Comment by balmas** [comment]
I think we probably do not identify Arma and arma as the same word.  We should probably do a case insensitive match on the worditem text when checking for equivalence.  Handing to Irina.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
I think this can be tested in 3.0.0.25

**Comment by monzug** [comment]
it works! see screenshot
![arma-virumque-cano](https://user-images.githubusercontent.com/41396793/58034678-1fc39b80-7af5-11e9-918b-c5b96bea8f22.JPG)
