### ISSUE TITLE
wordlist context links should open in new tab

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#379]
I haven't yet a reproducible scenario but I enter the issue to keep track of this.

Few times today I have been prompt to login again while I was already logged in.

1) I did login, populated the wordlist with new words then logged out. Logged in again, added some new words then looked (show context etc) to words from saved wordlist, I got prompt to login again
2) when going from one book to an other with back arrow

again I do not have a reproducible scenario. Further investigation needed.

**Comment by monzug** [comment]
this is still reproducible. not sure if it's this a desire behavior so checking with @balmas.
login the add some words to wordlist.  click on Show context  from any of the saved words in wordlist, then follow the link to the section. the book's section is open on blank panel (issue here????), if I go on user info and click on the log in button, I ma automatically logged in without prompting for is/psw. Pls advise.

**Comment by balmas** [comment]
this is not desirable :-) will take it as a bug.

**Comment by monzug** [comment]
do you think it would be a good idea to keep the current section still open? right now, we follow the link to new section and we close the current one. not sure it's a good idea.

**Comment by balmas** [comment]
I think this is mostly the same issue as #427 

I do agree we should have the context links open in a new tab.  Let's keep this item for that, and #427 will fix the login/logout issue.

**Comment by balmas** [comment]
in webextension qa-3.0.0.30 and texts-text (embed-lib 1.0.0.6)
(https://github.com/alpheios-project/webextension/tree/qa-3.0.0.30/dist and Dropbox)

**Comment by monzug** [comment]
tested in Chrome and Firefox 3.0.0.31
