### ISSUE TITLE
Add link to login for embedded library 

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#388]
> .... I do not see any button next to the message. should I? I ma in text env in chrome see screenshot

Oh, I forgot that you are using the embedded library in the texts environment. I do not have a button or link here because the login is actually in the encompassing application. This is a bit difficult to think how to do. I think it's possible though, so will make a separate issue for that.

_Originally posted by @balmas in https://github.com/alpheios-project/components/issues/317#issuecomment-480864847_

**Comment by balmas** [comment]
can be tested in texts-test (embed-lib 1.0.0.6)

**Comment by monzug** [comment]
if I click on Login I get Authentication failed. tested in Chrome  and firefox 1.0.0.6, also on mobile (iPhone 6)

**Comment by monzug** [comment]
![IMG_3425](https://user-images.githubusercontent.com/41396793/57027276-fc01e980-6c09-11e9-8a15-d2d74153c80b.JPG)

**Comment by balmas** [comment]
oops forgot to deploy the configuration that goes along with this. That's there now and it should be working (you may need to restart the browser).

**Comment by monzug** [comment]
tested in 1.0.0.7 on iPhone 6s
