### ISSUE TITLE
Change psw request

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#391]
Tested in Chrome in test environment.
when I request to change psw, I did receive two emails: first one to verify my account and the second one to confim psw change. why two? why am I getting the verify account? when I followed the link to verify account, it said "Verified" with no link to sys admin or any Alpheios reference.
As Bridget suggested, we do not know how much control we have on this.
 see screenshot 
![email-verification](https://user-images.githubusercontent.com/41396793/55735304-140d9100-59ef-11e9-82bd-9c2f445d0a63.JPG)

**Comment by balmas** [comment]
I believe my changes for #392 have fixed this.

**Comment by monzug** [comment]
Absolutely fixed. I do receive one email from alpheios with link to reset psw.
