### ISSUE TITLE
Change psw messages do not have any reference to Alpheios but to Auth0

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#392]
The change psw message does not have any link back to the Alpheios site or browser session.
Both messages (change psw and verify account) come from Auth0. Can we change Auth0 to Alpheios or similar? we do not have any reference to Alpheios in both messages.
see #391 
![sign-in-with-auth](https://user-images.githubusercontent.com/41396793/55735670-ccd3d000-59ef-11e9-8d91-1c19ed1e25f7.JPG)
![password-changed](https://user-images.githubusercontent.com/41396793/55735686-d2c9b100-59ef-11e9-965e-f49e88e464ac.JPG)

**Comment by balmas** [comment]
I have customized the various emails now.

This is what you should get

Verification Email ![Screenshot from 2019-04-23 15-25-09](https://user-images.githubusercontent.com/644870/56609980-76b08080-65dc-11e9-9f3e-2c4ce473c1a9.png)

Password Reset 
![Screenshot from 2019-04-23 15-24-48](https://user-images.githubusercontent.com/644870/56610020-87f98d00-65dc-11e9-8b66-29bddf8e195f.png)

Account Blocked ![Screenshot from 2019-04-23 15-25-09](https://user-images.githubusercontent.com/644870/56610038-8fb93180-65dc-11e9-9b4b-a2d5e89cf8ef.png)

Password Breach 
![Screenshot from 2019-04-23 15-25-29](https://user-images.githubusercontent.com/644870/56610055-9b0c5d00-65dc-11e9-90f7-2f9eb8d510fb.png)

**Comment by balmas** [comment]
@monzug some questions for you

1) on the password reset verification screen (not the email) -- we don't have the ability to send them back exactly to where they came. I could have a general link to the alpheios website here though I believe. Do you think that would be useful?

2) for the logo in the emails, do you think it's better to use the full logo with the Alpheios name, or just the icon as I currently have it?

Let me know if you see anything else that needs to be changed in the email content.

**Comment by balmas** [comment]
@monzug I should note -- I have switched to using AWS to send the emails from Auth0, and there is a short waiting period before it's enabled for all addresses. Might be as soon as tomorrow, but if not and the inability to get email for new accounts etc. holds you up, let me know and we can work around it by adding permissions for specific emails for testing.  It was necessary to make this switch to customize the emails.

**Comment by monzug** [comment]
on the password reset verification screen, maybe a link to alpheios main page wouldn't hurt but  I don't think it's critical right now.
I could test the password breach but screenshot looks good.

**Comment by balmas** [comment]
> on the password reset verification screen, maybe a link to alpheios main page wouldn't hurt but I don't think it's critical right now.
> I could test the password breach but screenshot looks good.

that's a good idea. will create a new issue for it.

**Comment by monzug** [comment]
I meant I could NOT test the password breach.
