### ISSUE TITLE
open compact panel split screen to the right on mobile in landscape mode

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#397]
See https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Landscape-Mode-Panel-Open.png

We might want to make it possible for the user to make it left or right

**Comment by balmas** [comment]
This is in 3.0.0.29 but needs to be tested in the texts environment.

@monzug we should talk about testing mobile ....

**Comment by monzug** [comment]
I usually use my iPhone 5. I also have a Samsung at home (somewhere).

**Comment by monzug** [comment]
in mobile the morphology opens in fixed position on the bottom of the screen. in landscape mode, I can't see any of the texts behind the pop-up - see screenshot
![IMG_3433](https://user-images.githubusercontent.com/41396793/57241869-03593680-7000-11e9-9e6d-60f5aec6e549.JPG)
on the iphone 6s, see screenshot
![IMG_3434](https://user-images.githubusercontent.com/41396793/57242116-a742e200-7000-11e9-849e-60011882e702.JPG)

**Comment by balmas** [comment]
moved this comment from #482 

> @kirlat this is in the latest embed-lib build and I think there is still some work to do wrt to the padding and font-sizes because there are some issues with the landscape mode in the alpheios nemo ui (the texts environment).
> 
> It's possible it's related to #496 which I have assigned to you now too.
> 
> It could also be that we need a combined fix -- i.e. styles that accomodate the panel more cleanly in the embedding environment.
> 
> I also notice that sometimes the font size in the panel is quite a bit larger than I expect it to be when used in nemo.
> 
> ![Screenshot_20190503-160642_Chrome](https://user-images.githubusercontent.com/644870/57162928-b5ed8700-6dbd-11e9-885c-b48d6c58b31c.jpg)

**Comment by monzug** [comment]
tested in 1.0.0.9 - when I click on the arrow to go right, it does expand the morphology pop-up to full screen. I was expecting to swap screens: on the right, Alpheios pop-up and on the left, the reader view.

**Comment by kirlat** [comment]
Well, this is an expected behavior. The left or right arrows on the panel on mobile do intend to expand it full to either left or right. For the sake of better icons I've put Font Awesome's "chevron" ones, but because they're so close to "switch side" icons on desktop (only thicker) it is really confusing. We were discussing it with @balmas, but so far we have no better solution icon-wise 🙂.

**Comment by balmas** [comment]
What about a plus/minus embedded in a chevron? +> <-

**Comment by monzug** [comment]
we are having an icon crisis...

**Comment by balmas** [comment]
I think maybe this one can be closed now @monzug ? I entered #547 to change the panel for moving the panel to the left and right and alpheios-project/alpheios_nemo_ui#158 to fix the navbar in landscape mode

**Comment by monzug** [comment]
on Samsung 5s, the screen is split in landsacape mode (the lookup is hidden by the nav bar so can't see the entry field)
on iPhone xr, the screen is not splint in landscape mode
![IMG_3450](https://user-images.githubusercontent.com/41396793/57675972-6b57e000-75f1-11e9-84ab-2e6e6ad7a3c0.PNG)

**Comment by kirlat** [comment]
@monzug, since I don't have an iPhone XR and cannot reproduce can you please test its rotation from portrait to landscape and back on http://embed.yula.media/demo/ ? We need to check that its recognizing a landscape orientation correctly. Also, does it report `or.chg` event callbacks during orientation change (must report one event CB per on orientation change). Thanks!

**Comment by monzug** [comment]
yes, it does report the or.chg rsz event one for each change. is that all?

**Comment by kirlat** [comment]
> yes, it does report the or.chg rsz event one for each change. is that all?

Thanks, yes, that's it. I assume it does display orientation properly as "landscape" when turned into landscape?

**Comment by monzug** [comment]
nope, that's not supported

**Comment by kirlat** [comment]
Sorry for bothering, but can you please upload a screenshot of a test page when the iPhone XR was in portrait orientation first and then turned to a landscape? That would be very helpful!

**Comment by monzug** [comment]
no problem at all
![IMG_3481 (1)](https://user-images.githubusercontent.com/41396793/58116099-7bf7ef80-7bc9-11e9-86da-0c62bfb114ee.PNG)
![IMG_3480 (1)](https://user-images.githubusercontent.com/41396793/58116101-7c908600-7bc9-11e9-9ae0-03ed4310b19c.PNG)

**Comment by kirlat** [comment]
Thank you!

**Comment by monzug** [comment]
Hope it can be of any help!!!!

**Comment by balmas** [comment]
ok, ready for testing (again) in texts-beta
embed-lib 1.0.0.16 webextension 3.0.0.37

**Comment by monzug** [comment]
confirm split screen on iPhone xr. it's not on the right but left side and then I can expand.

**Comment by kirlat** [comment]
> it's not on the right but left side and then I can expand.

Left is a default position of the panel now, for both desktop and mobile (@balmas - shall we make it right as default for mobile or does it not matter?). But from within the Options menu user can switch to have panel at the right, if he or she prefers so.

**Comment by balmas** [comment]
> (@balmas - shall we make it right as default for mobile or does it not matter?). 

I think it doesn't matter too much.
