### ISSUE TITLE
compact toolbar nav

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#399]
We want a compact version of the toolbar nav that looks like the one in 
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Default.png
(small book icon)

It should just open the compact panel and not expand a full nav bar.

Not sure yet about how to represent the lookup component.  Suggestions welcome.

**Comment by kirlat** [comment]
What if the click on the compact version of a nav bar would open an info panel where are the lookup controls? Then we won't need a toolbar version of a lookup on mobile at all.

**Comment by balmas** [comment]
> What if the click on the compact version of a nav bar would open an info panel where are the lookup controls? Then we won't need a toolbar version of a lookup on mobile at all.

maybe. Although #339 asks from removal of the info tab from the compact panel... Need to think about that some more.

**Comment by kirlat** [comment]
We could add a lookup tab into the panel for the compact toolbar if we remove an info tab. 

Another option might be for the compact toolbar button to display not a panel, but a panel's toolbar at the bottom of the page (then I'm not sure we need a toolbar button itself; we can just make the panel's toolbar always visible). When clicked on the toolbar's icon, the panel will slide out and reveal a corresponding tab.

**Comment by balmas** [comment]
Hmm. Let's talk about this tomorrow.

**Comment by balmas** [comment]
closing this. will enter a separate issue for lookup in mobile.

**Comment by balmas** [comment]
Can be tested in 3.0.0.29 https://github.com/alpheios-project/webextension/tree/qa-3.0.0.29/dist and in Dropbox for Safari

**Comment by monzug** [comment]
it does not work on iPhone 5 but it does on iPhone 6s.

**Comment by balmas** [comment]
I think it's the OS version that is the issue with the iPhone 5. It worked on one where with 12.2 iOS.
