### ISSUE TITLE
Blank panel when activate Alpheios

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#400]
Chrome build 3.0.0.23
activate Alpheios after installing build 3.0.0.23 in Chrome. it does open on a blank panel see screenshot.
I believe it should have the info page open.
I ma not sure if this build is ok for testing, though.
![activate-alpheios-white-panel](https://user-images.githubusercontent.com/41396793/55809634-446b3300-5ab4-11e9-8e53-442916d1bc3e.JPG)

**Comment by monzug** [comment]
Once I got the blank panel with waiting for grammar on the bottom. Could it be that it's waiting to load something?

**Comment by monzug** [comment]
Chrome build 3.0.0.25
![waiting-for-grammar](https://user-images.githubusercontent.com/41396793/55896463-57513680-5b8c-11e9-851e-8a6c9a91be07.JPG)

**Comment by balmas** [comment]
assigning to @kirlat to investigate

**Comment by balmas** [comment]
can be tested in 3.0.0.26 (https://github.com/alpheios-project/webextension/tree/qa-3.0.0.26/dist and Dropbox)

**Comment by monzug** [comment]
tested in chrome build 3.0.0.26
yes, it's fixed, now the help panel pops-up. Thanks
