### ISSUE TITLE
Congratulation message after login

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#402]
Chrome, build 3.0.0.23
in the morphology pop-up, "Congratulation you are logged in successfully" message is displayed for every look-up after login. can we make it a one time message?
Pls discard if this has been already implemented.
see screenshot
![congrats-msg](https://user-images.githubusercontent.com/41396793/55813052-1daffb00-5aba-11e9-9e33-ad596578f44d.JPG)

**Comment by balmas** [comment]
yes, we probably should. Currently you can close it by the little x and then it won't appear again but that isn't really intuitive.

**Comment by balmas** [comment]
in webextension qa-3.0.0.30 and texts-test (embed-lib 1.0.0.6)
(https://github.com/alpheios-project/webextension/tree/qa-3.0.0.30/dist and Dropbox)

**Comment by monzug** [comment]
verified
