### ISSUE TITLE
Waiting for packhum.org when word is invalid

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#403]
tested in Chrome build 3.0.0.23
if I go to word user example for an 'invalid' word and click on get results , the panel hangs there even when the user logged out. 
Not sure if we can do anything about this.
see screenshots
![waiting-for-results](https://user-images.githubusercontent.com/41396793/55815790-e263fb00-5abe-11e9-911b-3186c664f872.JPG)
![invalid-word](https://user-images.githubusercontent.com/41396793/55815795-e859dc00-5abe-11e9-9123-48ecd8685c07.JPG)

**Comment by balmas** [comment]
I think we should be able to fix this. @irina060981 can you take a look?

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
Now I get: there are no results
