### ISSUE TITLE
close toolbar when panel is open

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#405]
In discussions during design review yesterday, we decided that it would be good to close the toolbar nav when the panel is open, so that we don't duplicate the options for navigating the panel on the screen.

**Comment by balmas** [comment]
can be tested in 3.0.0.26 (https://github.com/alpheios-project/webextension/tree/qa-3.0.0.26/dist and Dropbox)

**Comment by monzug** [comment]
yes, I like this!. works as per issue. tested in chrome  build 3.0.0.26
