### ISSUE TITLE
Increase performance by turning on inflections on demand

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/components#408]
@balmas and @kirlat , I am registering the issue as we discussed on the meeting.
For now creating inflections tables (and may be tables for inflection browser too) is the most heaviest  operation because of calculating matches, and also it needs much DOM re-rendering.
But there is no any assurance that every user will user it after every lookup.

May be it would be better to create inflection tables only on opening inflection's tab?

**Comment by balmas** [comment]
@kirlat is there still work to do here for the lookup based inflection tables?

**Comment by kirlat** [comment]
I think they're fine. The first (selected by default) table is created and inserted into the panel in the background while the lexical query is still running and the popup is displayed. The other tables are rendered when a user switches to them using the table selector. I think we should not have any problems with such approach.

**Comment by balmas** [comment]
ok. marking this done then.  @monzug to test with regressions for #586

**Comment by monzug** [comment]
performance has improved, need more time for testing

**Comment by monzug** [comment]
will use as test case for regression
