### ISSUE TITLE
revisit color of toolbar/popup header

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#415]
So far @monzug and @kirlat have noticed some problems with the use of the midnight blue color for the toolbar and popup header:

1. icon is truncated. Recommendation from design firm was to use white instead of black for the lines and no background ciricle. not sure we like the way that looks but will try it.

2. active state in power blue is not noticeable enough, particularly with the more complex icons such as the inflection browser

3. generally feels too strong of a color

We need to revisit this once the design is implemented on the alpheios reader and look at everything together.

**Comment by monzug** [comment]
the credits do not stand out but blend in the morphological output. can we add something next to Credits to stand out (e.g. Alpheios logo)?

**Comment by balmas** [comment]
@monzug and @kirlat what do you think about using the yellow color to indicate the active state of an icon in the panel toolbar rather than powder blue. That's what kirill used in the design for the mobile menu and I think it works better than the powder blue against the midnight background.

**Comment by monzug** [comment]
I like it. keep in mind that orange is also the color on hover

**Comment by balmas** [comment]
@kirlat and @irina060981 suggest using the hover-yellow variant for hover and yellow for active.   Let's go with this for now.   I guess we should probably do the same with the breadcrumb trail in the collections pages of the text environment too. Handing to @irina060981 to implement in both.

**Comment by irina060981** [comment]
I have added hover styles for the texts environment to breadcrumbs.

![image](https://user-images.githubusercontent.com/12377640/57276815-ff074900-70e5-11e9-911b-c7b485d2cff9.png)

**Comment by balmas** [comment]
but active style should be yellow.

**Comment by irina060981** [comment]
Sorry, I misunderstood a little.
this way it should be
    **hover**
![image](https://user-images.githubusercontent.com/12377640/57297035-e14fd900-7111-11e9-9e9c-4c48ec0cb8d6.png)

    **active**
![image](https://user-images.githubusercontent.com/12377640/57297043-e9a81400-7111-11e9-8685-99ed410101cb.png)

ok - will fix

**Comment by irina060981** [comment]
Ok
would be like this
![image](https://user-images.githubusercontent.com/12377640/57299360-af417580-7117-11e9-965c-a622a3f57f95.png)

**Comment by monzug** [comment]
I am a little confused. I thought this change is meant for navigation (breadcrumbs), not for the books titles.

**Comment by irina060981** [comment]
it from this issue
https://github.com/alpheios-project/alpheios_nemo_ui/issues/131#issuecomment-490044532

**Comment by monzug** [comment]
Thanks! catching up... lots of changes but I don't mind. it looks better, I
think.

**Comment by balmas** [comment]
fixed in 3.0.0.33 (webext)/1.0.0.11 (embed-lib) 

The icons should now be yellow when active and the lighter hover-yellow on hover

**Comment by monzug** [comment]
ok. have to say that active style and hover are very very similar. @balmas?
see screenshot
![icon-colors](https://user-images.githubusercontent.com/41396793/57570138-cc529e80-73cc-11e9-87a9-bae74b6f260b.png)
