### ISSUE TITLE
styles bleeding from underlying page

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#416]
@monzug notes style problems when using the extension on https://www.tradurreantico.it/latino/grammatica-latina/morfologia/verbo/verbo-eo-latino/,

login button is truncated
lookup button is too wide

![truncation+lookup](https://user-images.githubusercontent.com/644870/55957452-655a9200-5c34-11e9-9cd5-e35e39b0268b.JPG)

She reports that these are fine on the latinlibrary so it would seem likely to be conflicts with page styles

**Comment by balmas** [comment]
test this with the build at https://github.com/alpheios-project/webextension/tree/qa-3.0.0.27/dist (sorry no Safari build yet)

**Comment by monzug** [comment]
this looks good in Chrome build 3.0.0.28. Thanks
