### ISSUE TITLE
wordlist: filter to current session

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#418]
user story from #304 

As a user I want to be able to view a subset of my word-in-context list that contains just the words I have looked up during the current application session.

**Comment by irina060981** [comment]
Add filter panel to wordlist language panel 
   - filter by current session

![image](https://user-images.githubusercontent.com/12377640/56193657-811ac980-6074-11e9-9f3e-930efdc092c5.png)

![image](https://user-images.githubusercontent.com/12377640/56193668-8841d780-6074-11e9-860c-c8206e4570f0.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
in 3.0.0.28

**Comment by monzug** [comment]
tested on desktop and mobile. I did enter a super minor issue /alpheios-project/alpheios_nemo_ui/issues/152
