### ISSUE TITLE
wordlist: filter on form/lemma

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#419]
User stories from #304 

As a user I want to be able to view a subset of my word-in-context list that contains just the instances of a specific word form.

As a user I want to be able to view a subset of my word-in-context list that contains just the instances of a specific lemma.

As a user I want to be able to view a subset of my word-in-context list that contains just the instances of a specific form+lemma combination.

**Comment by irina060981** [comment]
@balmas , I have  a question here:
we save words to word-in-context this way:
for example - 
    1) word `apertius` has 2 lemmas - `apertus, aperte`
![image](https://user-images.githubusercontent.com/12377640/56182325-f5457500-6054-11e9-86ac-3a16d5e36a20.png)

    2) word `aperte` has 3 lemmas - `apertus, aperio, aperte`
![image](https://user-images.githubusercontent.com/12377640/56182357-17d78e00-6055-11e9-8efa-0e0ac692d34f.png)

    3) word `apertus` has 2 lemmas - `apertus, aperio` 
![image](https://user-images.githubusercontent.com/12377640/56182398-566d4880-6055-11e9-958e-9e1dd3b2c496.png)

     4) word ` aperio` has 1 lemma - 'aperio`
![image](https://user-images.githubusercontent.com/12377640/56182457-a9df9680-6055-11e9-816c-6b4642c2fb5b.png)

     So finally the wordlist will contain 4 items
![image](https://user-images.githubusercontent.com/12377640/56182510-e7dcba80-6055-11e9-88d9-cd3e5477cd50.png)

Than how should it be filtered:

>just the instances of a specific word form
what are word forms here? we save to remote only lemmas (if I understand right)
Should it have input or a select with forms?

>just the instances of a specific lemma
how much items should I show from the list for `aperio`?
Only 3 items?

>just the instances of a specific form+lemma combination
what does it mean? and how should it be used in the current example?

@balmas, could you print examples how these fiters should work for these 4 words?

**Comment by balmas** [comment]
ok, so I think it's easier than you are anticipating:

1) As a user I want to be able to view a subset of my word-in-context list that contains just the instances of a specific word form.

_example based upon above:_ User enters aperio. Their word list shows only the 4th WordItem where targetWord === aperio (a case-insensitive match would be good though, so both aperio and Aperio work)

2) As a user I want to be able to view a subset of my word-in-context list that contains just the instances of a specific lemma.

_example based upon above:_ User enters apertus. For this we need to use the lemmasList getter on WordItem to show only those WordItems which contain 'apertus' in the lemmasList

3) As a user I want to be able to view a subset of my word-in-context list that contains just the instances of a specific form+lemma combination.

I am not sure this one actually makes sense because we group forms by lemma. So let's drop this one.

**Comment by balmas** [comment]
an additional thought that occurs to me, it might be nice to enable the lemma filter by clicking on the lemma in the display. What do you think @irina060981 and @monzug ?

**Comment by irina060981** [comment]
>an additional thought that occurs to me, it might be nice to enable the lemma filter by clicking on the lemma in the display.

I think that it would be comfortable for the user

**Comment by irina060981** [comment]
filtering by word form and by lemma
    by typing to an input field and by clicking a single lemma
   
![image](https://user-images.githubusercontent.com/12377640/56355778-83b72380-621a-11e9-8722-248ef53029c6.png)

   - by word form (full)
![image](https://user-images.githubusercontent.com/12377640/56355818-a1848880-621a-11e9-90e9-8b99fa1187b2.png)

   - by word form (part)
![image](https://user-images.githubusercontent.com/12377640/56355862-b8c37600-621a-11e9-822f-eb9595ae6773.png)

   - by lemma (full)
![image](https://user-images.githubusercontent.com/12377640/56355901-d1cc2700-621a-11e9-8429-2f9175530e08.png)

    - by lemma (part)
![image](https://user-images.githubusercontent.com/12377640/56355934-e3153380-621a-11e9-845c-e2f1367d7907.png)

for filtering by the session and important - it is enough to select a filter type
for filtering by word form/lemma - you should type to the input and press Enter or click Filter button (go icon)
or simply select a lemma

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
I approved the pull request because the code seems fine. From an implementation perspective, it might be more natural for the user to support wildcards rather than the two separate options (full) or (part). I.e. support fer* or *fer*. Let's see what @monzug thinks though and if we want to do that we can create a separate issue for it because we'll have to decide how to prioritize.

**Comment by balmas** [comment]
this was in build 3.0.0.28

**Comment by monzug** [comment]
form+lemma combination is out.  by clicking on the lemma, it does filter by lemma (full) but only by selecting the first word. clicking on second or third does not produce any result.
e.g. acconsenti is in the wordlist, lemma are consentio, Consens, consentium
if I click on consentium, there is no results on fileter by lemma.
however, if I click on consentio (the first one), the filter by lemma (full) returns acconsenti

**Comment by monzug** [comment]
forgot to comment about the use of wild card. I am ok with this version, it's very intuitive.

**Comment by irina060981** [comment]
>if I click on consentium, there is no results on fileter by lemma

It is because of a small error - will fix

>forgot to comment about the use of wild card. I am ok with this version, it's very intuitive.

part search was rejected here - https://github.com/alpheios-project/components/issues/562

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
can test in texts-beta embed-lib 1.0.0.17

**Comment by monzug** [comment]
verified. Thanks
