### ISSUE TITLE
wordlist: download

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#422]
User story from #304

As a user I want to be able to download the data from any view I can produce of my word-in-context list.

**Comment by balmas** [comment]
After thinking about the options, I think I would like for us to proceed with client-side file creation and download, using the HTML5 anchor element with the download attribute and blobUrl as described here https://blog.logrocket.com/programmatic-file-downloads-in-the-browser-9a5186298d5c/

As for file format, let's go with a simple csv output format for now, with one column per property of the serialized **remote** worditem objects. (I.e. just the data parts that we store on the remotedb. ) 

If we are concerned about file size, we could also exclude the `selector` part of the `context.target` property, so that we download just the source urls for the words and not the text of the surrounding context.   

If it's not too difficult, maybe we could make it an option for the user to choose which fields to download, with the default being just the target word, lemmas, and source urls.

@irina060981 and @kirlat does this sound like a reasonable approach to you?

**Comment by irina060981** [comment]
I think - it is a good way to go if we choose a client-side.
I have created a simple test page - http://fetch-test.irina-sklyarova.ru/
works well in Chrome, Firefox, Safari,
Chrome (Samsung A5)
on ios Chrome (Iphone 7) - it opens the file content and it could be sent through different applications (I didn't find how to save it locally)

**Comment by kirlat** [comment]
What a cool tech! Amazing! I did not know we can do it that simple. Thanks for sharing the article!

I vote for this solution with both of my hands 🙂. It should be simple and easy. Download attribute is supported in majority of modern browsers (https://caniuse.com/#feat=download) and Blobs are even more so (https://caniuse.com/#feat=download). I see no technical obstacles in going ahead with it.

**Comment by balmas** [comment]
thanks both for your feedback. Will assign this one to @irina060981 to implement then.

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
qa-3.0.0.49/components 1.2.12

**Comment by monzug** [comment]
ok. let's start with FF. I did try to download the wordlist from web extension and text env, both as a logged in user or before login. no action when clicking on the download icon.
in Chrome, it worked (logged, not logged in) both in text env and in web ext. in notepad it's just a long string of data. in excel, we have all the data.
on safari (iPhone xr) the file is displayed on screen with the option to send it to message, mail, WhatsApp, add to notes, dropbox etc. I tried mail and it does save the link to blob:https://texts-test.alpheios.....  not sure. on dropbox, it failed to upload the file
also, If I click on the reload icon when in blob:, it gives me an error. see screenshots

![IMG_3799](https://user-images.githubusercontent.com/41396793/62242061-60b71680-b3a8-11e9-8c1b-c1515b2f3f65.PNG)
![IMG_3796](https://user-images.githubusercontent.com/41396793/62242062-60b71680-b3a8-11e9-8169-2881a1d3a046.PNG)
![IMG_3797](https://user-images.githubusercontent.com/41396793/62242063-614fad00-b3a8-11e9-84ed-e7cf96dd516b.PNG)

I think there is too much data in the saved file

**Comment by monzug** [comment]
@balmas, two issues here: 
1) in FF it does not work in my environment 
2) in safari (iPhone xr), not sure how to save the file succesfully

**Comment by irina060981** [comment]
> in FF it does not work in my environment

I will check it

> in safari (iPhone xr), not sure how to save the file succesfully

Yes, I could see the same - and it doesn't properly work on a simple example (I have tested and posted about it before)

**Comment by irina060981** [comment]
After some investigating:
 - to be able to download via js click inside Firfox and Safari on MAC - we need to add the link to the document html tree (done in PR)

 - download attribute for download blob is not properly supported on IOS - that's why it shows blob cotent instead of download, I haven't found the workout for that

**Comment by balmas** [comment]
@irina060981 can we also change the separator on the file to a comma instead of a semicolon? I think it will enable it to be imported more easily into spreadsheet programs (which sometimes require you to specify the separator if it is something other than comma.  Thanks!

**Comment by irina060981** [comment]
> @irina060981 can we also change the separator on the file to a comma instead of a semicolon? I think it will enable it to be imported more easily into spreadsheet programs (which sometimes require you to specify the separator if it is something other than comma. Thanks!

There are some problems with comma.
We already have commas inside lemma-list.

I first used a comma for delimiter, but my excel  didn't parse it properly.
If we want to use comma - we should use it with quotation marks - "

**Comment by balmas** [comment]
LibreOffice doesn't have semicolon as a default. But you're right using a comma is a little more work.

I am on the fence about this.  I think we could leave it as semicolon but we need to add some instruction to the user somewhere.  Maybe we could add a little ? help popup next to the download link which instructs the users what to do with the file, and also advises them to use a browser other than Safari on iOS (for now)? 

According to https://caniuse.com/#feat=download it may work in Safari 13 so I am not inclined to code something special for Safari for this release anyway.

**Comment by irina060981** [comment]
It doesn't work both in Chrome and Safari on IOS for me, as I know they both has the same base on IOS.

I am not sure how to create a help popup - 
for standard popup - we should create an additional component and attach it to body outside alpheios popup and panel - I think it could be not so easy task - because we doesn't have any standard mechanism to show additional popup inside extension.

May be we should add the same UI as for delete all?

**Comment by balmas** [comment]
> May be we should add the same UI as for delete all?

Yes I think that's a good idea

**Comment by balmas** [comment]
> It doesn't work both in Chrome and Safari on IOS for me, as I know they both has the same base on IOS.
> 

Ok. I am still fine with this being a known issue in the release. We can put it in the FAQ.

**Comment by irina060981** [comment]
> >May be we should add the same UI as for delete all?

> Yes I think that's a good idea

Will add this to the current PR

**Comment by balmas** [comment]
qa-3.0.0.51/components 1.2.17

**Comment by monzug** [comment]
I tested on FF and I was able to download the file. Thanks for adding the message.
Just a couple of questions: when downloading the file on FF it does open the Help panel. why? see screenshot


also, the download file isa list of all the saved words, ignoring the limit applied. is this ok?

![help-panel-open](https://user-images.githubusercontent.com/41396793/62470987-9756ad80-b769-11e9-8b92-0feeec13a27d.JPG)

**Comment by balmas** [comment]
oh that's a weird bug with the help panel. I see it too. Will ask @irina060981 to look at it.

About the filters -- I think different users would expect different things and am not sure what is right to do here. For now, I think I'm okay with it ignoring the filters. Are you?

**Comment by monzug** [comment]
absolutely. let's keep track of it for future need. shall we keep this
issue or enter new one?

**Comment by balmas** [comment]
let's enter it as a new one.

**Comment by irina060981** [comment]
> oh that's a weird bug with the help panel. I see it too. Will ask @irina060981 to look at it.

I tried - and I was able reproduce it only on wikipedia via FF - it is very strange!
On http://www.thelatinlibrary.com/ it is not reproducable

**Comment by irina060981** [comment]
And I even couldn't understand how it is rendered
![image](https://user-images.githubusercontent.com/12377640/62510521-9b122f00-b852-11e9-90e7-275091ab37c4.png)

It shows visible info panel and a part of wordlist panel that has display: none

**Comment by irina060981** [comment]
oh it has two panels here

![image](https://user-images.githubusercontent.com/12377640/62510580-dad91680-b852-11e9-8780-27ead0763d7c.png)

**Comment by irina060981** [comment]
As I could see it behaves like that:
click on Download - wait a second and it adds a new panel and opens on the help tab.
 then I could close both panels - open a gain wordlist tab, click download - wait and it will add again panel and even a popup

![image](https://user-images.githubusercontent.com/12377640/62510822-f85ab000-b853-11e9-8639-5d00fec363bb.png)

It is some strange behaviour from the extension code, I think

**Comment by irina060981** [comment]
I think it works this way:

1) when a user clicks on download, the firefox browser reloads the page and then open download dialog (or starts download directly)

2) this reload doesn't have all events that has reload page action, that's why
    from one side - it reactivates uiController and all modules - that's why it adds new instance of all modules and divs to the body 
     from the other side it doesn't have an event of removing existed components (as when we simply reloads)

I tried to define on activating that modules are already created but failed - it sees only divs inside body
I am not quite sure, but it seems to me that on this reload the extension looses the bunch uiController + modules inside Vuex and creates another one. And these both bunches could work in paralell (and even more than one)

For now I have no idea how to fix it

**Comment by balmas** [comment]
wow that sounds a little nutty. will look at it and see if I can come up with anything.

**Comment by balmas** [comment]
qa-3.0.0.53/components 1.2.20

**Comment by balmas** [comment]
the fix checks to see if the url being loaded by the browser is a blob: url, and if so it aborts activation of the Alpheios code.

**Comment by monzug** [comment]
the help panel is not longer generated in FF. Thanks

as per mobile (safari and Chrome), are we going to add it as known issues? if yes, shall we keep this one open as a reminder?

**Comment by balmas** [comment]
yes' we're going to add it to known issues. I have tagged it with the faq label, which I will go through when I update the documentation and faq. That is issue alpheios-project/webextension#226 which will now have a reference to this. I think we can close this issue and the need to document will get caught there.

**Comment by monzug** [comment]
yes. I just add the error on chrome on mobile
![IMG_3848](https://user-images.githubusercontent.com/41396793/62634190-71fda700-b903-11e9-9d54-6347b5075053.PNG)

**Comment by irina060981** [comment]
> yes. I just add the error on chrome on mobile

It is not reproducable on my Samsung A5 + Chrome - it downloads correct

I believe that this dowload blob workflow is not supported on all mobile platforms
