### ISSUE TITLE
Important status color does not stand out with background color

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#424]
maybe it's my vision but the light blue on the orange background makes difficult to read the important word in wordlist. see screenshot
![important-word](https://user-images.githubusercontent.com/41396793/55970092-ed4c9600-5c4c-11e9-8620-9acf17afeb1e.JPG)

**Comment by balmas** [comment]
agree. we probably need a different link color here. looking at the style guide, i think maybe we could use powder blue instead of the yellow background to indicate current session and then burnt orange to highlight important? With midnight blue for not-important? what do you think @monzug ?

**Comment by monzug** [comment]
the icon of  current panel is actually powder blue and mouse over is
orange. not important can be gray, right?

did you just change it?

I am experiencing login issue (log in already after deactivating alpheios,
frozen wordlist and blank page when following the show context link), uhm,
better stop here...

**Comment by monzug** [comment]
I did enter issues for above problems

**Comment by balmas** [comment]
#430 may make this moot. holding onto it for now until that issue is resolved.

**Comment by balmas** [comment]
@monzug I think this is no longer relevant. Do you agree?

**Comment by monzug** [comment]
nope!!!!
