### ISSUE TITLE
Logged out when following link in Show contexts

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#427]
tested in Firefox 3.0.0.25
1) not login
double click on few words, then go to word list. verify that it's correctly populated by the look-up words. click on Show contexts on any of the saved words in the list. in the new pop-up, follow the link to the text. see that the new page is reloaded and the word list icon is gone.
2) logged in
proceed as above. Note that on reloading the page, the user is automatically logged out (no user info and no word list).
two things here: could we open a new browser session for the link and keep the previous one with its own status?
also, when I click on Login again, it does automatically log me in.
are all these acceptable behaviors?

**Comment by balmas** [comment]
>could we open a new browser session for the link and keep the previous one with its own status?
I am using #379 to track this request

**Comment by balmas** [comment]
in build 3.0.0.29 you should stay logged in across page loads and tabs.

**Comment by monzug** [comment]
uhm, I can still see issue 1). not logged in, when following the link from Show context, the page opens with blank panel and empty word list. see screenshot
the second part works fine.
![empty-panel](https://user-images.githubusercontent.com/41396793/56746672-ada4a480-674a-11e9-9e6e-a7cc518cf712.JPG)

**Comment by balmas** [comment]
this behaves differently in firefox but in any event I am going to handle 1) by opening links in a new tab via #379
