### ISSUE TITLE
Firefox: sign up takes a long time

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#429]
tested in Firefox 3.0.0.25
I noticed that signing up takes really a long time before displaying the user info panel with the congratulations message.
Also logging in. In both cases, I opt to save id/psw.
![sign-up-firefox](https://user-images.githubusercontent.com/41396793/56040017-82aa6180-5d03-11e9-8b9a-a60de630d77c.JPG)

**Comment by balmas** [comment]
Yep, this is a firefox bug. See alpheios-project/webextension#202. 
I have been tracking it and Firefox just implemented the fix yesterday. It looks like it is targeted for a build of release 68 although I'm not sure what their release schedule is.

**Comment by monzug** [comment]
Thanks!

**Comment by balmas** [comment]
closing as duplicate. Will be tracked through alpheios-project/webextension#202.
