### ISSUE TITLE
Word list: background color changed after logged in again

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#430]
Normally the background color in wordlist is orange. when I logout and login again, the background color is white. confusing

see screenshot
![background color word list](https://user-images.githubusercontent.com/41396793/56040957-9656c780-5d05-11e9-9d22-99336b2e3d4e.JPG)

**Comment by balmas** [comment]
Ah, this is because we use background color to indicate if a word was looked up in the current "session" (see also my comments on #424). 

Maybe we should not use the background color for this if it is confusing.  What do you think might be better?

**Comment by monzug** [comment]
got it. I missed this or didn't understand. Can we keep this item as  info?
how does the user know about this? would it be a new flag, next to the
word, easier to understand? not sure

**Comment by monzug** [comment]
![two-colors](https://user-images.githubusercontent.com/41396793/56043429-43800e80-5d0b-11e9-891f-bf561b2acd90.JPG)

**Comment by balmas** [comment]
@irina060981 can you try another design approach for indication the words from the current session? Maybe a little icon like this? https://material.io/tools/icons/?icon=new_releases&style=baseline

**Comment by irina060981** [comment]
I have corrected a little the icon (increased exclamation mark).
And now it looks like this
![image](https://user-images.githubusercontent.com/12377640/56072451-5d3c5700-5dda-11e9-91d4-4577173be32c.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
@monzug you can test this with the build at https://github.com/alpheios-project/webextension/tree/qa-3.0.0.27/dist (sorry no Safari build yet)

**Comment by monzug** [comment]
tested in Chrome build 3.0.0.28 - like the little icon next to the new word, tooltip says 'added in the current session'
