### ISSUE TITLE
logged in already after deactivating alpheios

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#433]
Both Chrome and Firefox 3.0.0.25
if I click on Deactivate Alpheios, all icons are closed (this was an issue on GitHub) but when I reactivate Alpheios, panel is open with the blank page, Wordlist and login are still active from previous session. Shouldn't the command deactivate Alpheios close all actions including wordlist and logout?

**Comment by balmas** [comment]
yes i think it should.

**Comment by balmas** [comment]
actually, I'm not sure if deactivating Alpheios *should* log you out.   I just implemented a fix for #409 which will fixes the problem of not retaining the session across page loads (and will also allow the session to be used across tabs).  The user login has an expiration which is enforced so the session does not last indefinitely (although we could also refresh the session for the user if we want -- see alpheios-project/webextension#213). 

I am leaning towards keeping the session active until it times out, the user explicitly logs out, or they close their browser. What do you think @monzug ? what is the benefit of logging out upon deactivation?

**Comment by monzug** [comment]
I have seen this issue few times today (build 3.0.0.29), always doing the following:
1) logged out
2) deactivating alpheios, activating alpheios
3) the wordlist is the last username's wordlist
and  I see this
![logged-out-uhm](https://user-images.githubusercontent.com/41396793/56750455-d1b7b400-6751-11e9-90de-7f5d2aa3dd91.JPG)
when I click on Logged out button, then the Log in button is generated and then username no longer shows up.

if we have multiple users on same computer, I want to be sure to logged out completely. that's why I am also deactivating Alpheios as an extra step. there is something not quite right here.

**Comment by balmas** [comment]
I think this one is fixed now.

**Comment by balmas** [comment]
I think the weird behavior on logging out was fixed, so back to this comment:

> I am leaning towards keeping the session active until it times out, the user explicitly logs out, or they close their browser. What do you think @monzug ? what is the benefit of logging out upon deactivation?

**Comment by monzug** [comment]
Yesterday I installed new build and I found myself already logged in. Note that before uninstalling the tools, I do clear data. Usually when I log out and then I log in again, I am prompt to enter id/psw. Sometimes, I get in without prompting for id/psw.

**Comment by balmas** [comment]
Yes, It's a session cookie added by the Auth0 application.

**Comment by monzug** [comment]
ok so we can close this one. Thanks
