### ISSUE TITLE
Frozen wordlist in Chrome and Firefox

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#434]
build 3.0.0.25
I experienced frozen wordlist several times both in Chrome and Firefox. I haven't figured out yet when is happening, so I do not have a reproducible scenario. need to reload page to go back to normal activity. this is to keep track of this potential issue.

**Comment by irina060981** [comment]
I think, I was able to reproduce this bug (occasionally).
The problem was in caching wordlists inside reactive computed properties.
Added check by updateTime.

Now I couldn't reproduce the bug - so hope - it is fixed here!

https://github.com/alpheios-project/components/pull/438

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
worked with wordlist quite a bit lately and I haven't experienced this issue anymore.
chrome build 3.0.0.26, 27 and 28
