### ISSUE TITLE
display the wordlist delete confirmation message in same style as login messages

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#436]
forgot to ask, can we display the message in same style as login messages? if this is out of scope, pls disregard.

_Originally posted by @monzug in https://github.com/alpheios-project/components/issues/363#issuecomment-482204365_

**Comment by irina060981** [comment]
Changed design according to the issue

![image](https://user-images.githubusercontent.com/12377640/56171634-5eaf8e80-6029-11e9-9734-8a8f3ddaf230.png)

**Comment by monzug** [comment]
Thanks!

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
@monzug you can test this with the build at https://github.com/alpheios-project/webextension/tree/qa-3.0.0.27/dist (sorry no Safari build yet)

**Comment by irina060981** [comment]
This changes are disappeared from the current master branch
now both - delete confirmation message look like there were no changes at all
and login message is changed too

**Comment by irina060981** [comment]
Merged and closed again

**Comment by monzug** [comment]
tested in Chrome build 3.0.0.28
