### ISSUE TITLE
add the ability to select the language in the lookup component

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#44]
we should add the ability for the user to select from available languages before submitting a request in the lookup component. It should default to whatever the current language is but the user should be able to override that.

**Comment by irina060981** [comment]
Added Language Settings link to lookup component
![image](https://user-images.githubusercontent.com/12377640/40044243-2ed1d4f6-586a-11e8-9cf1-1f0bde4caa0f.png)
![image](https://user-images.githubusercontent.com/12377640/40044258-39309b58-586a-11e8-805c-554dc17f3aed.png)

**Comment by irina060981** [comment]
Added to reskin-color-font branch
#42

**Comment by balmas** [comment]
See comments in #46 and PR
