### ISSUE TITLE
auth0 setup for Google doesn't allow use of multiple google accounts

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#444]
Noticed by @irina060981  --- we should be able to choose from different google accounts when logging in but the option isn't presented. Need to see if/how to enable this in the Auth0 setup.

**Comment by balmas** [comment]
solution may be here https://community.auth0.com/t/change-and-see-google-account-when-login/7132

**Comment by balmas** [comment]
Can be tested in 3.0.0.29 https://github.com/alpheios-project/webextension/tree/qa-3.0.0.29/dist and in Dropbox for Safari

**Comment by monzug** [comment]
login using the google account it does give the option to choose other accounts. tested in Chrome and firefox and Safari in text env.
