### ISSUE TITLE
wordlist does not get updated after login

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#449]
tested in Chrome build 3.0.0.27
There is a problem with login and wordlist. I did install new build and lookup a word then follow the login link from the morphology pop-up. Check wordlist which correctly has the one word listed. the double click on few other words, none of them get listed in wordlist. 
![word-list-does-ot-get-updated](https://user-images.githubusercontent.com/41396793/56307052-01dbd300-6112-11e9-9bb3-f7dacecb40e0.JPG)

**Comment by balmas** [comment]
@monzug can you confirm this is fixed in 3.0.0.28?

**Comment by monzug** [comment]
I haven't been able to reproduce this in 3.0.0.28 yet. let's keep it assign to me and I'll test if this scenario is reproducible in future builds.

**Comment by monzug** [comment]
tested also on mac 1.0.0.11
