### ISSUE TITLE
make wordlist filter case-insensitive

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#453]
Missed this in the code review. See comment at 
https://github.com/alpheios-project/components/pull/452#pullrequestreview-228245798

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
Can be tested in 3.0.0.29 https://github.com/alpheios-project/webextension/tree/qa-3.0.0.29/dist and in Dropbox for Safari

**Comment by monzug** [comment]
verified
