### ISSUE TITLE
Messages not visible with the gray background in build 3.0.0.28

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#455]
the background color does not match with the message's color as the latest is barely visible. see screenshot
Bridget has also noticed that the links in the popup are the wrong color too.
![background-color-not-visible](https://user-images.githubusercontent.com/41396793/56362708-86812c80-61b8-11e9-9ca0-35205b27b48e.JPG)

**Comment by balmas** [comment]
Can be tested in 3.0.0.29 https://github.com/alpheios-project/webextension/tree/qa-3.0.0.29/dist and in Dropbox for Safari

**Comment by monzug** [comment]
Looks good in 3.0.0.29
