### ISSUE TITLE
usage examples button should appear in popup if usage examples are enabled

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#467]
we switched the default behavior of the usage examples to "On Demand", which means that the Examples button does not appear in the popup anymore. I would like it to appear in the popup if the feature is enabled, changing the prior behavior of it only appearing if the examples data had been retrieved.

**Comment by balmas** [comment]
in webextension qa-3.0.0.30 and texts-test (embed-lib 1.0.0.6)
(https://github.com/alpheios-project/webextension/tree/qa-3.0.0.30/dist and Dropbox)

**Comment by monzug** [comment]
it's missing from mobile. Tested in text environment 1.0.0.7 on Samsung 5

**Comment by balmas** [comment]
it is there in mobile, in the menu, but it is at the very end. It should be moved higher up with the other word-specific options.

**Comment by monzug** [comment]
question on the examples option: how do we store it? is it user related? I logged in in Chrome as user sabato and the examples option is checked so I have the Examples button in pop-up. in Firefox, the examples option is not checked so I don't have the Examples button in pop-up but this is same user.
an other example: I am not log in but previous user had example option checked in Options, so I have examples button available.  I am ok with this but I want to understand how this option gets stored. see screenshot
![logout-examples](https://user-images.githubusercontent.com/41396793/57461240-a7332400-7244-11e9-8d9d-db075874f77f.JPG)

**Comment by balmas** [comment]
we aren't yet storing settings with the user data. We NEED to, and will do this before the full release, but not the beta.  I thought I had an issue for it, but can't find it, so will definitely add one.

**Comment by monzug** [comment]
will enter one then.

**Comment by balmas** [comment]
beat you too it :-) #522

**Comment by monzug** [comment]
ok. will delete mine

**Comment by balmas** [comment]
can we close this again now @monzug ?
