### ISSUE TITLE
replace grammar icon

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#470]
we'd like to replace the grammar icon with a version of one of the icons we had been considering for usage examples, the open book, without the "e.g." text.  The svg for this icon is currently atsrc/images/inline-icons/usage-examples-icon2.svg.

We should rename it to replace the resources.svg icon, and remove the "e.g." characters from it.

**Comment by irina060981** [comment]
![image](https://user-images.githubusercontent.com/12377640/56775996-2704cb80-680d-11e9-88d5-a7b2d84c359d.png)

Merged and closed

**Comment by balmas** [comment]
in webextension qa-3.0.0.30 and texts-text (embed-lib 1.0.0.6)
(https://github.com/alpheios-project/webextension/tree/qa-3.0.0.30/dist and Dropbox)

**Comment by monzug** [comment]
verified in 3.0.0.30 and 1.0.0.6
