### ISSUE TITLE
Lookup fails for words that do not belong to current site

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#473]
tested in Firefox and Chrome, build 3.0.0.29
in the saved wordlist I have a mix of words from different sites. If I double-click on any of the saved words that do not belong to current site, the lookup fails with Lexical query produced no results.
![no result for look-up words that do not belog to that site](https://user-images.githubusercontent.com/41396793/56748026-15f48580-674d-11e9-9f4c-200b6d9388a0.JPG)

**Comment by balmas** [comment]
not sure if this fix ever got tested

**Comment by monzug** [comment]
no longer reproducible in build 3.0.0.37
tested in site nihiliscio with wordlist from user test@test.it
lookup for venit (and other words) works fine
