### ISSUE TITLE
Question: clicking on wordlist when is not active but grayed out, takes to a blank panel

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#481]
tested in text environment and tools.
if I logged out, the wordlist icon is grayed out but still selectable. if I click on it, it will open a blank panel.
in the text environment, it will open the same blank page with no user info icon. 

![show-contexts](https://user-images.githubusercontent.com/41396793/56810839-44ce3280-6805-11e9-89a1-2ddd16cdc6d7.JPG)

two questions here:
1) why is the user able to click on a gray icon?
2) it seems that the login/logout process is different in text environment from tools. the user info icon is never grayed out in tools but it's in text environment

**Comment by monzug** [comment]
![tools-emptywordlist](https://user-images.githubusercontent.com/41396793/56811346-7dbad700-6806-11e9-8d1a-9c6dc0a2b4b6.JPG)

**Comment by balmas** [comment]
sounds like some state errors . will investigate.

**Comment by monzug** [comment]
still reproducible in 3.0.0.30

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
I think this should be fixed in the current build (3.0.0.37/1.0.0.16)

**Comment by monzug** [comment]
not longer reproducible in 1.0.0.16 and 3.0.0.37 (firefox and Crome)
