### ISSUE TITLE
add ability to reset user options to defaults

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#488]
We probably should offer a reset all (or groups of, or individual ) user options to defaults. 

Can wait for settings refactoring.

**Comment by balmas** [comment]
depends on #522

**Comment by balmas** [comment]
this is fully fixed with changes for #522

**Comment by balmas** [comment]
webextension qa-3.0.0.45/Safari3.0.0.45)/embed-lib 1.0.0.27 

Reset All should now take immediate effect.

**Comment by monzug** [comment]
after using the Reset all button, the Options panel is missing the style, both in Chrome and FF.
on iPhone xr, I am not able to click on Reset all, it just bounce back up.
see screenshot

![missing-tags](https://user-images.githubusercontent.com/41396793/61080902-0bfd2d00-a3f4-11e9-8cf2-79885a949291.JPG)

**Comment by balmas** [comment]
hmm. you're right. I can reproduce but I thought I had fixed that :-( will take it back.

**Comment by balmas** [comment]
in qa-3.0.0.47/components 1.2.6

**Comment by monzug** [comment]
verified in 3.0.0.48
