### ISSUE TITLE
drag toolbar off screen, cannot get it back in Firefox

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#489]
it shouldn't be possible to drag the overlay toolbar offscreen (#472) but if you do, it should be possible to get it back. On firefox, once dragged off screen, it doesn't come back, even after clearing the browser settings and reinstalling.

**Comment by balmas** [comment]
@monzug you should be able to fix this using build 3.0.0.31. I included in that a button at the bottom of the options panel that will reset all the settings to their default value. it's a temporary hack of a solution because it doesn't refresh the panel with the reset settings. it pops up an alert that tells you to shut down your browser for the change to take effect.  We need to refactor the way the settings work, storing user settings on a server, so the full fix needs to wait for that, but hopefully this will at least get you working in Firefox again.

**Comment by monzug** [comment]
have back my beautiful overlay in firefox. Thanks!!!!!!
