### ISSUE TITLE
options panel scrunched on iPhone 6x

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#495]
reported by @monzug 
![IMG_3428](https://user-images.githubusercontent.com/644870/57099545-ae10e280-6cea-11e9-9f7e-23f95f3b8928.JPG)

**Comment by monzug** [comment]
also check the icons. the same icon is used for User info, options and
grammat (not sure) - tested on iPhone 6s

**Comment by balmas** [comment]
@kirlat @monzug says that the options are unusable on the iPhone XR...

**Comment by kirlat** [comment]
Thanks for the update, I will work on it tomorrow.

**Comment by monzug** [comment]
![IMG_3443 (1)](https://user-images.githubusercontent.com/41396793/57476174-00f71680-7264-11e9-9083-9e3e56be43f2.PNG)

**Comment by balmas** [comment]
in 3.0.0.34/1.0.0.12

**Comment by monzug** [comment]
tested on iPhone 6 and xr, options panel look good (build 1.0.0.12)
