### ISSUE TITLE
Mobile: wrong word in lookup does not produce any error message

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#498]
tested in 1.0.0.7 on iPhone 6s. I enter a word such as fyhd in the "new" lookup and got an empty morphology pop-up. in the alpheios tool and text environment on desktop I get the "lexical query produced no results" message and then the word itself with no definition and the credits on the bottom.

**Comment by balmas** [comment]
can be tested in 1.0.0.9

**Comment by monzug** [comment]
tested in 1.0.0.9 on Samsung 5s. verified
