### ISSUE TITLE
fix the order of the buttons in the popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#50]
requested by @abrasax the order of the buttons in the popup should be:
Define
Inflect
Diagram 
Options

**Comment by irina060981** [comment]
Waiting for be able to work on a branch merged with lookup-reskin

**Comment by irina060981** [comment]
Waiting for be able to work on a branch merged with lookup-reskin

**Comment by irina060981** [comment]
Solved - https://github.com/alpheios-project/components/pull/94

**Comment by irina060981** [comment]
Merged to master
