### ISSUE TITLE
Best way to identify if no lexical data is found

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/components#502]
Currently, to check if the word has any morph data on it, we rely on the presence of the Lexeme object in the client data adapter output. If the Lexeme object is there, we check either it has principal parts, inflections, full or short definitions.

Currently it fails, because for an unknown word (Latin at least) there is always a full definitions object with the following text returned:
 `"<div xmlns:alph="http://alpheios.net/namespaces/tei" xmlns:dctype="http://purl.org/dc/dcmitype/" xmlns:tufts="http://www.tufts.edu/" xmlns:perseus="http://www.perseus.org/meta/perseus.rdfs#" class="alpheios-lex-text_container en">     <div class="alpheios-lex-error">No entries found</div> <div class="alpheios-lex-footnotes en"> </div> </div>"`
and it is counted as the results found.

What would be the best way to detect if no results are found? Shall the client adapter's source specific driver search for "No entries found" in the output? Can we use any other fields in the response of the remote source to identify an empty response? What do you think?

**Comment by balmas** [comment]
added check on an error return from the lexicon service, and passing that back as an error

**Comment by balmas** [comment]
qa-3.0.0.49/components 1.2.12

**Comment by monzug** [comment]
question on mobile: we do not show the word in the error panel but we do on desktop - see screenshot

![IMG_3843](https://user-images.githubusercontent.com/41396793/62478737-d2f97380-b779-11e9-929d-2edf003b78b7.PNG)

**Comment by balmas** [comment]
hmm. I think maybe that was to conserve space.  But maybe it should be there on mobile for consistency.

**Comment by balmas** [comment]
what do you think? Is it worth the space? 
![AwesomeScreenshot-127-0-0-1-demo-auth html-2019-08-05_2_53 (1)](https://user-images.githubusercontent.com/644870/62487876-ee23ad80-b790-11e9-9187-3cf53bee8d60.png)
![AwesomeScreenshot-127-0-0-1-demo-auth html-2019-08-05_2_53](https://user-images.githubusercontent.com/644870/62487878-f11e9e00-b790-11e9-91de-351c6cd77e2f.png)

**Comment by monzug** [comment]
considering the emphasis that recently we have put on sync mobile and desktop, what do you think? I am ok as is

**Comment by balmas** [comment]
let's leave it as-is then.  in my opinion, space limitations beat out consistency here.
