### ISSUE TITLE
remove titles in compact panel on mobile

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#505]
the word usage examples tab title is too long on a small device. Let's truncate this to just examples on mobile.

**Comment by balmas** [comment]
hmm. same is true for the other tabs such as "Browse Grammar" "Browse Inflection Tables"

Not sure about the wisdom of the design here. Ideas?

**Comment by balmas** [comment]
@abrasax and I discussed this today and we would just like to drop the titles from the compact panel, and move the zoom icon over to the right, just next to the close button (to the left of the close button)

**Comment by kirlat** [comment]
Will do that, was thinking about this problem too. The other option could be to use `text-overflow: ellipsis;` to cut the text so that it will always fit the header.

**Comment by monzug** [comment]
also the Browse Inflection tables is too long and it's truncated on Samsung 5s

**Comment by balmas** [comment]
this is in 1.0.0.10

**Comment by monzug** [comment]
Verified no more titles on mobile 1.0.0.11
