### ISSUE TITLE
Style for Show/Hide links in Credits (morphology pop-up)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#511]
Moved out from issue #496 
Please make the Show/Hide link in Credits in the morphology pop-up in orange (alpheios-color-vivid) .
as per Harry's request, all links in the morphology pop-up should be changed
 to the turquoise color (alpheios-color-muted). As I mentioned before, I think Credits blend in the text, so orange would make it more noticeable.

**Comment by irina060981** [comment]
Fixed and it looks like this
![image](https://user-images.githubusercontent.com/12377640/57429185-9eefde80-726e-11e9-97ce-8e57e06482b3.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
fixed in build 3.0.0.33 (webext)/1.0.0.11 (embedlib)

**Comment by balmas** [comment]
but see #527 which is interfering with this change in our texts environment

**Comment by monzug** [comment]
tested in Chrome and Firefox in build 3.0.0.33
in 1.0.0.11 unfortunately not per issue 527.
