### ISSUE TITLE
Uppercase default in lookup (mobile only)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#512]
when entering a word in lookup, first letter is uppercase by default. Is there a way to make the entry field lower case by default?

**Comment by kirlat** [comment]
There is a fix ready for this, it's packaged with a #514 and is waiting on it (but I will PR it separately if #514 be delayed).

**Comment by balmas** [comment]
in 3.0.0.34 and 1.0.0.12

**Comment by monzug** [comment]
tested on mobile (iPhone xr and Samsung 5 mini)
