### ISSUE TITLE
lookup from Definitions does not work (mobile only)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#513]
tested in 1.0.0.10 on Samsung 5s
from the morphology pop-up, select Definitions from the Tools menu. enter fero from world lookup. Note that it takes back to an empty morphology pop-up

it work from Help panel. it's just from Definitions.

**Comment by kirlat** [comment]
A fix for this is in eccf3d3e7948de0ca1bd757b80aa4c0466cc8143.

**Comment by balmas** [comment]
ready for testing in 3.0.0.33/1.0.0.11

**Comment by monzug** [comment]
yes, tested in Samsung 5s and iPhone xr build 1.0.0.11
