### ISSUE TITLE
use new reading tools icon

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#515]
the new reading tools icon can be found in the design-guidelines repo in v3/Icons/SVGs

![reading tools icn var](https://user-images.githubusercontent.com/644870/57388110-8eb00480-7185-11e9-8092-cd8e8f618cb9.png)

We would like to use this
(1) in place of the alpheios logo in toolbar-large.vue AND make it clickable there to expand and close the menu (not sure if we still want to keep the arrow also to expand or close need to see how it looks)
(2) in place of the open book icon in the toolbar-compact.vue
(3) in place of the open book icon in the panel-compact.vue (to open tools menu)

**Comment by kirlat** [comment]
This is how the new icons looks when put into the current layout of the large toolbar (a):
![image](https://user-images.githubusercontent.com/18631055/57474740-d88f0c80-72a3-11e9-9017-d565ec9e1c06.png)

We can also place an arrow into the same background, near the new icon (b):
![image](https://user-images.githubusercontent.com/18631055/57475075-a7630c00-72a4-11e9-8399-1cc4a37f1d14.png)

Or we can remove the arrow altogether (c):
![image](https://user-images.githubusercontent.com/18631055/57475205-e5603000-72a4-11e9-9ea0-a7fe644b5f23.png)

I probably like (b) the most: it makes sense to have an arrow there to indicate that an icon works as a toggle. Yet it's more compact that (a). What is your opinion on that?

**Comment by kirlat** [comment]
We can even maybe get rid of the icon on the top of the bar since we have a logo on an icon (d):
![image](https://user-images.githubusercontent.com/18631055/57475699-e5acfb00-72a5-11e9-93bd-8fc2e7897d5f.png)
This is the most compact variant and I like it too

**Comment by balmas** [comment]
> We can even maybe get rid of the icon on the top of the bar since we have a logo on an icon (d):
> ![image](https://user-images.githubusercontent.com/18631055/57475699-e5acfb00-72a5-11e9-93bd-8fc2e7897d5f.png)
> This is the most compact variant and I like it too

I think this one is best.

**Comment by balmas** [comment]
in 3.0.0.34 (https://github.com/alpheios-project/webextension/tree/qa-3.0.0.34/dist) and 1.0.0.12

**Comment by monzug** [comment]
I like it!!!! thanks.
verified on mobile and desktop

**Comment by balmas** [comment]
:-( problem with the display in Safari on the mac:

![Image 5-13-19 at 4 09 PM](https://user-images.githubusercontent.com/644870/57652234-1c805b00-759d-11e9-9b7f-02a35bd5e80f.jpg)

**Comment by monzug** [comment]
it did happen to me, initially but then I reboot. the icon looks good. the
only thing I noticed is that I can drop the icon outside the screen and not
able to bring back. I had to use the Reset all option.
see screenshot

**Comment by monzug** [comment]
![Screen Shot 2019-05-14 at 7 55 01 AM](https://user-images.githubusercontent.com/41396793/57673975-d6061d00-75eb-11e9-8901-ebaefcd7658f.png)

**Comment by monzug** [comment]
Mac only. if the cursor is on the little arrow (to expand or collapse), the reading tool can flash and then disappears. see screenshot
![Screen Shot 2019-05-14 at 8 10 29 AM](https://user-images.githubusercontent.com/41396793/57674601-ff40a080-761f-11e9-958c-bf941923dd5b.png)

**Comment by balmas** [comment]
I doubt that the flashing is related to the reset all option. 

Re the display on the mac --- I see that it's the version of the extension I have installed interfering with the display.  Still a little worried about this but I am hopeful it won't be a real world issue.

**Comment by balmas** [comment]
@monzug does the flashing happen no matter where on the screen you have dragged the icon?

**Comment by monzug** [comment]
Re display on the mac: I did also try on Emma's mac with no previous alpheios build and the icon looked ok. the interference with the webextension should not be a user problem. I have a build 3.0.0.33, we should try with a webextension that is at the same level as 1.0.0.12


as per the flashing, I did move the overlay around. it does happen in any location.

**Comment by balmas** [comment]
> Re display on the mac: I did also try on Emma's mac with no previous alpheios build and the icon looked ok. the interference with the webextension should not be a user problem. I have a build 3.0.0.33, we should try with a webextension that is at the same level as 1.0.0.12
> 
> as per the flashing, I did move the overlay around. it does happen in any location.

Ok, I'll make a new issue for the flashing.
