### ISSUE TITLE
always show prompt for login unless user disables it

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#519]
>I was a little annoyed to see appearing and disappearing this message before figuring out that it depended on the number of words in the wordlist. I am ok with it but I would rather prefer if this can be a permanent message. Users can get easily concerned about messages that appear and disappear (if they do not have control on the frequency).

Ok, this is helpful feedback. I can change this so that it always appears, but I think I also need to add the ability for the user to say never show this again.

_Originally posted by @balmas in https://github.com/alpheios-project/components/issues/317#issuecomment-480850081_

**Comment by balmas** [comment]
in qa-3.0.0.46 and embed-lib 1.0.0.28 (with components 1.2.2)

**Comment by monzug** [comment]
Login does always appear now. the don't ask button shows up after the 3rd lookup. when selected the prompt for login is disabled.
