### ISSUE TITLE
add short definition lexicon preferences to options panel

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#53]
allow the user to set the short definition lexicon preferences via the options panel

**Comment by balmas** [comment]
There are 2 sets of options for Lexicons in the language-options-defaults:
lexicons and lexiconsShort

In panel.vue , we offer the user the option to change lexicons but not lexiconsShort

```
              <setting :data="languageSetting" @change="resourceSettingChanged" :classes="['alpheios-panel__options-item']"
                  :key="languageSetting.name" 
                  v-if="languageSetting.values.length > 1 && data.resourceSettings"
                  v-for="languageSetting in data.resourceSettings.lexicons"></setting>
```

We currently use the correct setting when we issue the lexical query (lexical-query.js)

```
    let lexiconFullOpts = this.getLexiconOptions('lexicons')
    let lexiconShortOpts = this.getLexiconOptions('lexiconsShort')
```

So we need to add the ability to change the lexiconsShort preferences in the panel.vue:

```
              <setting :data="languageSetting" @change="resourceSettingChanged" :classes="['alpheios-panel__options-item']"
                  :key="languageSetting.name" 
                  v-if="languageSetting.values.length > 1 && data.resourceSettings"
                  v-for="languageSetting in data.resourceSettings.lexiconsShort"></setting>
```

**Comment by irina060981** [comment]
Created - https://github.com/alpheios-project/components/pull/140

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
verified

**Comment by irina060981** [comment]
The problem was in cloning all resource options on lookup component creation.
So when option for full definition changes - it doesn't reflect cloned copy in lookup.
I have added update operation before LexicalQueryLookup.

Fixed
https://github.com/alpheios-project/components/pull/185

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
tested in Firefox build 2.0.3-6
looks good. Thanks for fixing it
