### ISSUE TITLE
full definitions are being repeated in the definitions panel

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#530]
the definitions are being repeated

<img width="684" alt="Screen Shot 2019-05-09 at 5 02 05 PM" src="https://user-images.githubusercontent.com/644870/57526651-f0927a80-72fb-11e9-8979-c7ebd120062d.png">

reported by @abrasax

**Comment by irina060981** [comment]
It was printed twice in panel

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
in qa-3.0.0.35/1.0.0.13

**Comment by monzug** [comment]
ἀρρενικός   now returns only one entry in define

I found an other  word:  πρέπουσα  that  is repeated twice in define, from passage http://texts-beta.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg006.alpheios-text-grc1/passage/1-30
in lookup, this word is a verb and verb participle with two different endings but same meaning, so maybe it's repeated for each entry. This might be a situation in which we should consolidate the result like we did with latin, what do you think @balmas?

**Comment by balmas** [comment]
> This might be a situation in which we should consolidate the result like we did with latin, what do you think @balmas?

We can look into it. I have added it as alpheios-project/client-adapters#17

**Comment by monzug** [comment]
Thanks
