### ISSUE TITLE
Examples icon non displayed when diagram is enabled

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#534]
tested in build 1.0.0.11 (desktop and mobile)
have a user with word usage examples on. go to  Libation Bearers - Aeschylus  and lookup for λεύσσω. Note that panel and menu will have the icon for Diagram and not for Word Usage Examples. I believe this is by design, pls confirm.

**Comment by balmas** [comment]
the examples icon is not displayed because it's greek texts not latin. It's not related to the diagrams.

**Comment by monzug** [comment]
yes, perfect.
