### ISSUE TITLE
Firefox: yellow message on loading diagram

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#537]
Firefox, build 1.0.0.11
double click on αὐτοὺς  in  http://texts-beta.alpheios.net/text/urn:cts:greekLit:tlg0012.tlg001.alpheios-text-grc1/passage/1.1-1.30
and click on Diagram. the yellow message is generating on top of the page. Diagram panel opens up, but then I am not longer able to do any lookup (sort of freeze)
see screenshot
![yellow-message-diagram](https://user-images.githubusercontent.com/41396793/57622099-e5895580-755a-11e9-85da-86783c6426ee.JPG)

**Comment by balmas** [comment]
I think this is the exact same issue as in #639 so closing this in favor of that item
