### ISSUE TITLE
Mobile: loading issue after lookup of word from user word list 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#538]
on iPhone xr and Samsung 5mini, in texts beta environment.
to repro: go to user word list and double click on any saved word on the list. the related morphology pop-up opens up. if you close the pop-up then click on the overlay (sometimes you don't even need to click on the overlay) the world lookup pop-up keeps loading.
![IMG_3446](https://user-images.githubusercontent.com/41396793/57583537-363b7880-749f-11e9-9029-dc1bb6c03dae.PNG)

**Comment by irina060981** [comment]
Fixed condition for progressbar in action panel (make it the same as in other places with progress bar)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
test in texts-beta
embed-lib 1.0.0.16
webext 3.0.0.37

**Comment by monzug** [comment]
could not reproduce the above scenario, also we don't have the overlay anymore. Fixed. Thanks!
