### ISSUE TITLE
credits link: drop hide/show links

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#544]
@abrasax has requested that we drop the hide/show links for the Credits on the popup and instead just link the word "Credits" itself as the toggle again

**Comment by balmas** [comment]
ready for testing in 3.0.0.35/1.0.13

**Comment by monzug** [comment]
tested in chrome, firefox and safari.
on mobile (Samsung, iPhone), we still have the Credits show/hide - shall we make this change also on mobile?

**Comment by balmas** [comment]
oops yes, will fix. thanks.

**Comment by monzug** [comment]
btw, credits link does not work when lookup for a non existing word, such as pulcherra in chrome and firefox

**Comment by balmas** [comment]
can test in texts-beta environment with 1.0.0.14 . Webextension build not done yet.

**Comment by balmas** [comment]
webextension 3.0.0.36 is now available too https://github.com/alpheios-project/webextension/tree/qa-3.0.0.36/dist

**Comment by monzug** [comment]
tested on iPhone Samsung, safari, chrome and firefox. done!
