### ISSUE TITLE
turn usage examples on by default (beta only)

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#546]
for simplicity for the beta let's turn the usage examples on by default

**Comment by irina060981** [comment]
Hope, I understood you right.
I have set two settings:
   - `enableWordUsageExamples` to `true`
   - `wordUsageExamplesON` to `onLexicalQuery`

So now after each word select - the tab with examples has results
![image](https://user-images.githubusercontent.com/12377640/57696343-ee317700-7693-11e9-8ae1-fdf854a02de1.png)

**Comment by irina060981** [comment]
Changed - only setting
`enableWordUsageExamples` to `true`

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
in 3.0.0.35/1.0.0.13

**Comment by monzug** [comment]
verified
