### ISSUE TITLE
flashing of reading tools icon in overlay toolbar (mac only)

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#555]
Mac only. if the cursor is on the little arrow (to expand or collapse), the reading tool can flash and then disappears. it is always visible when expanded. Could it be related to Reset all option?
see screenshot
![Screen Shot 2019-05-14 at 8 10 29 AM](https://user-images.githubusercontent.com/41396793/57674601-ff40a080-761f-11e9-958c-bf941923dd5b.png)

_Originally posted by @monzug in https://github.com/alpheios-project/components/issues/515#issuecomment-492093497_

**Comment by kirlat** [comment]
Does this happen in Safari and Chrome? Does "the reading tool can flash" refers to flashing of the prose/poetry piece that is displayed below the toolbar?

I was testing with the current version of http://texts-beta.alpheios.net, and in Chrome I see no issues whatsoever, except maybe for an occasional blinking of a word in a text piece when the toolbar is dragged over it. This, however, happens very seldom and is hard to reproduce. I think maybe it's some glitch of a webkit rendering engine.

In Safari, however, if trying to move the toolbar out of the screen, I see that the text piece is getting a transparent red overlay, is if a text selection mode is applied to it: 
![image](https://user-images.githubusercontent.com/18631055/57910406-48018f00-7896-11e9-8035-e6777f6e99c9.png)
Is this it or is it something different?

I see on a screenshot that only an arrow of the toolbar is displayed and the toolbar is gone. If that's the problem, then I am not able to reproduce it currently, unfortunately.

Will continue with testing trying to reproduce the issue.

**Comment by kirlat** [comment]
I'm also having a weird issue running a nemo ui environment locally on MacOS: alpheios-project/alpheios_nemo_ui/issues/166

**Comment by monzug** [comment]
on safari (desktop) see video

[IMG_3475.zip](https://github.com/alpheios-project/components/files/3191435/IMG_3475.zip)

**Comment by monzug** [comment]
it's the problem that you can't reproduce. might be related to my test environment. will reboot and clean again the environment. yes, I have the same issue when moving the overlay outside the screen, I get a blue screen instead of pink!

**Comment by monzug** [comment]
reboot again, still same problem.

**Comment by balmas** [comment]
I can't reproduce this anymore.  @monzug the interface has changed so much since it was reported, can you verify whether or not it is still a problem (once you get back home with your mac)? Thanks!

**Comment by monzug** [comment]
I will

**Comment by monzug** [comment]
not longer reproducible tested in safari and chrome on mac
