### ISSUE TITLE
word list filter feedback

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#562]
requested by @abrasax 

1) change "word form" to "exact word"

2) remove "word form (part)" and "lemma (part)" and add autocomplete to exact word and lemma filters (based upon contents of list)

2b) autocomplete should be reduced to only the valid values for a filtered list

3) eliminate filtering options if only one item in the list

**Comment by balmas** [comment]
we might break these in to multiple issues. Autocomplete can come after the beta. The rest needs to be for the beta.

**Comment by irina060981** [comment]
1. Changed the list of filters
![image](https://user-images.githubusercontent.com/12377640/57967169-bb8ec380-799e-11e9-9b47-a817b37dafd1.png)

2. Added autocomplete to the `by exact form` and `by lemma` this way:
![image](https://user-images.githubusercontent.com/12377640/57967181-e416bd80-799e-11e9-9259-a6d04af3e7d3.png)

**Steps:**
   - a user types a part of the exact form/lemma - autocomplete will suggest variants, search part will be highlighted
    - if a user selects a variant from autocomplete list, then it would be pasted to the typeInput and the wordlist would be filtered and autocomplete would be hidden
   - if a user tries to filter with the part/incorrect variant (that is not in the list) , filtering wouldn't be done
 
If a user will add a new word to the list, filters would be cleared

3. If a wordList has only one value, filters won't be shown
![image](https://user-images.githubusercontent.com/12377640/57966814-5042f280-799a-11e9-98ba-11bfd451d182.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
reading for testing in texts-beta
embed-lib 1.0.0.16
webext 3.0.0.37

**Comment by monzug** [comment]
tested in build 1.0.0.17
- confirm that filtering options are not present with only one word in the list. This works.
- auto complete and exact form/lemma work on desktop.
- filter by exact form does not work on mobile (iPhone xr and Samsung 5 mini). when I select by exact form, there is an other entry field visible under the form field. autocomplete does not kick in and the exact form does not do anything, the same word list is displayed when I click on Filter button.

**Comment by balmas** [comment]
>filter by exact form does not work on mobile (iPhone xr and Samsung 5 mini). when I select by exact form, there is an other entry field visible under the form field. autocomplete does not kick in and the exact form does not do anything, the same word list is displayed when I click on Filter button.

this should be fixed. 

> we have exact form (not exact word). Please confirm this is ok.

this too, I think it should say "exact word"

**Comment by irina060981** [comment]
1. I have descreased the space that needs for filters - so they shouldn't become 2 lines
![image](https://user-images.githubusercontent.com/12377640/58475872-7afb2b00-8192-11e9-9965-5e36627f77d0.png)

2. Fixed

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
can be tested in texts-beta embed-lib 1.0.0.18

**Comment by monzug** [comment]
exact word is fixed. autocomplete works fine both for exact word and lemma. the entry field for filter for exact word/lemma should NOT make the first letter upper case., otherwise the filter is not working.
shall I enter a separate issue or shall we fix this one?

**Comment by balmas** [comment]
ugh.... that's an easy fix, I know.  what do you think? worth another build?

**Comment by monzug** [comment]
well, it's not working basically unless you change to lower case. I would do an other build. I can check the fix tonite. I'll stay up anyway

**Comment by balmas** [comment]
ok, buildling now

**Comment by balmas** [comment]
ready for testing in text-beta embed-lib 1.0.0.19

**Comment by monzug** [comment]
Thanks!!!!
