### ISSUE TITLE
once you have moved the popup once, it can't be moved again

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#563]
Might be a bug with the changes for #468 or else an interact.js bug

Once I have moved the popup once (or a few times) I can no longer move it again until I reload the page.

**Comment by balmas** [comment]
@monzug noted in #335 

>as per Firefox (3.0.0.31), unfortunately after the first move of the fixed pop-up (and overlay), I am not able to move it around again. I need to reload the page. note that the text environment works just fine also in firefox.

Note however that I was seeing this behaviorin the text environment in Chrome

**Comment by kirlat** [comment]
I was not able to reproduce it exactly as described, when it was stopping to work after a series of drag and drop actions. I was, however, able to find a situation when an attempt to resize it was causing drag and drop functionality to cease working. The fix is in #570.

**Comment by monzug** [comment]
Confirmed that I am still able to repro in build 3.0.0.36 in Firefox.
after a first drag and drop I can't move it again, need to reload the page: https://www.thelatinlibrary.com/sall.macer.html -

**Comment by kirlat** [comment]
> Confirmed that I am still able to repro in build 3.0.0.36 in Firefox.
> after a first drag and drop I can't move it again, need to reload the page: https://www.thelatinlibrary.com/sall.macer.html -

I can reproduce it, and the fix submitted in #570 won't work for this. This issue seems to be related to `interact.js` and is most likely the same as reported in #472: https://github.com/alpheios-project/components/issues/472#issuecomment-494070632. The clear indication of that is that the second time we hover over the popup's toolbar a move cursor do not appear. The cursor is generated by the `interact.js` and the lack of it is an indication that Interact loses track of a draggable object for the reason unknown 🙁.

**Comment by balmas** [comment]
@kirlat we *do* need the popup resizing functionality, as well as drag and drop.

**Comment by kirlat** [comment]
> @kirlat we _do_ need the popup resizing functionality, as well as drag and drop.

Thanks for the info, will work on the fix then

**Comment by balmas** [comment]
ok, ready for testing in texts-beta
embed-lib 1.0.0.16 webextension 3.0.0.37

**Comment by monzug** [comment]
build 3.0.0.37
Firefox: confirm that pop-up and overlay can't be moved again after the first move. in test env, it works fine.
Chrome: popup and overlay can be drag and drop several times. 
tested in : 
https://texts-beta.alpheios.net (1.0.0.16)
http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-100.html
https://www.thelatinlibrary.com
https://www.tradurreantico.it/latino/grammatica-latina/morfologia/verbo/verbo-eo-latino/

**Comment by balmas** [comment]
ok, so the problem remains, but only in Firefox?

**Comment by monzug** [comment]
correct, only in Firefox

**Comment by balmas** [comment]
dupe of #712 
(this is the original item, but debugging info is in the later one).
