### ISSUE TITLE
eliminate menu in compact panel

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#564]
after discussion with @abrasax and with the new fixed position for the tools icon on mobile, we think we'd like to change the compact panel only as follows:

1) eliminate the drop down menu
2) when the user is on a word-specific panel tab (i.e. morphology, definitions, inflections or examples), then only those 4 icons will be shown in the panel navbar (to the left of expand and close)
3) Users will access the other non-word specific panel features (browse grammar, browse inflections, wordlist, user, options)  only through the action panel.  When a user is on one of these panel tabs, then only that specific icon (as active) will be on the panel navbar. They will have to close the panel to get to one of the others.

Let me know if this isn't clear.

**Comment by balmas** [comment]
reassigned to @irina060981 . @irina060981 let me know if it isn't clear what is being asked for. Thanks!

**Comment by irina060981** [comment]
@balmas , I have several questions here:

>eliminate the drop down menu

Do you mean to remove this?
![image](https://user-images.githubusercontent.com/12377640/58252311-2712cf80-7da9-11e9-8963-7de1e10f62ee.png)

> when the user is on a word-specific panel tab (i.e. morphology, definitions, inflections or examples), then only those 4 icons will be shown in the panel navbar (to the left of expand and close)

where it is panel navbar in th mobile?
for example I am here
![image](https://user-images.githubusercontent.com/12377640/58252376-575a6e00-7da9-11e9-8bb8-59e1926b2d99.png)

where should be 4 icons? Do you mean that they should be here:
![image](https://user-images.githubusercontent.com/12377640/58252441-7953f080-7da9-11e9-9594-d4272d2d5830.png)

>Users will access the other non-word specific panel features (browse grammar, browse inflections, wordlist, user, options) only through the action panel.

So this panel shouldn't be change - it would be this - 
![image](https://user-images.githubusercontent.com/12377640/58252488-94266500-7da9-11e9-9e99-d43ed3f32c89.png)

Then I have a question - I have selected a word and then closed a panel, how could I again open the panel with definitions for example? Without reselecting a word?

**Comment by balmas** [comment]
> 
> Do you mean to remove this?
> ![image](https://user-images.githubusercontent.com/12377640/58252311-2712cf80-7da9-11e9-8963-7de1e10f62ee.png)

YES

> where it is panel navbar in th mobile?

SEE ARROW:

![58252376 575a6e00 7da9 11e9 8bb8 59e1926b2d99 (1)](https://user-images.githubusercontent.com/644870/58255541-33f8da00-7d3b-11e9-858c-cc8accfabd34.png)



> So this panel shouldn't be change - it would be this -

CORRECT

> Then I have a question - I have selected a word and then closed a panel, how could I again open the panel with definitions for example? Without reselecting a word?

hmm. I think yes, you would have to reselect the word.

**Comment by balmas** [comment]
> hmm. I think yes, you would have to reselect the word.

that might be a problem with this design, but let's implement it and request feedback on it.

**Comment by irina060981** [comment]
I have made a little additional change - make icons active (with yellow color)

If opened one of the main tab - morphology, definitions, inflections or wordUsage, then all these 4 icons (available) is shown in the panel header. Active tab has active color:
![image](https://user-images.githubusercontent.com/12377640/58328870-8a1e6800-7e76-11e9-914c-bbfb44551a5c.png)

If opened one of the tab from the action menu, then it would be the only icon (active state) in the panel header
![image](https://user-images.githubusercontent.com/12377640/58329033-f1d4b300-7e76-11e9-867d-87696248837a.png)

@balmas, now we don't have treebank icon and status icon, so we don't have access to these tabs, I believe.
May be we should add them somwhere or they would be only on the desktop?

**Comment by balmas** [comment]
> now we don't have treebank icon and status icon, so we don't have access to these tabs, I believe.

I think status doesn't need to be there (that's for debugging only) but you are right, I forgot about treebank.  That actually DOES need to be there but only when we have a treebank for the word. It looks like we have room to squeeze one more in (although this brings me back to disliking this design approach...)

**Comment by irina060981** [comment]
ok - will add it- I think the panel's header has one more place for one more icon (when they are all of them) - but it would a little cramped here :)

**Comment by irina060981** [comment]
would be this way
![image](https://user-images.githubusercontent.com/12377640/58331721-16338e00-7e7d-11e9-8497-72160685b08f.png)

**Comment by kirlat** [comment]
> ok - will add it- I think the panel's header has one more place for one more icon (when they are all of them) - but it would a little cramped here :)

I think we shall remember that there is no set width for the mobile panel. What might fit into one device might be too large for the other. I think we shall try not to fit too many items into a toolbar: this design might fail easily when users start to use it on multitude of their devices. 

But if we still want many items to be in there, then, probably, for safety, it's good a add a media query that will transform it (decrease icon size and/or spacing, hide some icons, etc.) when device width is too small to show them all. What do you think?

**Comment by balmas** [comment]
>But if we still want many items to be in there, then, probably, for safety, it's good a add a media query that will transform it (decrease icon size and/or spacing, hide some icons, etc.) when device width is too small to show them all. What do you think?

Yes, I agree. This is a good idea. But I would suggest to have @irina060981 merge this (after @kirlat your review) and then to address that with another issue.

**Comment by irina060981** [comment]
>But if we still want many items to be in there, then, probably, for safety, it's good a add a media query that will transform it (decrease icon size and/or spacing, hide some icons, etc.) when device width is too small to show them all. What do you think?

It could be another problem here. We couldn't make the button too small - it should be similiar to the finger spot. And it seems to me that it is near that size in design .
If we start to decrease icon size if a mobile device has less width - it could become hard-touchable.
I have made the current layout for the iPhone X - 375px in width.

On Galaxy S (360px) - it is visible
![image](https://user-images.githubusercontent.com/12377640/58333346-8ee81980-7e80-11e9-9ada-0a85185b2079.png)

Do we really need to made queries for less width?

**Comment by kirlat** [comment]
> Do we really need to made queries for less width?

On my opinion, if it fits on 360px, it should be fine. I think devices with anything less than that would be too small anyway to use Alpheios functionality effectively.

**Comment by irina060981** [comment]
merged and closed

**Comment by kirlat** [comment]
Here is a list of devices (a little outdated by today's standards but that's a good think for testing purposes) with their resolutions: https://www.mydevice.io/ CSS width is what would affect the minimal panel size.

Majority of devices does not go below 360px, but there are a couple of models that have it at 320px. However, those devices are clearly outdated and I think we can safely ignore them. I think most modern phones, even budget ones, have resolution of at least 720x1280px. With DPR 2 it gives us the same 360px.

So probably we can accept 360px as a minimal hardware requirement for our UI to be workable. @balmas, what do you think?

**Comment by balmas** [comment]
>So probably we can accept 360px as a minimal hardware requirement for our UI to be workable. @balmas, what do you think?
Yes that's okay with me.

**Comment by balmas** [comment]
reading for testing in texts-beta
embed-lib 1.0.0.16
webext 3.0.0.37

**Comment by monzug** [comment]
tested on iPhone xr and Samsung 5 mini
examples are only for latin. I see diagrams in greek but could not find any for latin text in the text env, so I could not test the situation of 5 icons in the compact panel. any suggestion?

small issues
1) the active icon in compact panel is not sticky, if I scroll the panel, the icon goes back to white.
 see screenshot

2) in samsung 5 mini, in landscape view the split screen is really small. in Define, I can barely see the entry field and when I enter a word such as fero, the lookup is for the reverse word: oref

3) the reader split screen in landscape view has the top nav truncated for FAQ/known issue when scrolling the text. see screenshot

![IMG_3492 (1)](https://user-images.githubusercontent.com/41396793/58370739-fa110a80-7ed7-11e9-81e5-f9a79e550026.jpg)

![IMG_3493](https://user-images.githubusercontent.com/41396793/58370797-a4892d80-7ed8-11e9-973b-61e29ffc4286.PNG)

**Comment by balmas** [comment]
> the reader split screen in landscape view has the top nav truncated for FAQ/known issue when scrolling the text. see screenshot

I think we probably need to detect this situation. The design called for the nav menu to actually change when in landscape split screen -- see alpheios-project/alpheios_nemo_ui#158.

**Comment by balmas** [comment]
>in samsung 5 mini, in landscape view the split screen is really small. in Define, I can barely see the entry field and when I enter a word such as fero, the lookup is for the reverse word: oref

I don't think there is much we can do about this.

**Comment by balmas** [comment]
>the active icon in compact panel is not sticky, if I scroll the panel, the icon goes back to white.
see screenshot

I would like us to fix this.

**Comment by balmas** [comment]
assigning back to @irina060981 to fix the active icon state.

**Comment by kirlat** [comment]
> I think we probably need to detect this situation. The design called for the nav menu to actually change when in landscape split screen -- see [alpheios-project/alpheios_nemo_ui#158](https://github.com/alpheios-project/alpheios_nemo_ui/issues/158).

The current version of components, when present, sets a `data-ap-screen-orientation="landscape"` data attribute of an `html` element that contains the current screen orientation. It updates every time orientation changes.

There is also an orientation change event fired by the `Platform` class instance (UI controller has it in the `platform` prop) when orientation is switched. We can subscribe to it if we need to detect an orientation change dynamically.

**Comment by irina060981** [comment]
I tried to look at it today - it has a direct style property - `padding-left: 50%`
so as we change layout via media-query - it doesn't properly work

**Comment by irina060981** [comment]
> 1. the active icon in compact panel is not sticky, if I scroll the panel, the icon goes back to white.
see screenshot

it was a small mix in styles - fixed

> 2. in samsung 5 mini, in landscape view the split screen is really small. in Define, I can barely see the entry field and when I enter a word such as fero, the lookup is for the reverse word: oref

I suggest to change Lookup text to the icon when landscape mode.
It would be this way
![image](https://user-images.githubusercontent.com/12377640/58473366-c1995700-818b-11e9-952a-6bfdb8ccfee2.png)

It would be in this PR https://github.com/alpheios-project/components/pull/590

**Comment by irina060981** [comment]
2 first points are merged and closed
the last with alpheios-nemo will do now

**Comment by irina060981** [comment]
Oh the last in a separate issue - then - I will close it
