### ISSUE TITLE
Safari: overlay not generated for local file

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#569]
related to issue #362
I could not test the issue in safari build 3.0.0.33 as the overlay did not appear in the tab with the test.html file. Note that the overlay is normally generated on activation of alpheios in the latin library site.

**Comment by balmas** [comment]
I believe this is the same as alpheios-project/webextension#185

**Comment by monzug** [comment]
a variation of it, yes.

**Comment by balmas** [comment]
can't really do anything about this. it's a limitation of safari.

**Comment by monzug** [comment]
it's ok, at least we have a record of this issue.
