### ISSUE TITLE
Samsung 5 mini (Chrome): can't login in texts env

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#571]
I keep clicking on login button from the lookup popup, from the tool menu, from the morphology popup, but nothing happens. the page keeps loading but then it goes back to the same page. 
anyone else?

**Comment by balmas** [comment]
is it just on the Samsung 5 mini?

**Comment by monzug** [comment]
yes. I don't have other Samsung. iPhone xr is ok

**Comment by balmas** [comment]
hmm. that's weird. has it ever worked before on that device?

**Comment by monzug** [comment]
yes. always. I have noticed yesterday as I wanted to test the login with google issue (#444)

**Comment by balmas** [comment]
I wonder if it's a problem with the change too https.  Are you accessing it first at http://texts-beta.alpheios.net or https://texts-beta.alpheios.net?

**Comment by monzug** [comment]
YES!!!! that's it. Thanks.

**Comment by balmas** [comment]
so it's the redirect from http to https during login that is not working properly?

**Comment by monzug** [comment]
I just typed the url with https and the login is working. I thought it
would automatically switch to https when trying to login.

**Comment by balmas** [comment]
it should, but apparently it isn't working 100% as expected. I saw something similar on Harry's Samsung Note 8.  Eventually we will redirect all http traffic to https from the start. So, this one might not be high priority. Still good to understand what is happening.  So let's keep this open.

**Comment by monzug** [comment]
actually I tried on my iPhone to login from http and it does this thing.
The first time it did show the login popup and let me in with google. but
now it does exactly what I saw in the samsun

**Comment by balmas** [comment]
thanks. I will try to fix it.

**Comment by monzug** [comment]
OK. could login with google have something to do with it?

**Comment by balmas** [comment]
I don't think so. I saw it with a non-google login on Harry's phone

**Comment by monzug** [comment]
ok. I'll assign back to you

**Comment by balmas** [comment]
@monzug can you try to reproduce this with the latest texts-beta code? I made one change which might have been sufficient, but maybe not.

**Comment by monzug** [comment]
Still I can't login from not secure http://texts-beta.alpheios.net  on Samsung and iPhone xr

**Comment by balmas** [comment]
ok.

**Comment by balmas** [comment]
I have solved this by just redirecting all http traffic to https on texts-beta. This will be necessary anyway for the PWA functionality so there isn't any reason not to do it now.

**Comment by monzug** [comment]
the not secure site is redirect automatically to a secure site.
