### ISSUE TITLE
lookup interference with source links in usage examples on mobile

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#575]
>lookup for fero and go to the word usage examples and click on Get results.
Have show source links on. click on any link, it's very difficult to have the source underline and selectable as link, specially when moving from landscape to portrait view. Frequently, it does open a morphological popup related to the word on which the finger was on.

_Originally posted by @monzug in https://github.com/alpheios-project/components/issues/573

**Comment by balmas** [comment]
I experienced this too. I think maybe we need to make the links explicitly wrapped in an data-alpheios-ignore div.

**Comment by irina060981** [comment]
Oh, I know, what you are talking about - I have seen this once, but then forgot to fix it
Will fix

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
reading for testing in texts-beta
embed-lib 1.0.0.16
webext 3.0.0.37

**Comment by monzug** [comment]
tested in build 1.0.0.16 on iPhone xr and Samsung 5 mini
I am not sure what's going on here but it's difficult to link to any source, specially from de Bello Gallico (Caesar).
For some reason, I got some souce links to work from Elegiae, Propertius Sextus.
 I am not sure if it's the source link itself. need to try more things.

**Comment by irina060981** [comment]
@monzug, could you give me some more details here:

 - If you test on desktop, and there are no any problems with clicking on the source link. Am I right? - 
 - When you test on the mobile - most of all the time source link doesn't work - it is not clickable? or does it happen anything else?

I tried to see some bugs on my Samsung - I used 
http://texts-beta.alpheios.net/text/urn:cts:latinLit:phi0448.phi001.perseus-lat2/passage/1.1.1-1.1.5
as you pointed, but source links are clickable

The only problem I found out - that if I scroll and upload additional text and then select a word, than the first link (without additional uploads) will be saved. @balmas , may be we should create additional issue for that?

**Comment by monzug** [comment]
Irina, it's on mobile only. when I click on the link, most of the time (but not always) it does the lookup for the word I hover over when selecting the link. I could not find a good reason, I thought it could be the type of link or the word or the book or Samsung vs iPhone. definitely it does not work for me most of the time.

**Comment by irina060981** [comment]
Oh, i guessed, I have missed that on mobile we look at the another source block, that I didn't add to ignore.
I was testing source link in wordlist that's why I couldn't see the problem.
Wordlist and word usage examples sometimes mix in my head, I am sorry!
Will fix

**Comment by monzug** [comment]
hahaha it does happen. No problem!!!!!!

**Comment by irina060981** [comment]
:) 
Merged and closed

**Comment by balmas** [comment]
can test in texts-beta embed-lib 1.0.0.17

**Comment by monzug** [comment]
tested in build 1.0.0.17 on Samsung 5 mini it works like a charm!!!!
still on iphone xr, it jumps up to the first souce link of the list and shows that link.
@balmas Known issue?

**Comment by balmas** [comment]
I would say let's leave it for now, although it's possible that the fix @kirlat just made for #573 could help here.

**Comment by monzug** [comment]
it's better but I can't really test this issue as I can't scroll down the list after the 7th or 8th source link.

**Comment by balmas** [comment]
@monzug is reporting problems with this so I'm reopening. We'll either fix or put it back in the faq

**Comment by monzug** [comment]
both in Samsung mini and iPhone xr I was able to link from source link to latin.packhum.org only once (tested with both orientation).

**Comment by balmas** [comment]
it looks like we lost the data-alpheios-ignore attribute on the source links. I think that should fix this.

**Comment by monzug** [comment]
@balmas, was it removed for other reasons?

**Comment by balmas** [comment]
no, I don't think so. I think it was just lost when we fixed the scrolling problem

**Comment by monzug** [comment]
ok. I will do more testing when fix is available.

**Comment by balmas** [comment]
ok. Hope to have a build for you this morning!

**Comment by monzug** [comment]
perfect.

**Comment by balmas** [comment]
qa-3.0.0.64/components 1.2.38

**Comment by monzug** [comment]
both scrolling and linking work great. tested in portrait and landscape view.
