### ISSUE TITLE
make X Close icon thinner

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#579]
request from Mark that we make this icon less prominent

**Comment by balmas** [comment]
can be in the beta if we do another build before then

**Comment by irina060981** [comment]
Here it is
![image](https://user-images.githubusercontent.com/12377640/58362223-36dd0180-7ed8-11e9-8d8f-f41c65d3d93f.png)

![image](https://user-images.githubusercontent.com/12377640/58362229-40ff0000-7ed8-11e9-8a51-6f8c62a12b07.png)

![image](https://user-images.githubusercontent.com/12377640/58362233-478d7780-7ed8-11e9-993e-d61839a3fc61.png)

**Comment by irina060981** [comment]
merged and closed
