### ISSUE TITLE
grammar component isn't mobile responsive 

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#58]
the content of the grammar component needs to be fixed so that it adjusts better to different screen sizes. When used in the pwa prototype it runs off the right side of the screen.

**Comment by kirlat** [comment]
I submitted a build that should be fixing it, please verify that it works for you. Thanks!

**Comment by balmas** [comment]
yes it's looking okay on mobile now. I had submitted this as an issue on components rather than pwa-prototype because I was thinking maybe it was a change that could/should be made in the grammar component styles itself, but I see that you have put them into a new mobile layout of the panel component.
