### ISSUE TITLE
adjust size of icons in compact panel based upon media query

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#580]
>But if we still want many items to be in there, then, probably, for safety, it's good a add a media query that will transform it (decrease icon size and/or spacing, hide some icons, etc.) when device width is too small to show them all. What do you think?

Yes, I agree. This is a good idea. But I would suggest to have @irina060981 merge this (after @kirlat your review) and then to address that with another issue.

_Originally posted by @balmas in https://github.com/alpheios-project/components/issues/564#issuecomment-495637495_

**Comment by balmas** [comment]
copying some discussion from #564 


Copying some additional discussion in #564 

from @irina060981 

>It could be another problem here. We couldn't make the button too small - it should be similiar to the finger spot. And it seems to me that it is near that size in design .
If we start to decrease icon size if a mobile device has less width - it could become hard-touchable.
I have made the current layout for the iPhone X - 375px in width.
Do we really need to made queries for less width?

From @kirlat 

>Here is a list of devices (a little outdated by today's standards but that's a good think for testing purposes) with their resolutions: https://www.mydevice.io/ CSS width is what would affect the minimal panel size.
Majority of devices does not go below 360px, but there are a couple of models that have it at 320px. However, those devices are clearly outdated and I think we can safely ignore them. I think most modern phones, even budget ones, have resolution of at least 720x1280px. With DPR 2 it gives us the same 360px.
So probably we can accept 360px as a minimal hardware requirement for our UI to be workable. @balmas, what do you think?

From @balmas 
>Yes that's okay with me.

**Comment by balmas** [comment]
I'm not sure if there is anything more we want to do here. Maybe we should fail a build if we exceed the size limitations?

**Comment by kirlat** [comment]
Since there is DOM emulation available in Jest, we can probably write a test that will check panel size and will fail if its size is larger than 360px. That should be feasible, in theory.

**Comment by irina060981** [comment]
we could do the following:
we could set a minimal width of the panel (360px) - so if it is opened at the smaller device than it would be scrollable by the width - but it would be normal on most devices

I didn't understand - what do you mean by fail the build or create a test?
Do you mean to create a test, that will create an HTML layout with max buttons and check the width?
I think that it is not a good practice - because unit tests couldn't emulate it properly with all css styles and in real browser environment - so it won't be a real test.

I believe that setting a minimal width is a good practice used by a lot of frameworks.
What do you think?

Also we could hide some icons for really small width (<360px) - inflection tables and tree diagram, because they won't be really easy to use on such small screens - and it will give more space.

**Comment by balmas** [comment]
>we could set a minimal width of the panel (360px) - so if it is opened at the smaller device than it would be scrollable by the width - but it would be normal on most devices

Ok, yes, let's do this. 

And this

>Also we could hide some icons for really small width (<360px) - inflection tables and tree diagram, because they won't be really easy to use on such small screens - and it will give more space.

**Comment by irina060981** [comment]
I think that we couldn't do both - set minimal to 360px and render if page less than 360px
I think it is enough to do the second - 

>Also we could hide some icons for really small width (<360px) - inflection tables and tree diagram, because they won't be really easy to use on such small screens - and it will give more space.

Am I right, @balmas?

**Comment by balmas** [comment]
ah, good point :-) 

Yes, I think that the latter suggestion is fine. Thank you!

**Comment by irina060981** [comment]
merged an closed

**Comment by balmas** [comment]
ready for testing at texts-test embed-lib 1.0.0.23

**Comment by balmas** [comment]
On my Galaxy 7, which is supposedly 360px wide, I don't get the treebank and inflection tables icons in portrait mode but I think I should. Switching the media-query to max-width:359px fixes it, so we need to either use min-width here to show or set max-width to 1 px lower than what our minimum is.

**Comment by irina060981** [comment]
Fixed - would be this
![image](https://user-images.githubusercontent.com/12377640/60243981-cec97300-98fc-11e9-8578-bbc273f77b01.png)

**Comment by monzug** [comment]
neither on my Samsung 5s mini: Inflection & diagram are missing

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
webextension qa-3.0.0.45/Safari3.0.0.45)/embed-lib 1.0.0.27

**Comment by monzug** [comment]
looks good on my Samsung mini 5
