### ISSUE TITLE
usage examples - hide filter after search

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#587]
As discussed, let's automatically hide the filtering/sort options on usage examples after executing a search, so that the results are visible on a small screen. 

So workflow is:

1. user opens usage examples
2. filtering is hidden
3. user clicks get results
4. results show with filters hidden
5. user clicks show filters
6. user selects filtering options and executes search
7. results show, with filters hidden

**Comment by irina060981** [comment]
It would work this way:
1. select a word and open usage examples
![image](https://user-images.githubusercontent.com/12377640/58463013-6c9f1600-8176-11e9-8382-a044bc6bb042.png)

2. get result is clicked
![image](https://user-images.githubusercontent.com/12377640/58463051-7d4f8c00-8176-11e9-9846-e79446066622.png)

3. show filters is clicked
![image](https://user-images.githubusercontent.com/12377640/58463156-a839e000-8176-11e9-90ab-f0010bb4ceaa.png)

4. filter is selected and get result is clicked

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
can be tested in texts-beta embed-lib 1.0.0.18

**Comment by monzug** [comment]
tested in build 1.0.0.18, both mobile and Chrome and Firefox on desktop. the logic is there.
