### ISSUE TITLE
bug in usage examples author selection

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#591]
tested in Chrome and Firefox  and mobile, build 1.0.0.17
Just realize that if I do double click and go to examples and get results for the same word two times in a row, the second time the author drop-down is empty.  on iphone xr, the dropdown for Authors is not populated the second time I go to examples for the same word
see screenshot
![second-x-examples](https://user-images.githubusercontent.com/41396793/58439843-77897600-80a4-11e9-8088-702877397f1d.JPG)

@balmas, I don't think it's critical for release but it should get fixed soon

_Originally posted by @monzug in https://github.com/alpheios-project/components/issues/558#issuecomment-496309030_

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
ready for testing at texts-test embed-lib 1.0.0.23
webextension qa-3.0.0.40

**Comment by monzug** [comment]
looks good. thanks
