### ISSUE TITLE
usage examples: fix prefix/suffix sort

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#595]
Requested by @abrasax 

1. rename prefix to "preceding word"
2. rename suffix to "following word"
3. the preceding word sort should sort on the word immediately before the exact word, but it is currently sorting on the first word of the example

**Comment by abrasax** [comment]
By the way, whoever changed my "exact word" to "exact form" made a very
good decision.

**Comment by balmas** [comment]
>By the way, whoever changed my "exact word" to "exact form" made a very
good decision.

If you mean in the word list filters, that is now "exact word" to match what you requested originally.

**Comment by abrasax** [comment]
yesterday my version said "exact form"- but either is adequate for the
moment.

**Comment by monzug** [comment]
I asked to change to exact word based on issue #562

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
ready for testing at texts-test embed-lib 1.0.0.23
webextension qa-3.0.0.40

**Comment by monzug** [comment]
verified in build 3.0.0.41 and text env
