### ISSUE TITLE
DRY up ResourceOptions and ContentOptions classes

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#6]
these classes are nearly identical. The only difference is that ResourceOptions are hierarchical per language. We should probably either have a base class that ResourceOptions extends.

**Comment by kirlat** [comment]
Maybe we can have a universal data-less class that will get a list of options and their values as constructor arguments? This class will know how to handle options of different types in a general way, how to save them to local storage and read them from there and do all other work related. Then we could have the same class definition, but create two instances of it by providing different options to constructors of those instances.

**Comment by balmas** [comment]
yes that sounds like a good approach.
