### ISSUE TITLE
add clickjacking protection to auth0 login page

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#600]
https://auth0.com/docs/migrations/guides/clickjacking-protection

**Comment by balmas** [comment]
this is done. It adds the following headers:

X-Frame-Options: deny
Content-Security-Policy: frame-ancestors 'none'

To test, I think just verify that login still works from the various platforms and devices

**Comment by monzug** [comment]
tested in Chrome and FF on desktop - Safari on iPhone xr
