### ISSUE TITLE
Blank panel instead of Info panel

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#605]
Tested in Chrome and Firefox,
when I right click or use the Alpheios logo to open the info panel, I get a blank panel instead. see screenshot
![blank-panel](https://user-images.githubusercontent.com/41396793/59354314-e8f73480-8cf2-11e9-81de-18da16fe730a.JPG)

to repro:
1) activate Alpheios
2) right click on the page and select Info from Alpheios Reading Tools
3) the panel opens with blank page

if it does not happen on the first attempt, open the Info panel again and it will show a blank page

could be related to issue #400 ?

**Comment by balmas** [comment]
I think it's probably just something we need to update in the webextension code.

**Comment by balmas** [comment]
can be tested in qa-3.0.0.40

**Comment by monzug** [comment]
works fine in build 3.0.0.40 (Firefox and Chrome)
