### ISSUE TITLE
add uiController method openLookup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#607]
@abrasax would like us to be able to add a lookup icon to the mobile reader UI that opens just the lookup component

For this we need to add an openLookup method that opens the action panel with just the lookup component in it.

**Comment by balmas** [comment]
@kirlat this is next priority after alpheios-project/node-build#16

**Comment by kirlat** [comment]
This has been merged into master

**Comment by balmas** [comment]
Will be tested vi alpheios-project/alpheios_nemo_ui#182
