### ISSUE TITLE
use ? instead of i for info icon

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#614]
to be consistent with alpheios-project/alpheios_nemo_ui#156

**Comment by irina060981** [comment]
I took icon from alpheios-nemo-ui

Would be this way
![image](https://user-images.githubusercontent.com/12377640/60437000-ae791b80-9c50-11e9-8d47-f44752c7eef9.png)

and this
![image](https://user-images.githubusercontent.com/12377640/60437019-b933b080-9c50-11e9-90bb-df37e40f7a6b.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
webextension qa-3.0.0.45/Safari3.0.0.45)/embed-lib 1.0.0.27

**Comment by monzug** [comment]
question: is it ok that the ? icon is highlighted when I activate alpheios?

**Comment by balmas** [comment]
Hmm. it's probably highlighted because it's the default tab. Do you think it's worth trying to fix?

**Comment by monzug** [comment]
nope, but it's worth to mention somewhere.

**Comment by balmas** [comment]
> nope, but it's worth to mention somewhere.

done. that's now issue #677
