### ISSUE TITLE
update info panel text

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#615]
to be more consistent style and content-wise with the getting started help in the alpheios_nemo_ui reading environment

**Comment by balmas** [comment]
this is fixed in qa-3.0.0.49/components 1.2.12

**Comment by balmas** [comment]
hmm. actually seems not to be in there. Need to check what happened.

**Comment by balmas** [comment]
qa-3.0.0.50/components 1.2.15

**Comment by monzug** [comment]
it's there now
