### ISSUE TITLE
use icons instead of text buttons in popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#618]
requested by @abrasax 

for consistency, let's see how using the icons instead of text for the define, inflect, diagram, examples buttons in the popup

**Comment by irina060981** [comment]
It would be this way
![image](https://user-images.githubusercontent.com/12377640/60094370-2ea20b80-978f-11e9-80a6-9fa126ae3906.png)

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
in qa-3.0.0.42

**Comment by monzug** [comment]
looks good. Just a note on tooltips:
in pop-up, we have "Show examples usages of this word" in panel it's "Word Usage Examples"
Show Definitions   vs  Definitions
Show Inflection  vs  Inflections

**Comment by irina060981** [comment]
It is because we use different translations  for panel and popup buttons :)
may be we should use the same translations for tooltips for panel and popup buttons?

**Comment by balmas** [comment]
> It is because we use different translations for panel and popup buttons :)
> may be we should use the same translations for tooltips for panel and popup buttons?

Yes, I think we should. Please do this. I think the current text of the popup tooltips are the better so let's use those.

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
embed-lib 1.0.0.25 / webext 3.0.0.43
(@monzug note that I decided to start using tags instead of branches for the QA builds, as it is more appropriate. You can find them in the same url (e.g. https://github.com/alpheios-project/webextension/tree/qa-3.0.0.43/dist) , but if you use the dropdown to locate, it's under the tags tab)

**Comment by monzug** [comment]
verified
