### ISSUE TITLE
Usage examples: default sort on author + work

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#621]
@abrasax requests that when we return usage example results, the default sort order should be a primary sort on author, and secondary sort on work.

Then we can eliminate the sort options for author and work entirely, because clearing a sort on preceding or following word should reset to the default order

He would also like to eliminate the words "Select sorting type" in the select box when none is selected.   Not sure what would be better here -- to display author/work as the default in the select box, or to display nothing.  If we display author/work, then we probably can eliminate the button to clear the sort results.

**Comment by irina060981** [comment]
@balmas , for now it is sorted by fullCit() by default.
FullCit = author.title + textWork.title (uppercase to ignore case-sensitive sorting).

That's why I believe that we already have the default sorting by author and textWork.
Or it is not working this way? 

May be if I am right - it is enough here
   - to remove by author and by textwork
   - rename Select sorting type - by author and textwork?

What do you think?

**Comment by balmas** [comment]
Yes, if that's already the default sort then you are correct.

Can we change "Select sorting type" to "Author+Work" and also let's just remove the "By" in front of the other options since it's redundant with the "Sort by" instruction. Thanks!

**Comment by irina060981** [comment]
Ok, it would be looked like this

![image](https://user-images.githubusercontent.com/12377640/59810225-94356880-9347-11e9-99c7-0d1155453f50.png)

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
in in qa-3.0.0.42 but probably should wait until #632 is done to test because it's all getting changed

**Comment by monzug** [comment]
Select sorting type has been introduced because on iPhone xr the first word on the drop-down is not selectable. by adding this sentence, the author or work can be selected. see https://github.com/alpheios-project/components/issues/539

**Comment by balmas** [comment]
>if we remove the sentence then we might have again a problem with iPhone xr

oh, that's a good point. We can keep the sentence then.

**Comment by balmas** [comment]
> > if we remove the sentence then we might have again a problem with iPhone xr
> 
> oh, that's a good point. We can keep the sentence then.

Actually clarifying ... was the problem with the iphone xr that the first item was disabled, but wasn't being grayed out? I think that might not be an issue now, because in this case the first item should actually be selectable, because it is the default.

I.e. if the select box contains

- Author+work
- Preceding word
- Following word

Any one of theses is a valid option. When first displayed, the sort will be Author+Work, and show as selected. To change to one of the others, you select, and then to change back to Author+Work you select that again.

**Comment by monzug** [comment]
yes, the problem was that the first item was not selectable, I had to
scroll to the next one and back to the first to be able to select it.

**Comment by monzug** [comment]
author+work is selectable on iPhone xr

**Comment by irina060981** [comment]
>author+work is selectable on iPhone xr
I really happy with this fact!!!!!
