### ISSUE TITLE
initial display of tree on desktop is smooshed

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#623]
I think maybe introduced by some of our changes to the sizing of the panel, the initial display of the trees in the diagram window appear smooshed

navigating between trees once loaded, the display resolves. 

![Alpheios Texts](https://user-images.githubusercontent.com/644870/59605788-87154100-90dd-11e9-86ba-d68be349a09b.png)

**Comment by balmas** [comment]
I think the problem is that the src of the iframe is being updated before the panel is visible. See this comment from the current 2.1.0.0x release version of the code:

https://github.com/alpheios-project/components/blob/v0.6.3-patch1/src/vue-components/treebank.vue#L39-L41

that was lost in the refactoring. Assigning to @kirlat to fix.

**Comment by monzug** [comment]
I think this is the same as alpheios_nemo_ui/issues/199 - will mark the other one as dup.

**Comment by balmas** [comment]
embed-lib 1.0.0.25

**Comment by balmas** [comment]
oh .. just realized we needed to fix alpheios-project/client-adapters#7 to test this because we are now under https.  will be ready with the next build.

**Comment by monzug** [comment]
I think I added a comment with the iPhone issue: the top navigation is missing from the diagram

**Comment by balmas** [comment]
I am struggling to find that issue

**Comment by monzug** [comment]
I just added a comment here but it's gone. on iPhone xr, the pop-up is ok while loading the diagram, when loaded the top navigation is gone (no scrolling arrows or credits)

**Comment by balmas** [comment]
ok, I have moved that to a new issue. I think this one is okay now.
