### ISSUE TITLE
tooltip activation area larger than icons

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#625]
reported by @PonteIneptique 

the activation area for the tooltips is larger than the tools icons themselves, so the tooltips appear before your mouse has even hovered over the icon.

This was reported in the current release, so I'm not sure if it is still an issue in the master branch but we should check.

Maybe to take into account when looking at this: #609

**Comment by balmas** [comment]
this was fixed by #609

**Comment by monzug** [comment]
fixed. I saw situation in which the tooltip was too large but not any longer.
