### ISSUE TITLE
usage examples: source link cleanup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#631]
Two requests:

1. When we display the usage examples source link, let's just display the full author and work and not the citation. I don't think we need both.  If we can't translate the citation into full author and work for some reason we could fall back to the citation, but otherwise the full data should suffice. E.g. if we get `Apul.Fl.18.37` as the value of the `cit` field in the service response, we should just display "Apuleius Florida 18.37" as the text of the source link.

2. I think there's a bug in the citation lookup code. Only the first portion of the passage reference is being included in the text of the link.  E.g. Right now for the above example we have "Apuleius Florida 18" and not "Apuleius Florida 18.37"

**Comment by irina060981** [comment]
the second point is solved in data-models repo - https://github.com/alpheios-project/data-models/pull/81

**Comment by irina060981** [comment]
the first in - https://github.com/alpheios-project/components/pull/642
 
Here it is a final result
![image](https://user-images.githubusercontent.com/12377640/60099434-f30d3e80-979a-11e9-8087-e748d51c682c.png)

**Comment by balmas** [comment]
as per discussion in alpheios-project/data-models#81 can we display the title in italics?

e.g.

Cicero, Marcus Tullius _ad Familares_ 8.4.3.1

**Comment by irina060981** [comment]
Would be this way
![image](https://user-images.githubusercontent.com/12377640/60340209-4deaa400-99ee-11e9-83b8-1ec26385895b.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
embed-lib 1.0.0.26/webextension qa-3.0.0.44

**Comment by monzug** [comment]
all in there. looks good

**Comment by monzug** [comment]
just a small thing about the title. I noticed that sometimes the citation is highlighted instead of the title (and the author is anonymous but there is an author).
if you do a usage example for moris, you'll see that the first authors/book are anonymous. in parenthesis is the title (and authors name I believe) but the cit is highlighted. e.g. Laus Pisonis, Laus Pisonis 1
see screenshot
![title](https://user-images.githubusercontent.com/41396793/61884416-30640980-aeca-11e9-87bb-c77e97267038.JPG)

**Comment by balmas** [comment]
> just a small thing about the title. I noticed that sometimes the citation is highlighted instead of the title (and the author is anonymous but there is an author).
> if you do a usage example for moris, you'll see that the first authors/book are anonymous. in parenthesis is the title (and authors name I believe) but the cit is highlighted. e.g. Laus Pisonis, Laus Pisonis 1

Ah, this is a bug in the parsing of the response, when the title isn't present.  will open a new issue in client-adapters for it.
