### ISSUE TITLE
usage examples: replace clear limits/clear sort icon, 

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#632]
@abrasax requests that we replace the clear filter icon with just links that say "Clear Limits" or "Clear Sort"

**Comment by irina060981** [comment]
@balmas, it would be enough place for the fix on desktop
but on mobile - it is not enough
![image](https://user-images.githubusercontent.com/12377640/59901965-359fe580-9440-11e9-8fa9-7da3ec02f8b3.png)

I could place text link on mobile, but it would have really small font.

May be we should make text links for desktop and leave icons for mobile?

**Comment by balmas** [comment]
I guess the other option is to have the first item in the select lists be selectable and have the same effect as clearing the limit/sort (or as is the case of the sort, resetting it to the default)

**Comment by irina060981** [comment]
I suggest to do it this way

**when the author/textwork is not selected** - Select an Author
![image](https://user-images.githubusercontent.com/12377640/60179369-e6ebb480-9860-11e9-9e6a-47decdf34e3e.png)

**when the author/textwork is selected** - Clear the filter
![image](https://user-images.githubusercontent.com/12377640/60179438-02ef5600-9861-11e9-8735-4c5b72550fde.png)

**Comment by irina060981** [comment]
@monzug, I have checked on my Iphone, the first item in all selection as available.
Hope, it would be available on your IPhone too.
Anyway - waiting for your testing it .

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
note from @monzug although this might not be in latest build "select an author on usage examples, the scrolling arrows in the drop down are way too big for the dropdown"

**Comment by balmas** [comment]
please test in webextension qa-3.0.0.44/embed-lib 1.0.0.26

**Comment by monzug** [comment]
looks good now.

**Comment by monzug** [comment]
not sure if this is the right spot but can we add an extra space between the authors drop-down and Focus on Work? only on iPhone xr
![IMG_3665](https://user-images.githubusercontent.com/41396793/60601469-2b56e300-9d80-11e9-8f08-ebe1635dc5f0.PNG)

if we remove the Clear icon in here, shall we remove it also from the user word list? just a thought...

**Comment by irina060981** [comment]
![0379D878-DFE2-4A95-A0E2-3C9EB1F19E3B](https://user-images.githubusercontent.com/12377640/60632141-58ba9400-9e47-11e9-982f-c7c04c2d33b4.png)

It is not reproducible on my IPhone 7, May be it has some cache? Because it was such bug before, but I fixed it already. 

We could make a simple check

**Comment by balmas** [comment]
>if we remove the Clear icon in here, shall we remove it also from the user word list? just a thought...

Probably yes. Will make a new issue. Thanks.

**Comment by balmas** [comment]
Per review with @abrasax we would like to make the hide/show focus/sort option available only on Mobile -- on desktop we should always show the focus/sort options.

**Comment by irina060981** [comment]
@balmas , I have made the fixes for @abrasax review and posted a PR, but I think I won't have time to merge after a review because of vacation - I hope you will merge it :)

**Comment by balmas** [comment]
Additional feedback from @monzug 
>  - Have default limits in options (Max results per authors: 3)
>- go to https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0448.phi002.perseus-lat2/passage/1.1.1-1.1.4 and double click on sequantur
>- on sort by work+author, there are 3 entries per author. When I select an author, I have more than 3 entries per author, e.g. Cicero, De finibus has 5 entries.
>I would change the setting in Option to say Max results per author+work, so there is no confusion where the limit is applied.
>I made a note to use "Sample of work+author", although I am not sure where to use it.... 
>- also I would use Clear author and clear work in drop-down (remove limit), as we are not limiting results but expanding them.
>we talked about this scenario before and I get your point of view but I am not convince about the results. 
>- usage example for sequantur as above, select Cicero in author drop-down, then look at the related works (focus on work), 
>- select Academica, there are no entries. same with the next book, then the following one.
>there are many works for cicero (maybe all his works), but for many of these works, it will return no entries (there are no results).
>my first reaction would be something is not right.
>as you had very well explained that we can't limit the works to only the ones with the search word in them, can we adjust the text to make it clear why there are no results for the book selected?
>I wrote something like: all works from selected author...
>or when "there are no results" add something like "there are no entries for this specific word in the selected work, try with an other one", though it sounds like a bet.....
>ok, these are my concerns. what do you think?

**Comment by balmas** [comment]
Ok @monzug what I came up with was this:

After the initial search, below the searched word, you get a hint that explains that the results are limited to max 3 (or whatever the current setting is) per author and instructs the user to use Focus to see more by author

![AwesomeScreenshot-localhost-8888-demo-auth-html-2019-07-08-14-07-73](https://user-images.githubusercontent.com/644870/60836071-c261d780-a192-11e9-8218-96e1cef6ae1a.png)

After either an Author Focus or Author+Work Focus, the hint changes to warn the user that results might be truncated at max 5000 (or whatever the current setting is) results:

![AwesomeScreenshot-localhost-8888-demo-auth-html-2019-07-08-14-07-00](https://user-images.githubusercontent.com/644870/60836166-08b73680-a193-11e9-827c-a5333331de41.png)

And if there are no results for a work, the error message explicitly indicates that there were no results found in the selected work by author:
![AwesomeScreenshot-localhost-8888-demo-auth-html-2019-07-08-14-07-17](https://user-images.githubusercontent.com/644870/60836252-3a300200-a193-11e9-887b-7f114dc71287.png)

Finally, on the mobile device, I decided to change the show/hide source links button to a checkbox, so that it would take up less room. It looked odd to me the way we had it:

![localhost_8888_demo_auth html(iPhone 5_SE)](https://user-images.githubusercontent.com/644870/60836315-5f247500-a193-11e9-8856-d52b6a01c68c.png)

**Comment by balmas** [comment]
What do you think? those changes will be in the next build.

**Comment by monzug** [comment]
I think I will like them. Let me try on next build. Thanjs.

**Comment by balmas** [comment]
webextension qa-3.0.0.45/Safari3.0.0.45)/embed-lib 1.0.0.27

**Comment by monzug** [comment]
I like it. Thanks for reworking it. Looks good.
