### ISSUE TITLE
overlay toolbar: changes to help icon

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#633]
requested by @abrasax 

1. Change the help icon to the ? to match what we use in alpheios_nemo_ui
2. Move the help icon to the always visible part of the overlay toolbar (above the tools icon)

**Comment by kirlat** [comment]
We're already using a question mark in a circle in the desktop version of a toolbar
![image](https://user-images.githubusercontent.com/18631055/61220791-1dae3f80-a728-11e9-9abc-3909b7e207a2.png)
and in the panel
![image](https://user-images.githubusercontent.com/18631055/61221015-96ad9700-a728-11e9-9c8a-836759c299e9.png)
So the only thing that is not done yet, it seems, is to move the hep icon to the always visible part of the overlay toolbar. Shall it look similar to below?
![image](https://user-images.githubusercontent.com/18631055/61222307-7fbc7400-a72b-11e9-9197-8cfc8f4e9c0d.png)

**Comment by balmas** [comment]
yes, I think that's right. Can we even out the spacing in between the 3 icons there (lookup, help and tools)?

**Comment by kirlat** [comment]
> Can we even out the spacing in between the 3 icons there (lookup, help and tools)?

Yes, definitely. Will start implementing this.

**Comment by balmas** [comment]
per discussion on slack, the order should be help, lookup, tools

**Comment by balmas** [comment]
qa-3.0.0.49/components 1.2.12

**Comment by balmas** [comment]
oops, did the wrong order

**Comment by balmas** [comment]
qa-3.0.0.50/components 1.2.15

**Comment by monzug** [comment]
verified

**Comment by monzug** [comment]
wait, there is something funny on the lookup in both chrome and FF - see screenshot

![lookup-chrome](https://user-images.githubusercontent.com/41396793/62246615-028f3100-b3b2-11e9-96e7-73203b45b8db.JPG)

**Comment by balmas** [comment]
do you mean that both the lookup icon and the tools icon are the active color? That is because both are open.  I could remove the active color from the tools icon again, but it seemed inconsistent to me. 

Or do you mean something else?

**Comment by monzug** [comment]
the lookup is smaller than the size of the flex nav. it looks weair

**Comment by balmas** [comment]
oh.... ok I can fix that. thanks!

**Comment by balmas** [comment]
qa-3.0.0.51/components 1.2.17/embed-lib 1.0.0.34

**Comment by monzug** [comment]
yes.
