### ISSUE TITLE
remove flexible positioning popup option

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#634]
I think the changes to remember the popup position (#468) broke the flexible positioning option for the popup.  If that's set, the shift gets set to 0,0 and it no longer tries to position itself at the location of the click.  I'm tempted to just get rid of that feature because it was difficult to get right which is why it wasn't the default. I think maybe the ability to remember where a user last put the popup makes this less necessary anyway too. 

@monzug @abrasax  what are your thoughts about this?  Could we abandon that feature for now?

**Comment by monzug** [comment]
agree

**Comment by balmas** [comment]
webextension qa-3.0.0.44/embed-lib 1.0.0.26

**Comment by monzug** [comment]
I am not sure if this is a side effect of the above change but in FF I cannot move the morphology pop-up (and the flex nav) anymore. Note that Chrome works fine. see screenshot (I cannot reach the bottom of the pop-up)
![cannot-move-the-popup](https://user-images.githubusercontent.com/41396793/62079271-6253d380-b21c-11e9-99e9-499906977257.JPG)

**Comment by balmas** [comment]
hmm. in build qa-3.0.0.49 I can move the popup in FF but not the overlay toolbar. @monzug do you see the same?

**Comment by monzug** [comment]
build 3.0.0.49 in FF 
I can't move pop-up (after first move) and flex nav in 
https://latin.packhum.org/loc/22/1/17/8497-8502#17
https://la.wikipedia.org/wiki/Vicipaedia:Pagina_prima
http://www.thelatinlibrary.com/quintilian/quintilian.decl.mai9.shtml

**Comment by balmas** [comment]
ok, assigning to @kirlat . Thanks.

**Comment by balmas** [comment]
actually, I think it's better as a new issue. Not sure it's related to this fix at all.

**Comment by balmas** [comment]
@monzug the new issue is #712. Can we close this one?

**Comment by monzug** [comment]
yes
