### ISSUE TITLE
wordlist: sort by target word (ascending and descending)

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#653]
We need to add a UI element to all the user to sort their wordlist alphabetically (ascending or descending). sort should ignore case.

**Comment by irina060981** [comment]
Would look like this
![image](https://user-images.githubusercontent.com/12377640/60518198-61667980-9d24-11e9-8fc7-2a75ef4b4298.png)

![image](https://user-images.githubusercontent.com/12377640/60518268-83f89280-9d24-11e9-8b42-2be371c5bf1f.png)

**Comment by irina060981** [comment]
the space between icons - because they are 22px with clickable padding.
And I tested it on mobile - it is not good to make it closer - becaus ethey are smalll.

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
webextension qa-3.0.0.44/embed-lib 1.0.0.26

**Comment by monzug** [comment]
question: how do we sort accent? right now, they go after regular words and sort in alphabetical order

![sorting-greek](https://user-images.githubusercontent.com/41396793/61006662-c9c2e580-a338-11e9-8eb9-2deb31dec193.JPG)

**Comment by balmas** [comment]
ah, we need to do locale sensitive sorting. Will fix.

**Comment by monzug** [comment]
I might have few other questions. need to do some more testing

**Comment by monzug** [comment]
how about numbers? right now, they go to top if ascending is selected or to bottom if descending is selected
![number-order](https://user-images.githubusercontent.com/41396793/61059439-fb828d80-a3c6-11e9-8eee-6d759ebb52da.JPG)

**Comment by monzug** [comment]
should we apply the ascending/descending also to the limits? right now, if I select a limit (e.g. by this session or by important) and then select descending, it goes back to the complete list of words.

**Comment by balmas** [comment]
> how about numbers? right now, they go to top if ascending is selected or to bottom if descending is selected

I think that's ok

**Comment by balmas** [comment]
> should we apply the ascending/descending also to the limits? right now, if I select a limit (e.g. by this session or by important) and then select descending, it goes back to the complete list of words.

No, that sounds like a bug. Will investigate.

**Comment by balmas** [comment]
in qa-3.0.0.46 and embed-lib 1.0.0.28 (with components 1.2.2)

**Comment by monzug** [comment]
all good.
