### ISSUE TITLE
grammar link to target within page not working on iPhone XR

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#655]
I noticed that the link to grammar from morphology are different in desktop versus mobile.
e.g.  collaudatur  in https://texts-beta.alpheios.net/text/urn:cts:latinLit:phi0448.phi002.perseus-lat2/passage/1.1.1-1.1.4
click on 1st conjugation from morphology. in desktop it will take the user to the FIRST (OR Ā-) CONJUGATION of the Grammar
on mobile, it will stay in Part II, Inflections without taking the user to the chapter.

let me know if I should enter a separate issue. Thanks

_Originally posted by @monzug in https://github.com/alpheios-project/components/issues/613#issuecomment-507276004_

**Comment by balmas** [comment]
additional notes

from @balmas 
>hmm, that's interesting. On the Galaxy 7 it does first go to Inflections and then, after a moment, to First Conjugation. Surprised that this would behave differently on the iPhone because it's just standard link hash reference. Are you sure it doesn't go to the section after first loading the page?

and @monzug 
>I waited for a bit but didn't go anywhere.

**Comment by balmas** [comment]
@irina060981 can you reproduce this on your iPhone?

**Comment by irina060981** [comment]
I have checked it on desktop-Chrome, Mac-Safari, Samsung A5 - Chrome - woprks like a charm.

Tried on IPhone Safari and Chrome - it reproduces the same problem  - the link from morphology goes only to the Part 's header 
It is really IPhone specific behaviour «like»

**Comment by irina060981** [comment]
Here it is a discussion about the similiar problem

https://premium.wpmudev.org/forums/topic/anchors-inside-the-iframe-are-not-working-on-ios

**Comment by irina060981** [comment]
I have an idea - what is happening on IOS here with iframe.
If you look carefully on the current url link following steps - you will see:
   - it opens the grammar tab
   - load url withouit hash to iframe
      it adapts to the width and has a little horizontal scrolling
   - it scrolls vertically to hashtag

There is a well-known old IOS bug:
```
The base page is scrolling at the same time as the iframe page because WebKit has an iframe scrolling bug. Often, but not always, WebKit browsers will scroll the base page in a seemingly random fashion when a scroll request is made in an attached iframe. This bug can be fixed only by the WebKit developers.
```
here it is a discussion - https://floatboxjs.com/forum/topic.php?post=8440#post8440

It could be the source of our problem.

Anyway I haven't found any suggestions or variants how it could be solved, because - "IOS + iframe = always black hole" (it is the most widely used thought for such problems)

**Comment by balmas** [comment]
ok. It sounds like this would likely require a redesign of the grammar functionality, to pull it out of the iframe, which I want to do, but not for this release. it is issue #204.  Will reference this problem there and close this issue. 

Thanks for investigating @irina060981 :-)
