### ISSUE TITLE
font size setting isn't taken into account until it changes

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#659]
I think we don't do anything with the fontSize setting until the user changes it. We should take it into account when we first read it too

**Comment by balmas** [comment]
assigning to myself to deal with as part of the settings work.

**Comment by balmas** [comment]
well, I didn't get to it so am going to ask @irina060981 to ...

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
qa-3.0.0.50/components 1.2.15

**Comment by monzug** [comment]
Glad it's back working. I did report this some times ago but I think we were not on same page.
