### ISSUE TITLE
abbreviate inflection features

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#66]
request from @abrasax to abbreviate the inflection features in the popup
e.g.   masc: acc.   fem: acc.   neut: nom. acc. voc.     or     nom: n.   acc: m. f. n.  voc: n.

(not ready to be worked on -- pending more information on correct abbreviations)

**Comment by balmas** [comment]
@monzug since you already found one issue per https://github.com/alpheios-project/inflection-tables/issues/81 maybe you can check that the rest of the abbreviations used make sense and if any are missing? The source file for them is at https://github.com/alpheios-project/data-models/blob/master/src/i18n.js

**Comment by monzug** [comment]
us vs whitaker:
com vs COMP (for comparative)  
fex vs FUTP (for future perfect)
need to check the others abbreviation

**Comment by balmas** [comment]
per @monzug we are also missing an abbreviation for pluperfect (we have one for plusquamperfect which Whitaker never reports)

**Comment by monzug** [comment]
Whitaker's abbreviation for plusquamperfect is PLUP. I like the one that we are currently using: pluperfect.
the only real issue was with sup that was used both for supine and superlative, all other abbreviations look ok. it's just a question of interpretation. I am not crazy for fex (so modern, it looks like terminology from trading)

**Comment by balmas** [comment]
per @abrasax  we should use 
comp for comparative
for future perfect wants us to check with Allen and Greenough use
plup for plusperfect (which is a synonym for plusquamperfect)

**Comment by balmas** [comment]
ok. Can you compare all of our abbreviations against Allen and Greenough? Harry says those should be the standard.

**Comment by monzug** [comment]
yes, I can. I found their online grammar  and I should be able to compare
most abbreviation

**Comment by balmas** [comment]
reading for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-5

**Comment by monzug** [comment]
checked 
Impf.
Fut.
Perf.
Plup.
fut. perf.
