### ISSUE TITLE
remove clear icons from wordlist filters/sort

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#662]
>if we remove the Clear icon in here, shall we remove it also from the user word list? just a thought...

Probably yes. Will make a new issue. Thanks.

_Originally posted by @balmas in https://github.com/alpheios-project/components/issues/632#issuecomment-508732378_

Let's be consistent with the usage examples

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
qa-3.0.0.48/components 1.2.8

**Comment by monzug** [comment]
we still have the Clear limits icon when limit to by exact word and by lemma. tested in chrome and ff in 3.0.0.48 and on mobile

**Comment by irina060981** [comment]
>we still have the Clear limits icon when limit to by exact word and by lemma.

yes, I have save it here there, because
   - it has another UI workflow (we could not choose anything to imitate clearing limits)
   - we are not checking changing the field (exact word and lemma), because it should have only values form the wordlist (there was a task about that). So I could add an event only on blur or again return an event to change.

@balmas , should I change it somehow?

**Comment by balmas** [comment]
@irina060981 maybe the "Clear limits" from the primary selection box can just clear everything? I am not sure it's necessary to have the 2nd level of clear there.

**Comment by irina060981** [comment]
I could simply remove the Clear limits from the second level input and Clear limits from the first level select will do like it is described.
But we will loose an opportunity - to reenter/reselect a lemma or a target word in one step - the user would need to guess to clear filters on the first level, reselect the ame - to filter by exact  word (for example) and retype.

If you think that it would appropriate workflow - I  will do it .

**Comment by balmas** [comment]
@monzug what do you think?

**Comment by monzug** [comment]
I agree with Irina. we missed the option to change lemma or exact word without switching from one limit to an other. on the other hand, it would be a more elegant solution and we get rid of the second limit icon

**Comment by monzug** [comment]
yes

**Comment by balmas** [comment]
ok, @irina060981 please go ahead with the change. thanks!

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
qa-3.0.0.50/components 1.2.15

**Comment by monzug** [comment]
very nice, clean
