### ISSUE TITLE
morphology icon

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#67]
I like the morphology icon i.e.
![morphology](https://user-images.githubusercontent.com/644870/40056143-6acd9f5a-5818-11e8-9226-4a9c6328316b.png)  @kirlat created but want it for the diagram/treebank panel instead :-) please use that for diagram and let's see if we can come up with something else for morphology

**Comment by kirlat** [comment]
This should be fixed by 4cc88a011b0aab0f7381e18113a9ab324d8b7aa9
