### ISSUE TITLE
rename --alpheios-inflect-browser-title-color to --alpheios-inflect-title-color

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#673]
All following items starts with `--alpheios-inflect` prefix before the text describing the location. This one starts with `--alpheios-inflect-browsers`. Maybe it's better to use `--alpheios-inflect` for consistency?

_Originally posted by @kirlat in https://github.com/alpheios-project/documentation/pull/13_

**Comment by irina060981** [comment]
Will fix in `fix-387-skin`

**Comment by irina060981** [comment]
Merged and closed
