### ISSUE TITLE
rename --alpheios-inflect-match-cell-border-color to --alpheios-inflect-feat-match-cell-border-color

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#674]
Maybe it's better to indicate in a description that this is for cells that has a full feature match (if I remember correctly). Also, maybe it's better to rename it to something like `--alpheios-inflect-feat-match-cell-border-color` to signify that too?

_Originally posted by @kirlat in https://github.com/alpheios-project/documentation/pull/13_

**Comment by irina060981** [comment]
no, it is not true - it is not for full match, it is for morphologyMatch

infl-cell--morph-match: cell.morphologyMatch

I will add morphology to description and morph to the variable title

**Comment by irina060981** [comment]
Merged and closed
