### ISSUE TITLE
provider information missing when homonym is retrieved from wordlist data

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#678]
Noted by @monzug while testing #656 :

When we click on a word in the wordlist and the lookup results get populated from the local storage, then we are missing provider information (i.e. credits) in the popup.

I believe this is because we are leaving the provider information out when we serialize the homonym for the wordlist.  We probably ought to include it but since we aren't saving full definitions to remote storage, it will often be missing anyway.  Need to think a bit about what to do here.

**Comment by irina060981** [comment]
It was solved here
https://github.com/alpheios-project/components/issues/840
