### ISSUE TITLE
add Auth0 badge to user tab

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#679]
Our open source licence agreement with Auth0 requires us to add the Auth0 bad to our interface.

http://auth0.github.io/auth0-oss-badges/

**Comment by balmas** [comment]
qa-3.0.0.48/components 1.2.8

**Comment by monzug** [comment]
I can see that in FF.
![ff-autho](https://user-images.githubusercontent.com/41396793/61962112-d715dc00-af96-11e9-98d0-073e01566bf1.JPG)

**Comment by monzug** [comment]
should it also be on mobile?

**Comment by balmas** [comment]
it should be on mobile ... I thought it was working but you're right it doesn't seem to be there in the latest build. Will investigate that and also the ff display.

**Comment by monzug** [comment]
what's wrong with the FF display?

**Comment by balmas** [comment]
> what's wrong with the FF display?

it shouldn't be so smooshed

**Comment by monzug** [comment]
ah, ok

**Comment by balmas** [comment]
@monzug can you look at this again in qa-3.0.0.49 and the latest code at texts-test? I cannot reproduce either problem.  Thanks.

**Comment by monzug** [comment]
yes! all good on desktop (FF and Chrome) and on mobile (safari), in chrome (on iPhone xr) I cannot get to the log in panel as the icon is grayed out and the tools do not really work much (again, iPhone xr). do you want me to report issues on chrome/iPhone xr?

**Comment by balmas** [comment]
@monzug Did you clear your browser history on chrome?

**Comment by monzug** [comment]
now I did and it shows up! thanks
however I still have issues on chrome/iPhone xr

**Comment by balmas** [comment]
> now I did and it shows up! thanks however I still have issues on chrome/iPhone xr

ok, please enter a separate issue for those.
