### ISSUE TITLE
use double-click instead of single click to lookup wordlist targetWord 

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#680]
reported by @monzug 

Similar to #526 

If you open the wordlist tab and the panel appears over text on the page, a double-click on the the target word will do a lookup on the word in the page below the panel.

We need probably to add the data-alpheios-ignore attribute to the wordlist tab?

**Comment by irina060981** [comment]
I didn't quitely understand, if to be honest.
The wordlist tab has already `data-ignore-all` (and also all other tabs have it too, if have onlt an exception on wordUsgae tab).

But clicking is working here:
  1. if you click on a target word - it would upload the data from the storage
  2. if you click on the lemma - it would filter by it
  3. clicking on the context part doen't work for me

@balmas, @monzug - could you add some details for this issue?

**Comment by balmas** [comment]
Hmm. After looking at it again, I think the problem here is actually a different one and exacerbated by our use of a different ui paradigm in the wordlist then elsewhere.

We use a **single** click handler on the words on the wordlist and @monzug is expecting a **double** click to work. And sometimes it does and sometimes it doesn't but when it does work it might be more of an accident than the rule.

Here's what I think is happening:

The first click of the double-click starts the word-list item lookup and closes the panel. That happens very fast and if there is another selectable word underneath it that gets caught up in the double-click, the browser a double-click event catches that word.  (This is very hard to describe...)
 
I think changing the event on the wordlist items to a double-click would solve this. Based upon @monzug 's expectations, it seems like maybe that is the likely expectation of users, since double-click is how we select words elsewhere. 

What do you think @irina060981 and @monzug ?

**Comment by monzug** [comment]
I just tried it again and as you described so well, it does work also with
double-click accidentally. I would expect double-click because we use it
everywhere else. if we want to keep single click then we should add some
info.

**Comment by balmas** [comment]
ok, let's switch to double-click. Updating the title of this item to match.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
qa-3.0.0.48/components 1.2.8

**Comment by monzug** [comment]
we have double click on wordlist now
