### ISSUE TITLE
usage examples: author drop-down not in alphabetical order

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#681]
I was able to reproduce the problem again on latest build 3.0.0.45 in FF
the author drop-down is not in alphabetical order. not easy to repro but it does happen frequently, I would say when I get usage examples for the same word.

see also https://github.com/alpheios-project/components/issues/620

![IMG_3702](https://user-images.githubusercontent.com/41396793/61079191-57154100-a3f0-11e9-99d7-87a958f562ee.jpg)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
qa-3.0.0.49/components 1.2.12

**Comment by monzug** [comment]
I did play with wordlist a bit and could repro the problem. Fixed!!!! thanks
