### ISSUE TITLE
need to update lookup in Definition Panel

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#683]
I can see the word in the lookup in toolbar when I enter the word from there. same in Help panel.
However I can't see the word in  lookup from Definition panel, even if I entered the word in there. I think we are missing to update the lookup from Definition Panel.

_Originally posted by @monzug in https://github.com/alpheios-project/components/issues/267#issuecomment-510639537_

**Comment by irina060981** [comment]
@balmas, we don't have lookup in definition panel now.
May be we could close this issue as outdated?

**Comment by balmas** [comment]
ah yes, thanks!
