### ISSUE TITLE
Add some progress indicator for retrieving data from wordlist on mobile

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/components#694]
@balmas
We have such a small confusion problem on mobile platform.
When we open a wordlist tab on mobile and try to tap a word (it should retrieve homonym, definitions and may be something else from the storage), sometimes it could take some secondsa and sometimes it could be near a minute.
And all this time nothing happens on the screen.

This way if nothing happens on the screen, it could seems - tap was not registered correctly and it does really nothing happen. Or it is thinking and will show information.

May be it is better to add some indicator here.

**Comment by balmas** [comment]
@irina060981 does this happen only when it's loading the lexical data from local storage rather than from the lexical query service? 

Looking at the code, we do have the progress bar in there, but for some reason we don't seem to be switching to the morphology tab immediately upon click on the wordlist item the way we do when the item requires the full lexical query lookup.  It just stays on the word list tab until the data is populated. 

Maybe this is easily solved by moving the `this.open()` call from line 1615 of uiController to 1609, i.e. to *before* the UserDataManager query starts?

**Comment by irina060981** [comment]
I was to move not only `this.open` but also `this.newLexicalRequest`
So when it takes too long we could see progress bar.

I have tested on my Samsung and on Iphone.
Unbelievable :), but it works great on Iphone.
On my Samsung - it has a little gap - I tried to track and I think that this small gap is from communication between UIController <-> Vuex <-> Vue-components.
My Iphone has good performance features - and here there are no gap at all.
My Samsung is less productive it gives a small gap (and it is old and sometimes my test page with application hangs on totally - it could be seen on progress bar stage).

The same for taping here - I have increased (for height) the area that could be clicked to get data from wordlist. Iphone taps well, on my Samsung sometimes I was to tap several times.

I think that it should be enough for this moment and we could plan some other improvements after getting more feedback.
What do you think @balmas?

**Comment by balmas** [comment]
>I think that it should be enough for this moment and we could plan some other improvements after getting more feedback.

I agree!

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
qa-3.0.0.48/components 1.2.8

**Comment by monzug** [comment]
Unfortunately my iPhone is so fast that I cannot see the progress bar

**Comment by monzug** [comment]
on the text environment, go to https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0474.phi007.perseus-lat2/passage/1-5  and add word reprendis to wordlist. then double click on the word from user word list. on FB it takes longer than in Chrome but I didn't see any progress bar been generated., same on web ext. Basically I have to wait for the popup to be generated. I thought we want to add a progress bar to let the user know that something is happening behind the scene. Am I wrong?

**Comment by balmas** [comment]
what you should see:

On the desktop: when you double-click on a word from the wordlist, the popup opens and then you see the progress bar on the popup while the word data is loading

On mobile: when you tab a word on the wordlist, the panel opens and you see the progress bar on the morphology pane while the word is loading

It seems to be working okay for me.

**Comment by balmas** [comment]
@monzug let me know if it makes sense. thanks!

**Comment by monzug** [comment]
I thought you wanted an extra progress bar.... ok, then.  in the above scenario (only in FF), it takes longer to generate the morphology pop-up and I am there waiting for it. I don't see the pop-up with the indicator. when it does open the morphology pop-up, it's all super fast and no indicator there. what I should expect: the morphology pop-up with indicator generated immediately.
in Chrome and on iPhone, unfortunately (or fortunately) it works like a charm.

**Comment by irina060981** [comment]
@monzug and @balmas , I saw that delay and spent some time to investigate it.
I think that this delay is from communicating between application and Vuex, and it is longer in Firefox and on my old Samsung.
We have a rather long way to pass data to a popup (or mobile panel tab):
and some steps are catches mutable properties by vue-components,
Sometimes it is quick - on Iphone dor example for me, sometimes like on my Samsung it is waiting for while - and progress is not shown - because tab is not yet changed.

**Comment by balmas** [comment]
hmm. I'll enter another issue for this for the firefox performance issue. I think it will probably have to wait until after the release but I don't want to lose track of. Sound okay @monzug ?

**Comment by monzug** [comment]
sounds good to me.
