### ISSUE TITLE
input boxes should obey text direction

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#697]
>I am not sure if we need to change the cursor for limit to exact word and lemma to be right to left

Yes, I think we should change text direction for input of exact word to rtl for arabic and persian. Actually, we probably should do the same for the lookup box too, right? I will make this a new issue.

_Originally posted by @balmas in https://github.com/alpheios-project/data-models/issues/75#issuecomment-514742697_

**Comment by balmas** [comment]
I think this affects the input box for exact word limit on the wordlist and the lookup box. The text direction should obey that of the language being entered.

**Comment by irina060981** [comment]
While working on this issue, I have faced with the following confusing behaviour:

1. If I select, for example, `እግዚአብሔር` and if I type to lookup field `እግዚአብሔር`
    I will recieve the following
    
![image](https://user-images.githubusercontent.com/12377640/62175482-4453b380-b381-11e9-9cdb-7b54f8cdda7b.png)
    
     To avoid it I should guess to open help tab and change language there

2. If I would change language there to Geez (on help tab) - it would be saved only if I would make a lookup, otherwise it returns to previous value. It could lead to the following:

     change Latin to Geez 
     try to lookup using a toolbar lookup - it would change Geez to Latin bck and show no result

**Comment by irina060981** [comment]
@balmas , I have a question here how could I define the language for lookup (to define rtl) - using select from help tab?

**Comment by balmas** [comment]
I'm struggling with a few problems related to the lookup box. #703 is another one, different from this, but also caused by lack of visibility of what language the lookup box uses.

For the most part, I would guess these are edge cases, since people aren't likely to be switching languages frequently, but it needs some thought.  No answers yet...

**Comment by irina060981** [comment]
@balmas , may be then I will create a PR for wordlist without a lookup?
and then we could think about lookup or may be even wait for feedback?

**Comment by balmas** [comment]
I'm not sure what you mean about wordlist without lookup? Are you talking about the lookup box on the toolbar?

**Comment by irina060981** [comment]
yes - I am tooking about lookup bar in toolbar and on help tab.
For now I have done rtl for Wordlist tab:
![image](https://user-images.githubusercontent.com/12377640/62210677-0f2a7e00-b3e0-11e9-8b30-99fce78378cf.png)

**Comment by irina060981** [comment]
Could I create a PR?

**Comment by balmas** [comment]
ah, ok, I understand now. Yes, please do a PR for this. thank you!

**Comment by irina060981** [comment]
I have merged PR - may be I should move problems with lookup to a separate issue and close this one, @balmas ?

**Comment by balmas** [comment]
Can you actually add them to #703?  I have renamed that item to reflect the scope better. Thanks.

**Comment by irina060981** [comment]
Done - and I will close this one

**Comment by balmas** [comment]
this change is for the input box on the wordlist only.  Dealing with the lookup box is a bigger project. 

qa-3.0.0.50/components 1.2.15

**Comment by monzug** [comment]
ok but I do not see the RTL direction in Persian and Arabic in lookup. note that it works fine

**Comment by balmas** [comment]
you're right. We can fix this part now that #703 is fixed.

**Comment by balmas** [comment]
qa-3.0.0.53/components 1.2.20

**Comment by monzug** [comment]
it's there, also backspace works correctly
