### ISSUE TITLE
when we delete all items from wordlist

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#706]
is it ok to display an empty panel and that the icon is still selectable? or should we go back to the state of icon grayed out and no panel generated if empty?

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
qa-3.0.0.50/components 1.2.15

**Comment by monzug** [comment]
now the wordlist icon is grayed out and not selectable. However when I empty the wordlist, I ended on an empty panel with the correct top nav (no wordlist icon) and with no icons highlighted. my question: is it ok to land on an empty panel or should we show a default panel (info)? I am happy with the current behavior but want your feedback @balmas

**Comment by balmas** [comment]
I think it's okay to land on the empty panel for now.  Going back to info could be equally confusing.
