### ISSUE TITLE
resource setting multi-value broken

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#719]
> > anyhow, it looks like I am not able to remove or add any grammars in Resource options both in chrome and FF
> 
> I didn't touch this - but I will check
> 
> It doesn't work for me even in Chrome

possibly I broke it with the regrouping, although I thought I had tested it.

_Originally posted by @balmas in https://github.com/alpheios-project/components/issues/323#issuecomment-517241388_

**Comment by balmas** [comment]
qa-3.0.0.51/components 1.2.17

**Comment by monzug** [comment]
this works now. Thanks
