### ISSUE TITLE
search fails with different result

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#731]
while testing issue #502 , I come across the following search that fails with different error pop-up than in case of data not found.

1) Astraea  --> from Ovid line 150    http://www.thelatinlibrary.com/ovid/ovid.met1.shtml

whitaker's output is unknown

see screenshot
![astraea](https://user-images.githubusercontent.com/41396793/62550999-2f6f9800-b839-11e9-9521-c4b6765f96af.JPG)

2) book  -->  whitaker's output is also unknown 

see screenshot
![book](https://user-images.githubusercontent.com/41396793/62551075-54fca180-b839-11e9-98fd-50e775a551aa.JPG)

**Comment by balmas** [comment]
oh, that was a good catch. I didn't update the message when the failure came from a page lookup but we should probably use the same one in both circumstances, and the former just gets the additional option to change the language. Will fix.

**Comment by balmas** [comment]
qa-3.0.0.54/components 1.2.22

**Comment by monzug** [comment]
fixed. see screenshot
![astraea-fixed](https://user-images.githubusercontent.com/41396793/62823722-049b8180-bb62-11e9-8b3c-589c719f3325.JPG)
