### ISSUE TITLE
popup color/font changes

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#735]
Requested by @abrasax 

Change color of 'Credits' link to alpheios-color-bright (the yellow color)
Change color of the short definition to alpheios-color-dark (the dark turquoise color used for the toolbar background) and increase the font weight and size.

e.g. as in attached:

![AwesomeScreenshot-www-thelatinlibrary-ovid-ovid met1 shtml-2019-08-07_10_19](https://user-images.githubusercontent.com/644870/62630451-f26cd980-b8fc-11e9-88e4-65416190efd9.png)

**Comment by balmas** [comment]
qa-3.0.0.54/components 1.2.22

**Comment by monzug** [comment]
changes are in mobile and desktop
