### ISSUE TITLE
Options are sticky in user word list

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#741]
while testing issue #598, I come across the following scenario:
1) login with id/psw: latin@test.it    Test@123
2) go to wordlist and click on letter B, it will show the French translation only. see screenshot

![french-define](https://user-images.githubusercontent.com/41396793/62714030-be141e80-b9cb-11e9-9525-257548add327.JPG)

I did reset all options for the user latin so the French translation is not longer checked in Options and it does not show up in morphology. why is it still sticky for user word list? Is this an expected behavior? Please confirm.

**Comment by balmas** [comment]
I think that's okay.  The same would be true for definitions --- i.e. if the user changed dictionaries. It will only last as long as the local cache does though. When the cache is cleared, it should go back to whatever the current settings retrieve.

**Comment by monzug** [comment]
yes, by clearing the cache I don't get the French translation. Thanks
