### ISSUE TITLE
additional changes to info panel text

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#742]
[help-language.txt](https://github.com/alpheios-project/components/files/3486396/help-language.txt)

**Comment by balmas** [comment]
specific changes:

1. add FAQ button

2. Starting Alpheios:
  Click on the Alpheios icon in the browser toolbar to
  turn the Alpheios tools on and off.

3. Word Selection:
  Double-click on a word to see lemmas, morphology, short
  definitions and icons for additional resources, such as
  long definitions, and, when available, inflection tables,
  usage examples, and sentence diagrams.

4. Word Lookup:
  Opens a lookup box in which you can enter any word to see   its lemmas, morphology etc, just as if you had double-clicked on it in a text. Note that you can change the language in which the word will be searched. 

X Additional Resources:   Shows a series of icons for other resources, including browsable inflection tables and grammars, setting options,  and, if a user has logged in, his word lists and profile.

X Moves this panel from side to side of your browser window.

Usage Tips

If a web page identifies its language, Alpheios will use that language, otherwise it will use its default language- initially set to Latin. You can change this default in the settings options.

**Comment by balmas** [comment]
note that the change to the tools help also implies a change to the tooltip from "Reading Tools" to "Additional Resources"

**Comment by balmas** [comment]
NB. For Additional Resources, I think we need to change "a user" and "his" to "you" and "your"

**Comment by balmas** [comment]
qa-3.0.0.54/components 1.2.22

**Comment by monzug** [comment]
instead of "to see lemmas, morphology" there is retrieve. is that ok?

**Comment by balmas** [comment]
ah, no, should probably fix that.

**Comment by balmas** [comment]
qa-3.0.0.56/components 1.2.25

**Comment by monzug** [comment]
verified
