### ISSUE TITLE
changes to settings panel

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#743]
per discussion with @abrasax 

move the "About alpheios" to the bottom of this panel, because the help panel will be gone in the embedded library.

Also:

change "reskin" to "resize"

change "resource"  to either "dictionaries" or "resources"

**Comment by balmas** [comment]
if we are going to make "Resources" plural, we probably should do the same for "Feature"

**Comment by balmas** [comment]
qa-3.0.0.54/components 1.2.22

**Comment by monzug** [comment]
Features and Resources are both plural. are we ok with the related tooltips being Feature Options and Resource Options?

**Comment by balmas** [comment]
I think that's okay for the tooltips.
