### ISSUE TITLE
add ability for embedded library to replace help function

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#744]
Per discussions with @abrasax 

We would like for the alpheios nemo application to be able to have the help button on the floating toolbar open the popup Getting Started help, rather than the help on the panel. 

This change will also make it possible for other sites using the embedded library to override our help with their own, should they choose.

**Comment by balmas** [comment]
qa-3.0.0.54/components 1.2.22

test this the texts-test environment, which makes use of the new feature. See alpheios-project/alpheios_nemo_ui#258

**Comment by monzug** [comment]
I am not sure how I can test the second part
This change will also make it possible for other sites using the embedded library to override our help with their own, should they choose.
any idea?

**Comment by balmas** [comment]
I think if we can do it, it's validation enough that others can. I think it can be verified.
