### ISSUE TITLE
detect orientation change and make expanded default for landscape

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#749]
If a user switches to landscape mode from portrait, with the panel open, it probably means they want more horizontal space so we should make the expanded panel the default in this case.

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
it works as described. 
question: if I have a panel open (e.g. Options) in portrait mode (not expanded) and switch to landscape, the panel is still expanded also when I go back to portrait mode. should it go back to its original state?

**Comment by balmas** [comment]
> if I have a panel open (e.g. Options) in portrait mode (not expanded) and switch to landscape, the panel is still expanded also when I go back to portrait mode. should it go back to its original state?

Ideally, yes. but I would say it's not a show stopper. @irina060981 would this be difficult to do?

**Comment by irina060981** [comment]
I have realized it this way:

1. Was Portrait + Not expanded -> Become Landscape + Expanded -> Become Portrait + Not Expanded

2. Was Portrait + Expanded -> Become Landscape + Expanded -> Become Portrait + Expanded

3. Was Portrait + Expanded -> Become Landscape + Expanded -> Switch to not Expanded -> Become Portrait + not Expanded

The last one seems to me be consistent with overall behaviour

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
qa-3.0.0.57/components 1.2.27 (Safari build in Dropbox)

**Comment by monzug** [comment]
works as described. Note that if I initiate the panel view from landscape mode, it goes to expanded panel and when I go back to portrait, it goes to not expanded view.
