### ISSUE TITLE
fieldsets for full and short definitions in options

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#750]
Let's add fieldsets around the full definition and short definition options, captions and modify the select box labels as in the attached. 

![AwesomeScreenshot-thelatinlibrary--2019-08-12_1_10](https://user-images.githubusercontent.com/644870/62883676-9a6e1280-bd02-11e9-916b-25971371f9a5.png)

**Comment by irina060981** [comment]
I have done the following here

1. Add fieldset to short and full definitions options on Settings tab
2. Add translations to resource options on Settings tab 
    I would add translations to other options tab in another PR

![image](https://user-images.githubusercontent.com/12377640/62930430-bd322100-bdff-11e9-834e-9998451a57d4.png)

![image](https://user-images.githubusercontent.com/12377640/62930459-cd4a0080-bdff-11e9-88b9-981470572b67.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
the fieldset around short and long definitions in Options can be seen in some sites, but not all. find below a list:
Chrome and FF
fieldset is visible in thelatinlibrary.com, latin.packhum.org
not visible in https://www.loebclassics.com   and    https://texts-test.alpheios.net/    and  scaife.perseus.org

not visible in text env on safari and chrome (iPhone xr)

**Comment by balmas** [comment]
back to @irina060981 , probably we need to add some styling for it.

**Comment by irina060981** [comment]
I have fixed fieldsets styles both on features and resources tab.
![image](https://user-images.githubusercontent.com/12377640/63330705-9c297d00-c377-11e9-9ad2-15917f45dcfc.png)

![image](https://user-images.githubusercontent.com/12377640/63330721-a3e92180-c377-11e9-897e-a7759c6aab7f.png)

But there are some other style problems.
you could see all of them here
![image](https://user-images.githubusercontent.com/12377640/63331430-07c01a00-c379-11e9-87c7-4684cda311dd.png)

They are from css properties with !important
I could over-write them with important only.
@balmas, what do you think - is it worth to do?

**Comment by balmas** [comment]
>They are from css properties with !important
I could over-write them with important only.

@irina060981 I'm not sure what you are suggesting. Can you clarify?

**Comment by balmas** [comment]
But like you, I have noticed, is that when you change the font-size, various form elements look a little odd. I am not sure what is causing that.

**Comment by irina060981** [comment]
>They are from css properties with !important
I could over-write them with important only.

Some basic styles on these files have `!important` flags:
![image](https://user-images.githubusercontent.com/12377640/63392153-cec78a00-c3f8-11e9-8565-07945308b961.png)

we could win them only with adding our basic styles with `!important` or stay it as is, because applying basic styles to tags with `!important` flag is the worst web "crime" :)

I suggest to stay it as is :)

**Comment by balmas** [comment]
ok, @irina060981 you are saying that the underlying page has the !important flag on its styles?

**Comment by irina060981** [comment]
>ok, @irina060981 you are saying that the underlying page has the !important flag on its styles?

yes it has it for buttons, inputs

**for buttons** 
![image](https://user-images.githubusercontent.com/12377640/63429205-c99c2680-c45c-11e9-8fa1-ad861d1ce80e.png)

**for inputs**
![image](https://user-images.githubusercontent.com/12377640/63429243-da4c9c80-c45c-11e9-877b-4b79297a410e.png)

**for selects**
![image](https://user-images.githubusercontent.com/12377640/63429271-f0f2f380-c45c-11e9-913e-cd3820cf7833.png)

**Comment by balmas** [comment]
ok, let's use #760 to track the issue of !important page styles overriding our styles and leave this for the definition of the fieldset styles.

**Comment by balmas** [comment]
fieldset styling should be fixed for most sites 
qa-3.0.0.57/components 1.2.27

**Comment by monzug** [comment]
fieldsets are visible in Safari (latin library and loeb classics and text env)
also in Chrome and FF
