### ISSUE TITLE
browse grammars should offer top level choice of language to browse

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#755]
to be consistent with Browse Inflections.  

Can wait until after the release.

**Comment by irina060981** [comment]
Finally it looks like this
![image](https://user-images.githubusercontent.com/12377640/70281316-8052c580-1806-11ea-8e08-18ec37abc92d.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
components 1.5.0 (qa-3.0.4.83/embed-lib 3.1.5.46)

**Comment by monzug** [comment]
it's in Alpheios Reading Tools 3.0.4.93
Alpheios Components 1.5.0

not so crazy about this change, specially in the mobile. now we have this fixed frame with the two grammars and the scrolling part is reduced at a small portion of the screen even in expanded view.
also, Back to index does not work in Greek grammar (tested in Chrome and FF)
see pic of landscape view
![IMG_4115](https://user-images.githubusercontent.com/41396793/70717714-ed5dd380-1cbc-11ea-9b63-75c1100677b6.PNG)

**Comment by balmas** [comment]
Hmm. I see what you mean.  @irina060981 may be we could change this to work a little differently from the inflection table browser? Maybe once you choose a grammar it could bring you to a display of just 
that grammar, and with back buttons to choose a different grammar? @monzug what do you think about that idea?

**Comment by monzug** [comment]
removing the frame, correct? yes it could work. also back to index needs to
be fixed for greek grammar

**Comment by balmas** [comment]
ok. @irina060981 can you give that a try? Thanks!

**Comment by irina060981** [comment]
>also back to index needs to be fixed for greek grammar

It is worked for me, hmm - it is strange
@monzug, do you see any error in console?

**Comment by irina060981** [comment]
>Maybe once you choose a grammar it could bring you to a display of just
that grammar, and with back buttons to choose a different grammar?

@balmas , do you mean that we would have two back buttons or one?
If I simply hide titles on select language and we have one back button

then here it should show titles
![image](https://user-images.githubusercontent.com/12377640/70792557-35781580-1de5-11ea-9a6c-9da6bf4542e9.png)

and here return to index
![image](https://user-images.githubusercontent.com/12377640/70792704-8851cd00-1de5-11ea-91ab-7840cf3ad17f.png)

So at the last case to return to titles - we should click return twice?

**Comment by balmas** [comment]
>So at the last case to return to titles - we should click return twice?

Yes, if I am understanding correctly, I think that is fine.

The likelihood is that once a person chooses a grammar (and language) to work with, they aren't going to switch to the other one much, if at all. If and when we have multiple grammars for a single language that might change, but that isn't the case now.

The main points with showing both grammars at all in browse grammars is to show the breadth of coverage.

**Comment by monzug** [comment]
@irina060981, funny scenario: it's NOT the Greek grammar but any grammar opened after the first. so if I browse the Greek grammar first and then I go to the Latin grammar, the back to index will not work. if I browse the Latin grammar first, like I did in my testing and then browse the Greek grammar, the back to index will not work

**Comment by irina060981** [comment]
@monzug, great catch! Will fix it!
@balmas , I understood - will do then this way.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
qa-3.0.4.94/components 1.5.1

**Comment by monzug** [comment]
tested in chrome and FF. Unfortunately I cannot test in the test environment as it does point to the release build Alpheios Embedded Library 3.1.4.45
Alpheios Components 1.4.7
I did try both on mobile and on pc. @balmas?

**Comment by balmas** [comment]
shoot, sorry about that. I reset the texts-test environment and forgot to update it with the test code again. It should be there now.

**Comment by monzug** [comment]
Thanks!

**Comment by monzug** [comment]
tested in chrome component 1.5.1 on PC
can we improve the look? language selector and back to index icons are overlapping with the scrolling text. see screenshot
![back to index](https://user-images.githubusercontent.com/41396793/71670569-43fb8200-2d3e-11ea-9121-c50f6e6f0acf.JPG)

**Comment by irina060981** [comment]
>can we improve the look? language selector and back to index icons are overlapping with the scrolling

Yes, it is overlapping by its design.
Because it is sticked to the top right corner of the frame
![image](https://user-images.githubusercontent.com/12377640/71714110-389c7980-2e58-11ea-9b73-523a957f1b5d.png)

![image](https://user-images.githubusercontent.com/12377640/71714123-4520d200-2e58-11ea-8077-417c9ba5a173.png)

As Greek Grammar has text on the right side of the frame it overlaps.
That's why I added opacity to both icons.

I could suggest only to move down the whole text of the frame this way:

![image](https://user-images.githubusercontent.com/12377640/71714209-aa74c300-2e58-11ea-916c-e1833a6c4b29.png)

![image](https://user-images.githubusercontent.com/12377640/71714218-b2346780-2e58-11ea-8584-bb81a0ddaafb.png)

![image](https://user-images.githubusercontent.com/12377640/71714274-e576f680-2e58-11ea-916c-cc25019efee0.png)

But it would "eat the place" from the iframe

@balmas and @monzug , should I change this way?

**Comment by balmas** [comment]
maybe we should just fix the display of the Greek grammar title? we can left align it. That is in our control.

I think we might still have overlapping at certain resolutions though. Could we move the text down only when there isn't enough room?

**Comment by monzug** [comment]
yes. I was thinking of reducing the size of the top frame and also the space between the top grammars and the selected grammar. would that be possible?
![frame-grammars](https://user-images.githubusercontent.com/41396793/71726570-7cb25e80-2e05-11ea-98bc-553c1b3174fd.JPG)

**Comment by balmas** [comment]
yes I agree. I think we could make the selection are at the top smaller and more compact.

**Comment by irina060981** [comment]
>maybe we should just fix the display of the Greek grammar title? we can left align it. That is in our control.

@balmas, do you mean to make changes in grammar repo? inside components we couldn't fix style inside iframe.

>I think we might still have overlapping at certain resolutions though. Could we move the text down only when there isn't enough room?

I didn't quitely understand, what do you mean here.
How could we define inside iframe when it is overlapping?

**Comment by irina060981** [comment]
>yes. I was thinking of reducing the size of the top frame and also the space between the top grammars and the selected grammar. would that be possible?

@monzug , do you mean something like this?

![image](https://user-images.githubusercontent.com/12377640/71863251-05076b00-3148-11ea-85c0-b08004207c7e.png)

**Comment by monzug** [comment]
Yes! Looks great

**Comment by balmas** [comment]
> > maybe we should just fix the display of the Greek grammar title? we can left align it. That is in our control.
> 
> @balmas, do you mean to make changes in grammar repo? inside components we couldn't fix style inside iframe.
> 
> > I think we might still have overlapping at certain resolutions though. Could we move the text down only when there isn't enough room?
> 
> I didn't quitely understand, what do you mean here.
> How could we define inside iframe when it is overlapping?

Well I thought we could try on different resolutions and then set the CSS accordingly on those dimensions that we know it overlaps.  But it could be that just left aligning the title in the grammar css and the changes you made above are sufficient.

**Comment by irina060981** [comment]
@balmas, I looked at res-client repo and saw that it has no source grammar files that we retrieve from url
https://grammars.alpheios.net/smyth/xhtml/smyth.html?ts=1578441501802#table-of-contents

could you help me? Where could I see its css?

**Comment by balmas** [comment]
@irina060981 the CSS files are these:

https://github.com/alpheios-project/grammar-smyth/blob/master/xhtml/alph-tei.css
https://github.com/alpheios-project/grammar-smyth/blob/master/xhtml/tei.css

**Comment by irina060981** [comment]
Hope now it looks like much better - merged and closed

**Comment by balmas** [comment]
webextension 3.0.6-qa.1 (components 1.6.0-dev)

**Comment by monzug** [comment]
tested in Chrome and Firefox  Alpheios Reading Tools 3.0.6.97
Alpheios Components 1.6.0-dev
