### ISSUE TITLE
close language settings on lookup component after lookup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#76]
I think perhaps we should close the language settings options on the lookup component after a user does the first regular lookup after using it. Or maybe it should always be closed when the popup or panel is updated.

**Comment by balmas** [comment]
@irina060981 can you take a look at this one? I think you could probably use the same code you used for clearing the lookup text box

**Comment by irina060981** [comment]
https://github.com/alpheios-project/components/pull/111
I have done in previous pull request the foolowing workflow:
If lookup is successfull - it clears lookupText, if it is not - then lookupText is not cleared.
I have added changing the showLanguageSettings to the same place.

**Comment by irina060981** [comment]
merged
