### ISSUE TITLE
Options: remove Dodson from Greek full definitions

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#762]
I checked a Greek sentence for full and short definitions and I could not find any entry for Dodson full definition, but I could get short definition for same entries when Dodson was selected. 
@balmas reply: Dodson does not have full definitions, only short.  We should remove 
it from the list of available lexicons for full defs.

**Comment by balmas** [comment]
qa-3.0.0.57/components 1.2.27 (Safari build in Dropbox)

**Comment by monzug** [comment]
Dodson is gone from full def drop-down
