### ISSUE TITLE
offer hide login prompt button after 2 times not 3

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#771]
@abrasax thinks we should show the option to hide the login prompt sooner. I think showing it immediately makes it too easy for the user to hide the login prompt without knowing why they are being asked. So we have compromised to show it on the 2nd prompt rather than the 3rd.

**Comment by monzug** [comment]
Now it works as follow: 
don't ask again appears on the second lookup, then it stays on until end of session or user clicks on it. On reload the login appears again on 2nd prompt. tested in Chrome and FF and Safari (mobile)
