### ISSUE TITLE
usage examples - change text

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#772]
Requested by  @abrasax 
* change "(up to 3 usages per author - Focus to get more results by author)"  to
"(default display: all available authors, up to 3 examples each)"

* Change "Focus on Author:" to "Choose an Author: (up to 5000 examples, default sort by work)"
* Change "Focus on a Work:" to "Choose a Work: (up to 5000 examples, default sort by previous word)

(We need also to change the wording in the Options to correspond)

**Comment by monzug** [comment]
Only checked that they are in and looked good.
