### ISSUE TITLE
we seem to have lost some rounded corners

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#773]
Some of the buttons suddenly aren't rounded anymore. E.g. 
![Alpheios Texts (1)](https://user-images.githubusercontent.com/644870/63696956-e5e7ec80-c7e9-11e9-8cb3-62e364e083b4.png)

@irina060981 can you investigate?

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
but please test in later build, qa-3.0.0.61/components 1.2.34

**Comment by monzug** [comment]
Good catch. I did notice something weird with the style but could not figure out that it was the button!!!!! looks good now.
