### ISSUE TITLE
limit by this session when a word is already in the user word list

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#789]
Scenario: sign in with id/psw (e.g. Test@test.it  pdw: Test@123) the word unus is already in the user word list. Double click on unus (and other words) then use limit by this session, unus will not show up in the new session user list because it was already in the list. (you can use the text at https://en.wikipedia.org/wiki/Latin_declension#Personal_pronouns)
I think this works as it should but... do we want to add an other flag for this scenario?

**Comment by balmas** [comment]
I think we could just reflag the word as from the current session, don't you? Do you think it is worth distinguishing another way?

**Comment by monzug** [comment]
you are probably right but I am not sure.

**Comment by balmas** [comment]
ok. I think maybe I will let this be deferred until the next release. If users report it then we can make it a higher priority.

**Comment by monzug** [comment]
yes!

**Comment by balmas** [comment]
qa3.0.3.87/components 1.4.5

**Comment by monzug** [comment]
I really like how it does add all the entries to the show contexts page. see below

![this-session](https://user-images.githubusercontent.com/41396793/68135686-0d49ec80-fef2-11e9-82d6-d29ab4c53052.JPG)
