### ISSUE TITLE
Safari: we don't show the log in and don't ask again buttons

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#793]
if user is not logged in, we don't show the log in button and don't ask again button in login to save your words to wordlist.
see screenshot
![Screen Shot 2019-09-11 at 3 05 15 PM](https://user-images.githubusercontent.com/41396793/64699744-c1f10000-d4a5-11e9-90dc-b0a73a6fbadd.png)

**Comment by monzug** [comment]
what would the log in button do? send to the Alpheios Reading Tools?
note that also from the User account we don't have the log in / log out buttons.

**Comment by balmas** [comment]
the only thing it could do would be to send them to the user tab, which gives the instructions on how to login.  Even if we decide not to show the Login button, we should show the Don't Ask Again button.

**Comment by balmas** [comment]
@kirlat I think maybe instead of login in the notification on Safari, the Login button should say "User Account" and open the panel to the User tab. What do think?

We do still need to show the Don't Ask Again button too.

**Comment by balmas** [comment]
Safari build QA-3.0.0.70 (in Dropbox)

**Comment by monzug** [comment]
it's in there (the don't ask button and User account). the navigation is not so smooth though.
1) click on user account, it will bring up the log in (user account) tab with again user account button it it. if I click on it, nothing happens, if <i double-click on it it will open the related morphological pop-up. see screenshots
![Screen Shot 2019-09-20 at 2 43 06 PM](https://user-images.githubusercontent.com/41396793/65328034-a5477d00-dbb5-11e9-8c75-e5f167875d58.png)
![Screen Shot 2019-09-20 at 2 42 23 PM](https://user-images.githubusercontent.com/41396793/65328037-a5e01380-dbb5-11e9-8bff-bf8299c777dc.png)

**Comment by balmas** [comment]
agree we should hide the notification on the user tab in this case. that might be a little tricky though. @kirlat what do you think?

**Comment by monzug** [comment]
u are super fast. that's what I was going to ask in point 2)

**Comment by monzug** [comment]
maybe login or user account should not have the buttons at the bottom.

**Comment by balmas** [comment]
I think that's a good suggestion. I think we probably don't need the login notification on the user tab ever. But we do need the logout notification.

**Comment by monzug** [comment]
yes. that's what it does right now. see screenshot

![Screen Shot 2019-09-20 at 3 03 32 PM](https://user-images.githubusercontent.com/41396793/65328990-e04ab000-dbb7-11e9-94ce-80e377bc37f7.png)

**Comment by kirlat** [comment]
On my opinion, we need a notification (both login and logout) on the user account tab, but it'll be better to be without the button. I think notification can be good as a reminder that user needs to log in to do certain actions (access stored word list, preferences, etc.). What do you think?

**Comment by balmas** [comment]
Yes I agree.

**Comment by kirlat** [comment]
I've added this change to the `components#safari-authentication`

**Comment by balmas** [comment]
QA 3.0.1.72/components 1.2.47 (Safari Build is in Dropbox)

**Comment by monzug** [comment]
I like these changes.
