### ISSUE TITLE
Safari: missing the Alpheios build information from UI panel

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#795]
Should build info be in the UI panel in Safari builds?
see screenshot
![Screen Shot 2019-09-11 at 2 05 37 PM](https://user-images.githubusercontent.com/41396793/64701560-47c27a80-d4a9-11e9-9683-522f4697e801.png)

**Comment by balmas** [comment]
yes it should be there. I was seeing it . Are you sure it's not just below (or maybe underneath??) the notification?

**Comment by monzug** [comment]
yes, u are right. it's below the log in message not above as in the the other browsers.
