### ISSUE TITLE
vue warning on mutation of showLangSelector

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#798]
seeing warning in the console with a dev build (probably not there in non-dev builds but I wonder if it's somehow responsible for  #746 )

[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "showLangSelector"

found in

---> <Lookup> at vue/components/lookup.vue
       <Toolbar> at vue/components/nav/toolbar-large.vue
         <Root>

**Comment by balmas** [comment]
@irina060981 Can you take a look at this when you have a second? Thank you!

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
qa-3.0.1.72/components 1.2.47

@monzug there isn't an easy way for you to verify that the dev mode warning is gone, but please just retest change language functionality (sadly I don't expect this to fix #746)

**Comment by monzug** [comment]
tested change language on local file, all good.
