### ISSUE TITLE
need to pass sendFeature event from morph-inner to morph parent

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#80]
in the refactoring of the morph component to inner components of the different designs the sendFeature event stopped being emitted from the morph component to the parent popup.

(presumably there is a better way to handle emitting events from child components through to the topmost level parent than redefining the event in each component -- something to consider with the state refactoring)

**Comment by irina060981** [comment]
Ok, I see, I missed it. There are different ways to pass events through components (via props in components and in the template file) realised in the project. And sometimes it is difficult to track correctly all of them. I think refactoring a event's bus in future will solve this problem.
