### ISSUE TITLE
Credits: dedupe providers

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#801]
double click on θηρῶν from https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0561.tlg001.perseus-grc2/passage/1.praef.1-1.praef.4
you'll see the Liddell, Scott, Jones lexicon repeated 3 times.

![short-def-credits-greek](https://user-images.githubusercontent.com/41396793/64865953-8589e500-d608-11e9-9dd8-4e7fe785ca32.JPG)

**Comment by balmas** [comment]
oh shoot. I think we lost the deduping of that list at some point. @monzug do you think it's worth a new build for this? Or could it wait for the first incremental?

**Comment by monzug** [comment]
it can wait... of course!

**Comment by balmas** [comment]
in v3.0.0.67/components 1.2.44

**Comment by monzug** [comment]
fixed in v3.0.0.67/components 1.2.44
