### ISSUE TITLE
on mobile, can we open the selected table instead of the head of Inflection Browser?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#805]
Right now, when I click to open any inflection table in the browser, it takes me to the top of the browser, rather then anchor on the selected table. I need to scroll down to see the table open. tested on iPhone xr.

**Comment by balmas** [comment]
this might be similar to the problem we have scrolling to the right section of the grammar.

**Comment by balmas** [comment]
@irina060981 when you have a minute can you investigate? We won't hold the release for it but we could put it in an incremental.

**Comment by irina060981** [comment]
I suggest to solve it via js fix. (I have no  more ideas what css magic could be done with this weird bug on IPhone).

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
ready for testing at texts-test.alpheios.net in components 1.2.47

**Comment by monzug** [comment]
beautiful. Thanks
