### ISSUE TITLE
Usage example: range should be 1 to 1000?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#809]
world usage example: Max tot results field is 5000 by default, however when I edit the field, range goes from 1 to 1000 (also tooltip says that value are 1 to 1000). in order to go back to 5000 I need to click on reset all  (could not find anything on this in GitHub)
Bridget's reply: darn that was an oversight after we changed the max. I think this 
can be in an incremental though

**Comment by monzug** [comment]
@balmas, in the tutorials we still have 5000 all over the place (in Options tutorial and in Word usage Examples tutorial). so, do we want to change the UI to reflect the new limit or we stick with 5000?

**Comment by balmas** [comment]
oh shoot, we will fix the UI. This one slipped my mind.

**Comment by monzug** [comment]
No problem!!!!!

**Comment by balmas** [comment]
qa 3.0.1.73/components 1.2.48

**Comment by monzug** [comment]
tested in build
Alpheios Reading Tools 3.0.1.73
Alpheios Components 1.2.48

**Comment by monzug** [comment]
it's not in mobile. when I edit the 5000 field, the top limit is still 1000
tested in 3.0.0-rc.2.39  component 1.2.47  in texts-text.alpheios.net

**Comment by balmas** [comment]
ah sorry, I didn't push to the dev channel for texts-tests. It's there now.

**Comment by monzug** [comment]
it's there. thanks
