### ISSUE TITLE
use full url for auth0 badge

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#810]
@monzug notes that the Auth0 badge on the User tab is broken if you are using Alpheios on a local file. That's because we used a "//" url for it, which is supposed to follow the scheme used for the page (i.e. if you loaded the page as http it would use http:// and if you loaded it as https: it would use https://). There isn't a local file so it is broken.

We could just always use the https url here.

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
QA-3.0.1.72/Components 1.2.47

**Comment by monzug** [comment]
tested the icon on the local file both in Chrome and FF.
