### ISSUE TITLE
toolbar controls background is wrong color

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#812]
the lookup and help controls (.alpheios-toolbar__lookup-control and .alpheios-toolbar__help-control) have the wrong background color defined.

they are set to var(--alpheios-text-bg-color) but it should be  var(--alpheios-toolbar-bg-color)

it is causing bleeding on sites which explicitly define the background color.

e.g. see on the Alpheios poetry prototype:

![Alpheios Poetry Prototype](https://user-images.githubusercontent.com/644870/65183000-88357180-da30-11e9-97cf-50a844787808.png)

**Comment by irina060981** [comment]
Great catch! I missed it!

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
QA-3.0.1.72/Components 1.2.47
I think you can test this one on Scaife.

**Comment by monzug** [comment]
I have seen it several times indeed. didn't think it could be fixed but it is. Thanks
