### ISSUE TITLE
back to toc button not working in Smyth grammar

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#837]
not sure of the cause of this but just noticed that the back to TOC button doesn't seem to work in the Smyth (Greek) grammar, although it does in the Latin grammar.

@monzug do you see the same?

**Comment by monzug** [comment]
yes, only the Greek, just tested in the latest dev version. tested also in
Safari. it does work when from the morphology page you click on the case
e.g. voc the you open the grammar on the subject. Back to Index will take
you to main page of grammar.
when I navigate through  the sections of the Grammr and then click on Back
to Index, it does not work. sorry but I think I did only check the first
scenario (from morphology to grammar to index)

**Comment by balmas** [comment]
ok thanks for verifying @monzug. I will fix.

**Comment by balmas** [comment]
I'm not sure why, but it seems that inserting a location # in the url for the toc fixes the problem. This is changed on the server now. @monzug can you confirm that it works for you? Thanks!

**Comment by monzug** [comment]
tested in Chrome build Alpheios Reading Tools 3.0.1.80
Alpheios Components 1.4.0
scrolling through the Grammar then clicking the TOC still doesn't work. 
it does work only when linking from morphology to Grammar's section to TOC.

**Comment by balmas** [comment]
monica, just checking -- did you clear your browser cache before testing?
The index file gets cached.

**Comment by monzug** [comment]
it does work in FF. yes I did clear my cache. will try closing browser and start again.

**Comment by monzug** [comment]
it works in Chrome too. closed this one.  sorry for the confusion.
