### ISSUE TITLE
Missing Credits in morphology pop-up when landing from wordlist

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#840]
and only when limit by this session is applied. to repro: double click on any word from wordlist selected from the limit by this session list. the pop-up does not have the Credits
see screenshot
![no-credits](https://user-images.githubusercontent.com/41396793/66923055-2e57a580-eff6-11e9-8c1d-c3bc6ba0b567.JPG)

**Comment by irina060981** [comment]
The problem here is the following:
    We don't save credits information to Remote or Local Storage
    So when we select it from the list and it could retrieve data from Remote, than it will show without credits. But when it fails it creates a new lexical request then we could see Credits.
     We need to save it there if we want to publish it.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
components 1.5.0 (qa-3.0.4.83/embed-lib 3.1.5.46)

**Comment by monzug** [comment]
tested in Chrome and FF
btw, the version is Alpheios Reading Tools 3.0.4.93
Alpheios Components 1.5.0
