### ISSUE TITLE
Back to Main link from Greek verbs does not work

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#844]
I think we should remove Back to main and see declension links. tested in Safari and Chrome
lookup for ξυνέηκε  and go to the Weak (1st) Aorist System Active inflection table, click on Back to main link at the bottom of the page. it will not work. (same for see declension)

**Comment by balmas** [comment]
qa3.0.3.87/components 1.4.5

**Comment by monzug** [comment]
Bridget,
I can still see the link to Back to main which is active in Chrome (does not do anything) but not in FF. in mobile, it takes to top of the page. also see declension is still there
tested in Alpheios Reading Tools 3.0.3.87
Alpheios Components 1.4.5

**Comment by balmas** [comment]
hmm. I left the links there but I thought I fixed them so they would work.... they were working for me in chrome...

**Comment by balmas** [comment]
@monzug are you sure the links aren't working now? They do work for me in Chrome, FF and on my mobile device

**Comment by monzug** [comment]
wait! I thought you were going to remove them. 
retested in Chrome and FF.
so, they do work depending on the view. if the view is small and panel fits the screen, then back to main and see declension does not do anything.

**Comment by monzug** [comment]
if I look at the tables for ἐλῴη in FF, the back to main does not work in Future System (Active and Middle) with contraction in -έω

**Comment by balmas** [comment]
it works there for me

**Comment by monzug** [comment]
will reinstall build and try again.

**Comment by monzug** [comment]
tested in Chrome and FF. reinstall the latest build then open the latin library, in lookup change language to Greek and enter ἐλῴη. the see declension and back to main links will not work. they will work on reload or by looking at an other word.

**Comment by balmas** [comment]
that is very strange.  Do they work on ἐλῴη then after reload? Or never work for you on that word? (but really the word should not make a difference at all... )

**Comment by monzug** [comment]
after reload, yes

**Comment by balmas** [comment]
I really cannot explain that.

**Comment by balmas** [comment]
I still cannot reproduce. The only thing I can think is that somehow the prior version of the table is getting cached.  As long as it works consistently after the first reload, I think we could let this go, do you agree?

**Comment by monzug** [comment]
I did clear cache before each installation. agree that it's not a big deal.
