### ISSUE TITLE
restrict matching into paradigm tables to inflections which matched the table rules

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#846]
reported by @monzug 

Currently we iterate through all of the inflections across all lexemes to identify the paradigms that match, and then later we iterate through all of the inflections across all lexemes to identify the cells in a table that match, but we don't take into account whether the table we are looking for matches in is one whose rules actually match the inflection.

E.g. take the example of ἄγων 
This has 2 lexemes:

it's the participle of the lexeme ἄγω which is a w_stem verb
it's the indicative of the lexeme ἀγάω which is an aw_pr stem verb

So we correctly bring up 2 tables: for the participle, the Participles in -ων, -ουσα, -ον and for the indicative Present System Active of Contract Verbs in -άω, but we show a match on the participle in the latter table which is incorrect.

**Comment by balmas** [comment]
qa3.0.3.87/components 1.4.5

**Comment by monzug** [comment]
Looking at Morpheus for verb συμβέβηκε  - see screenshot of the two matching for the 1st perfect indicative and 2nd perfect indicative.
we have <stemtype>perf_act</stemtype>
<derivtype>a_stem</derivtype>
Is there any way to distinguish the 1st and 2nd perfect indicative?

![improve-matching](https://user-images.githubusercontent.com/41396793/68215963-1e583380-ffae-11e9-9e61-8c90693be635.JPG)

**Comment by monzug** [comment]
an other one is related the verb   εἰμί    to be:
1) εἶναι 
2) ἔσεσθαι
the 1) does the match with the εἰμί  inflection table    <stemtype>irreg_mi</stemtype>
2) does the match with   Future System (Active and Middle) with contraction in -έω                                             <stemtype>reg_fut</stemtype> .  (an other example is ἔσεσθον)

this is a situation in which we have the exact verb inflection tables (the verb  εἰμί  table). would it be possible to do the match like we do for the Latin irregular verbs?

**Comment by monzug** [comment]
Unfortunately issue #233 is still reproducible
ἠγγέλμεθα: participle is also highlighted but it shouldn't

**Comment by balmas** [comment]
> Is there any way to distinguish the 1st and 2nd perfect indicative?

I don't know. What do 1st and 2nd perfect mean in this case? I looked up the actual forms in the paradigm table in those columns in morpheus and the only difference I get is an additional `derivtype` of reg_conj in the form from the "1st perfect" column.  If that's reliable then we could probably add that as a matching constraint but I'm not sure if it is.

```
<infl>
<term xml:lang="grc">
<stem>λελυκ</stem>
<suff>εν</suff>
</term>
<pofs order="1">verb</pofs>
<mood>indicative</mood>
<num>plural</num>
<pers>3rd</pers>
<tense>pluperfect</tense>
<voice>active</voice>
<dial>epic Doric Aeolic</dial>
<stemtype>perf_act</stemtype>
<derivtype>reg_conj</derivtype>
<morph>unaugmented</morph>
</infl>
```
```
<infl>
<term xml:lang="grc">
<stem>λελοιπ</stem>
<suff>εν</suff>
</term>
<pofs order="1">verb</pofs>
<mood>indicative</mood>
<num>plural</num>
<pers>3rd</pers>
<tense>pluperfect</tense>
<voice>active</voice>
<dial>epic Doric Aeolic</dial>
<stemtype>perf_act</stemtype>
<morph>unaugmented</morph>
</infl>
```

**Comment by balmas** [comment]
> Unfortunately issue #233 is still reproducible
> ἠγγέλμεθα: participle is also highlighted but it shouldn't

That's a different issue than was reported with ἄγων but you're right it seems that alpheios-project/inflection-tables#233 wasn't fully fixed.  The part of speech wasn't added to all the necessary rows in that table.  Will reopen that one.

**Comment by balmas** [comment]
>an other one is related the verb εἰμί to be:

I've entered a new issue for that. Need to spend some time to investigate but it's not exactly the same problem as reported in this issue.

**Comment by monzug** [comment]
yes, I agree. this issue has been fixed and verified. while testing it, I come up with the above questions. I can close this one.
