### ISSUE TITLE
keep language consistent across all lookup compnents

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#85]
reported by @irina060981 on #78 

Bridget, I have tested the lookup saving options and see that language settings are separately saved for each one.

I am making these steps:

open a popup on a word and type a greek word in lookup and choose Greek language
click Definitions to open a panel with lookup component
image
Lookup in a panel a Latin word - bene
Get a popup with data for bene with saved lookup language settings from previous (greek)
image
and so on
Also - there are two lookup child components in the panel component.
And they also saves data apart (for the word and for language settings)

One of them (info tab) has this format with parentLanguage
145.

And the other (definition tab) has without parentLanguage
91.

May be if a user changed his/her preferance for lookup language settings in panel it should be passed to lookup in popup and be the same for both lookups in the panel?

**Comment by irina060981** [comment]
https://github.com/alpheios-project/components/pull/107

I have moved a language setting used in lookup to LocalStorage - lookupLanguage
This way it uses from Local Storage for both panel and popup

I have added to localStorage, option-item remove method.

On page unload (window.onbeforeunload) lookupLanguage deleted from LocalStorage.

On load it takes default value (it is the coommon way for options)

Updated unit tests for new workflow
