### ISSUE TITLE
problem with selection of greek text in Google Docs on Mac

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#853]
user-report

Separate from #852, there seems to be a problem with the selection of greek words from a google docs page on a mac, even in Chrome.  It looks like there are some extra characters being included in the selected text -- they are getting encoded as %E2%80%AC at the beginning and end of the selected word.

**Comment by balmas** [comment]
that's the unicode char 8204 (zero-width non-joiner) that's getting included in the text selection

**Comment by balmas** [comment]
the html entity &zwnj; is being inserted into the doc by something. 

https://support.google.com/docs/thread/11959154?hl=en

**Comment by balmas** [comment]
I think 200C and 200D should be added to the punctuation lists in the language data models. According to this article, they could have linguistic meaning in some languages, so it's better to make this language specific.

http://archives.miloush.net/michkap/archive/2006/02/15/532394.html

**Comment by balmas** [comment]
should be fixed in QA-3.0.3.89/components 1.4.7

**Comment by monzug** [comment]
just tested in chrome Alpheios Reading Tools 3.0.3.90
Alpheios Components 1.4.7
double click on the a greek word in google doc after installation will not work. it will open an empty morphology pop-up. after doing a latin lookup, double click on greek words works fine. see screenshot
![Screen Shot 2019-11-11 at 8 04 46 PM](https://user-images.githubusercontent.com/41396793/68613372-e3c72d00-04be-11ea-8d53-59874d5ad1ac.png)

**Comment by monzug** [comment]
here is a screenshot of empty pop-up
![Screen Shot 2019-11-11 at 8 09 24 PM](https://user-images.githubusercontent.com/41396793/68613576-5801d080-04bf-11ea-90d5-52a72db28946.png)

the problem is that every morphology pop-up shows the same result of the first pop-up over and over. need more testing on this but basically the morphology pop-up keeps getting generated

**Comment by balmas** [comment]
hmm. that's odd. investigating

**Comment by balmas** [comment]
something seems to have gone horribly wrong with that build, I am sorry.

I rebuilt the code and it is working for me. 

Can you please retest with qa-3.0.3.91 (components 1.4.7)

Thanks!

**Comment by monzug** [comment]
could it be my messy environment?

**Comment by balmas** [comment]
no, I was able to reproduce it. I struggled with that build because I was so confused by the auth0 error on Safari so I probably messed something up.

**Comment by monzug** [comment]
I am going to install it tomorrow. let me know which build should I use if
not xxx91

**Comment by balmas** [comment]
please use qa-3.0.3.91. There's a corresponding Safari build in Dropbox too. Grazie!

**Comment by monzug** [comment]
it does work perfectly in build qa-3.0.3.91
