### ISSUE TITLE
sticky options after log out

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#859]
build 3.0.0.91 in FF and Chrome.
login and update some preferences in Options, then log out. The default option are not applied as expected, instead the last login preferences are kept.

**Comment by monzug** [comment]
Not sure if it does matter but I usually change the following preferences: medium size into large, verbose mode, panel position right, uncheck concordance, check Latin translation

**Comment by balmas** [comment]
:-( I can't reproduce in either Firefox or Chrome.

Do you do anything between log in, changing settings and logging out? Does it happen with every account?

**Comment by monzug** [comment]
I did use several different accounts. I do usually a lookup and a double
click and sometimes I do a lookup from wordlist. uhm... something wrong
with my environment.

**Comment by balmas** [comment]
> something wrong with my environment.

maybe. Is it just in the webextension? Are there any errors in the developers console after logging out?

**Comment by monzug** [comment]
yes webextension only. could it be the file env-webext? it's not in the
dist directory any more, so I ma using the one from build xxx.25

**Comment by balmas** [comment]
it could be. Can you copy the contents of the file here?

**Comment by monzug** [comment]
const auth0Env = {
  AUTH0_DOMAIN: 'alpheios.auth0.com',
  AUTH0_CLIENT_ID: 'iT75HkBHThA4QdFwFoZRofLC41vVyvAt',
  ENDPOINTS: { 
    'wordlist' : 'https://w2tfh159s2.execute-api.us-east-2.amazonaws.com/prod/words',
  },
  AUDIENCE: 'alpheios.net:apis',
  LOGOUT_URL: 'https://alpheios.net/pages/logout'
}

**Comment by balmas** [comment]
ah yep, you're missing the settings api settings. That would probably account for this.

the END

**Comment by monzug** [comment]
so I can use that one!!!! will try tomorrow. Thanks

**Comment by monzug** [comment]
this is non issue after using the proper env-webext file
