### ISSUE TITLE
Part of speech is disappeared from Popup

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/components#880]
Now we have no part of speech for words with only one part feature from the pofs list [ 'grmCase', 'gender', 'part' ] in morph-data.vue

![image](https://user-images.githubusercontent.com/12377640/72717636-280e3200-3bc0-11ea-8d7f-d6e188eb898c.png)

it was well on 10/12/19 when I registered the issue https://github.com/alpheios-project/inflection-tables/issues/310

![image](https://user-images.githubusercontent.com/12377640/70515342-eb8ef580-1b80-11ea-9267-364fbcae6a7f.png)

**Comment by irina060981** [comment]
After some investigation we have some changes in Feature saving logic.

Before lemma was as the following:
```
lemma:
    features:
        part:  
```

And so we could use `Feature.types` to iterate through lemma's features.

But after some updates now we have the following structure
```
lemma:
    features:
        part of speech:  
```
This way part feature is unaccessible for infl-attribute.vue (even if we try to use `part of speech` as a type for the component.

**Comment by irina060981** [comment]
I haven't found the source of this change - So I suggest to fix `morph-data.vue`

**Comment by balmas** [comment]
webextension 3.0.6-qa.1 (components 1.6.0-dev)

@monzug FYI, you can now download zips of qa builds directly from releases in GitHub e.g. this one is available via 
https://github.com/alpheios-project/webextension/releases/download/v3.0.6-qa.1/qa.zip
(you will have to manually copy in the env-webext.js for now).
Or you can continue to access it from the release tag, e.g. at https://github.com/alpheios-project/webextension/tree/v3.0.6-qa.1/dist

We're still working through some improvements on the build automation and versioning so the use of a "dev" version for components in a qa build is temporary.

**Comment by monzug** [comment]
tested in Firefox and Chrome Alpheios Reading Tools 3.0.6.97
Alpheios Components 1.6.0-dev
