### ISSUE TITLE
replace grammar icon

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#89]
we are currently reusing a standard "more" icon for the grammar. This will be needed for other more appropriate uses so we should replace it with something. We used a single quotation in Alpheios V1 for this: https://github.com/alpheios-project/design-guidelines/blob/master/v1/fficons/grammar_32.png . Maybe we should create an svg version of that for now until we do a full design pass.

**Comment by irina060981** [comment]
Icon changed - https://github.com/alpheios-project/components/pull/106
