### ISSUE TITLE
replace inflection tables icon

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#90]
the current inflection tables icon (the hamburger) is normally used to represent a menu and we would like to be able to use it for that meaning, so we should replace it. In Alpheios V1 we used a table icon to represent this feature. https://github.com/alpheios-project/design-guidelines/blob/master/v1/fficons/inflection_32.png Perhaps we can create an svg version of that.

**Comment by irina060981** [comment]
Icon changed - #106
